### ISSUE TITLE
SignaturePacket: unsupported version: 192

### ISSUE THREAD

**Issue by dschuermann** [open-keychain/open-keychain#1012]
from G Play

```
java.lang.RuntimeException: An error occured while executing doInBackground()
at android.support.v4.content.ModernAsyncTask$3.done(ModernAsyncTask.java:137)
at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
at java.util.concurrent.FutureTask.run(FutureTask.java:242)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
at java.lang.Thread.run(Thread.java:841)
Caused by: java.lang.RuntimeException: unsupported version: 192
at org.spongycastle.bcpg.SignaturePacket.<init>(SignaturePacket.java:123)
at org.spongycastle.bcpg.BCPGInputStream.readPacket(BCPGInputStream.java:232)
at org.spongycastle.openpgp.PGPSignature.<init>(PGPSignature.java:57)
at org.spongycastle.openpgp.PGPObjectFactory.nextObject(PGPObjectFactory.java:112)
at org.sufficientlysecure.keychain.pgp.UncachedKeyRing$2.cacheNext(UncachedKeyRing.java:177)
at org.sufficientlysecure.keychain.pgp.UncachedKeyRing$2.hasNext(UncachedKeyRing.java:200)
at org.sufficientlysecure.keychain.ui.adapter.ImportKeysListLoader.generateListOfKeyrings(ImportKeysListLoader.java:131)
at org.sufficientlysecure.keychain.ui.adapter.ImportKeysListLoader.loadInBackground(ImportKeysListLoader.java:82)
at org.sufficientlysecure.keychain.ui.adapter.ImportKeysListLoader.loadInBackground(ImportKeysListLoader.java:39)
at android.support.v4.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:242)
at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:51)
at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:40)
at android.support.v4.content.ModernAsyncTask$2.call(ModernAsyncTask.java:123)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
... 3 more
```

**Comment by Valodim** [comment]
Test case + fix done, also improved the exception handling in our fromStream method while I was at it

**Comment by dschuermann** [comment]
A pull request on bouncycastle would be nice: https://github.com/bcgit/bc-java/pulls
