### ISSUE TITLE
Crash after key import from file

### ISSUE THREAD

**Issue by scento** [open-keychain/open-keychain#1035]
Every time after I successfully imported an gnupg key via file, OpenKeychain crashes.

**Logcat:**
```
E/AndroidRuntime(10476): FATAL EXCEPTION: main
E/AndroidRuntime(10476): Process: org.sufficientlysecure.keychain, PID: 10476
E/AndroidRuntime(10476): java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=0, result=-1, data=Intent { (has extras) }} to activity {org.sufficientlysecure.keychain/org.sufficientlysecure.keychain.ui.KeyListActivity}: java.lang.IllegalArgumentException: SuperCardToast - You must have a LinearLayout with the id of card_container in your layout!
E/AndroidRuntime(10476):        at android.app.ActivityThread.deliverResults(ActivityThread.java:3351)
E/AndroidRuntime(10476):        at android.app.ActivityThread.handleSendResult(ActivityThread.java:3394)
E/AndroidRuntime(10476):        at android.app.ActivityThread.access$1300(ActivityThread.java:135)
E/AndroidRuntime(10476):        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1244)
E/AndroidRuntime(10476):        at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(10476):        at android.os.Looper.loop(Looper.java:136)
E/AndroidRuntime(10476):        at android.app.ActivityThread.main(ActivityThread.java:5001)
E/AndroidRuntime(10476):        at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(10476):        at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime(10476):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
E/AndroidRuntime(10476):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
E/AndroidRuntime(10476):        at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
E/AndroidRuntime(10476):        at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime(10476): Caused by: java.lang.IllegalArgumentException: SuperCardToast - You must have a LinearLayout with the id of card_container in your layout!
E/AndroidRuntime(10476):        at com.github.johnpersano.supertoasts.SuperCardToast.<init>(SuperCardToast.java:284)
E/AndroidRuntime(10476):        at org.sufficientlysecure.keychain.operations.results.ImportKeyResult.createNotify(ImportKeyResult.java:186)
E/AndroidRuntime(10476):        at org.sufficientlysecure.keychain.ui.KeyListActivity.onActivityResult(KeyListActivity.java:231)
E/AndroidRuntime(10476):        at android.app.Activity.dispatchActivityResult(Activity.java:5423)
E/AndroidRuntime(10476):        at android.app.ActivityThread.deliverResults(ActivityThread.java:3347)
E/AndroidRuntime(10476):        ... 12 more
```

**Versions:**
AOSP 4.4.4 on Nexus 5 (hammerhead)
OpenKeychain, commit 6c6201f1292951fdc25b355c1693045d94186ff2
XPrivacy 3.6, not restricting OpenKeychain

**Comment by dschuermann** [comment]
You are using the development branch :dancers:

**Comment by dschuermann** [comment]
Will work on these problems today...
