### ISSUE TITLE
Update MaterialNavigationDrawer when version 1.3.3 is out

### ISSUE THREAD

**Issue by dschuermann** [open-keychain/open-keychain#1061]
due to https://github.com/neokree/MaterialNavigationDrawer/issues/193

Also enable multipane, seems to be fixed in 1.3.3

https://github.com/neokree/MaterialNavigationDrawer

**Comment by dschuermann** [comment]
Also enable multipane, seems to be fixed in 1.3.3

**Comment by dschuermann** [comment]
1.3.3 is crashing :/
```
  449          AndroidRuntime  E  Caused by: java.lang.RuntimeException: You are trying to open at startup a section that does not exist
  449          AndroidRuntime  E  at it.neokree.materialnavigationdrawer.MaterialNavigationDrawer.onCreate(MaterialNavigationDrawer.java:702)
  449          AndroidRuntime  E  at android.app.Activity.performCreate(Activity.java:5933)
  449          AndroidRuntime  E  at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105)
  449          AndroidRuntime  E  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2282)
  449          AndroidRuntime  E  ... 10 more
```

**Comment by ChristopheVersieux** [comment]
What can we do to avoid this crash? Is 1.3.3 not ready for release or do we have to update code?

**Comment by vectorijk** [comment]
@ChristopheVersieux We updated and switched to MaterialDrawer library #1197
