### ISSUE TITLE
Import progress sometimes reset to 0%

### ISSUE THREAD

**Issue by dschuermann** [open-keychain/open-keychain#1077]
Somehow the dialog showed 0% and no progress half way through a previously successfull import.

**Comment by indrora** [comment]
When you say "many keys", is this "many private keys (e.g. a ton of RSA/DSA keypairs) or "Here's a hundred thousand public keys"?

**Comment by dschuermann** [comment]
100 public keys + 5 public/private key pairs

**Comment by indrora** [comment]
Huh, happens when I import ~650 keys, but not when I import ~200. According to [the documentation](http://developer.android.com/reference/android/os/TransactionTooLargeException.html), the key importer is creating a Parcel that's too big for the binder -- Bigger than 1MB.

**Comment by indrora** [comment]
Found the root cause: Logs.

Android has a maximum cap on how big a Parcel/intent can be. Since the log is schlepped over the activity boundary as an extra, It counts towards the parcel weight.

I'm not sure what I can do to reduce it. All that the log contains is a bunch of integers, really. The only thing I can think of is a Singleton that just handles logs, but I'd rather not add a LogManager somewhere it doesn't belong (that'd be a hack, and I don't want that in something that's supposed to be secure).

Here's my current ideas to solve this:

* Implement a `LogManager` -- you feed it logs and it gives you tickets out. You can hand it a ticket and it returns you a log (makes keeping logs easier, but it adds a layer of complexity to logs themselves)
* In all operations that work with logs, have a singleton `OperationLog` that we carry around.
* Use the global Application to keep logs. This works, but isn't a terribly great idea, I don't think.

Fundamentally, big logs are breaking the 1MB parcel size cap, and big enough key imports are creating big logs.

**Comment by indrora** [comment]
I've chosen a variation on option 2 which doesn't change the API at all.

**Comment by indrora** [comment]
It appears this is two bugs in one! yay!

The `TransactionTooLargeException` was caused by a log being huge, but there's another problem that comes when you run Consolidate: the OOM killer.

This happens most when *not* running under debugging -- I cannot reproduce the issue when we are plugged in and adb is running. Possible reason? We're *slowing* something down by spewing so much into the debug log that we're avoiding a dead-ness. Or, alternatively, the GC runs differently when adb is running. 

My reasoning for this is that Android Studio, during a consolidation (and import) regularly spits out the message "Too much to handle!" and I get ADB messages *long* after I've finished an import action. Something in import might be [logging too much](https://source.android.com/source/code-style.html#log-sparingly).

When you import a ton of keys (say, several megs worth) and run consolidate, and are not running adb in the background, you get this:

```
03-03 10:24:14.324    6072-6093/org.sufficientlysecure.keychain W/Keychain﹕ Exception sending message, Is handler present?
    android.os.DeadObjectException
            at android.os.BinderProxy.transactNative(Native Method)
            at android.os.BinderProxy.transact(Binder.java:496)
            at android.os.IMessenger$Stub$Proxy.send(IMessenger.java:89)
            at android.os.Messenger.send(Messenger.java:57)
            at org.sufficientlysecure.keychain.service.KeychainIntentService.sendMessageToHandler(KeychainIntentService.java:618)
            at org.sufficientlysecure.keychain.service.KeychainIntentService.sendMessageToHandler(KeychainIntentService.java:629)
            at org.sufficientlysecure.keychain.service.KeychainIntentService.onHandleIntent(KeychainIntentService.java:262)
            at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.os.HandlerThread.run(HandlerThread.java:61)
```

In adb, I get plenty of messages stating that the progress is being updated:

```
03-03 10:36:31.811    6950-7379/org.sufficientlysecure.keychain D/Keychain﹕ Send message by setProgress with progress=81, max=100
03-03 10:36:31.812    6950-7384/org.sufficientlysecure.keychain D/Keychain﹕ Query: SELECT keys.oid AS _id, keys.master_key_id, user_id, keys.is_revoked, keys.expiry, verified, (EXISTS (SELECT * FROM keyrings_secret WHERE keyrings_secret.master_key_id = keys.master_key_id)) AS has_any_secret FROM keys INNER JOIN user_ids ON (keys.master_key_id = user_ids.master_key_id AND user_ids.rank = 0) LEFT JOIN certs ON (keys.master_key_id = certs.master_key_id AND certs.verified = 1) WHERE (keys.rank = 0) ORDER BY has_any_secret DESC, UPPER(user_id) ASC
03-03 10:36:31.838    6950-7379/org.sufficientlysecure.keychain D/Keychain﹕ Send message by setProgress with progress=81, max=100
```

... Something isn't happening on the UI thread. I don't know what at this point, but it's not happening.

**Comment by Valodim** [comment]
that makes sense. the progress message granularity is intended for a single key import, but it's still all sent for each import. there's probably something like 15 progress updates per key, so 3k progress updates in rapid succession during the import of (or consolidation with) 200 keys.

**Comment by indrora** [comment]
The dialog isn't getting not-updates, there's two dialogs.

When I trace out the calls to `showProgressDialog`, I get this:

KISH here is KeychainIntentServiceHandler, SPD is showProgressDialog.

```
03-03 16:07:37.769  10136-10136/org.sufficientlysecure.keychain I/KISH﹕ SPD Activity: org.sufficientlysecure.keychain.ui.ConsolidateDialogActivity@8937fbd
    java.lang.Throwable
            at org.sufficientlysecure.keychain.service.KeychainIntentServiceHandler.showProgressDialog(KeychainIntentServiceHandler.java:84)
            at org.sufficientlysecure.keychain.ui.ConsolidateDialogActivity.consolidateRecovery(ConsolidateDialogActivity.java:94)
            at org.sufficientlysecure.keychain.ui.ConsolidateDialogActivity.onCreate(ConsolidateDialogActivity.java:46)
            at android.app.Activity.performCreate(Activity.java:5940)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2267)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2376)
            at android.app.ActivityThread.access$800(ActivityThread.java:147)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1281)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5239)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
03-03 16:07:41.958  10136-10136/org.sufficientlysecure.keychain I/KISH﹕ SPD Activity: org.sufficientlysecure.keychain.ui.ConsolidateDialogActivity@3b954606
    java.lang.Throwable
            at org.sufficientlysecure.keychain.service.KeychainIntentServiceHandler.showProgressDialog(KeychainIntentServiceHandler.java:84)
            at org.sufficientlysecure.keychain.ui.ConsolidateDialogActivity.consolidateRecovery(ConsolidateDialogActivity.java:94)
            at org.sufficientlysecure.keychain.ui.ConsolidateDialogActivity.onCreate(ConsolidateDialogActivity.java:46)
            at android.app.Activity.performCreate(Activity.java:5940)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2267)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2376)
            at android.app.ActivityThread.access$800(ActivityThread.java:147)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1281)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5239)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
```

I've reduced `KeylistFragment`'s `consolidate()` to

```
    private void consolidate() {
        Intent consolidateIntent = new Intent(this.getActivity(), ConsolidateDialogActivity.class);
        consolidateIntent.putExtra(ConsolidateDialogActivity.EXTRA_CONSOLIDATE_RECOVERY, false);
        consolidateIntent.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
        startActivity(consolidateIntent);

```

so that it's more consistent with the invocation from other places (namely, the Application instance)

I don't know what's creating a second `ConsolidateDialogActivity` invocation or why it's being started twice. I'll keep digging.

**Comment by Valodim** [comment]
Sorry this took a while, way busy at the moment:

Some background: consolidate sets a flag when it wrote down all the keys, that there is an unfinished consolidation going on. Once it's finished, the flag is set to off, so that is fine. In the Application class, this flag is checked and if it's set, the second part of consolidation is run again.

The problem is that the flag is process-independent, while static variables are process-dependent. During the consolidation, an extra process is started (I'm guessing for passphrase checking?), which checks if consolidation is finished, finds it is not, thus sparks a ConsolidateDialogActivity.

I'm really not sure how we should handle this yet. I think the easiest way is checking in MainActivity rather than Application.

**Comment by Valodim** [comment]
(also this is definitely not a simple one patch, sorry for the confusion. that doesn't mean you can't work on it, just that it's not "simple" by any means)

**Comment by indrora** [comment]
There's multiple facets to this bug; I'm leaving this as it stands, close the PR's related.
