### ISSUE TITLE
NullPointerException when signing with YubiKey

### ISSUE THREAD

**Issue by dschuermann** [open-keychain/open-keychain#1152]
Sign via API and Yubikey key: 
```
21053               Keychain  D  signImpl
 21053               Keychain  D  java.lang.NullPointerException: Attempt to invoke virtual method 'long java.lang.Long.longValue()' on a null object reference
 21053               Keychain  D  at org.sufficientlysecure.keychain.pgp.PgpSignEncryptOperation.execute(PgpSignEncryptOperation.java:492)
 21053               Keychain  D  at org.sufficientlysecure.keychain.remote.OpenPgpService.signImpl(OpenPgpService.java:290)
 21053               Keychain  D  at org.sufficientlysecure.keychain.remote.OpenPgpService.access$100(OpenPgpService.java:65)
 21053               Keychain  D  at org.sufficientlysecure.keychain.remote.OpenPgpService$1.execute(OpenPgpService.java:795)
 21053               Keychain  D  at org.openintents.openpgp.IOpenPgpService$Stub.onTransact(IOpenPgpService.java:69)
 21053               Keychain  D  at android.os.Binder.execTransact(Binder.java:446)
 20022               Keychain  E  onError getErrorId:0
 20022               Keychain  E  onError getMessage:Attempt to invoke virtual method 'long java.lang.Long.longValue()' on a null object reference
```

**Comment by kentnek** [comment]
This is due to `input.getSignatureSubKeyId()` (which is a `Long`) can be `null`. Can I return a `PgpSignEncryptResult` with `PgpSignEncryptResult.RESULT_ERROR` as the `result`?
