### ISSUE TITLE
crash in tokenautocomplete

### ISSUE THREAD

**Issue by Valodim** [open-keychain/open-keychain#1227]
```
 10470         AndroidRuntime  E  FATAL EXCEPTION: main
 10470         AndroidRuntime  E  Process: org.sufficientlysecure.keychain, PID: 10470
 10470         AndroidRuntime  E  java.lang.RuntimeException: Unable to destroy activity {org.sufficientlysecure.keychain/org.sufficientlysecure.keychain.ui.EncryptTextActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.Object.toString()' on a null object reference
 10470         AndroidRuntime  E  at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3702)
 10470         AndroidRuntime  E  at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3720)
 10470         AndroidRuntime  E  at android.app.ActivityThread.access$1500(ActivityThread.java:147)
 10470         AndroidRuntime  E  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1350)
 10470         AndroidRuntime  E  at android.os.Handler.dispatchMessage(Handler.java:102)
 10470         AndroidRuntime  E  at android.os.Looper.loop(Looper.java:135)
 10470         AndroidRuntime  E  at android.app.ActivityThread.main(ActivityThread.java:5256)
 10470         AndroidRuntime  E  at java.lang.reflect.Method.invoke(Native Method)
 10470         AndroidRuntime  E  at java.lang.reflect.Method.invoke(Method.java:372)
 10470         AndroidRuntime  E  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:898)
 10470         AndroidRuntime  E  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:693)
 10470         AndroidRuntime  E  Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.Object.toString()' on a null object reference
 10470         AndroidRuntime  E  at com.tokenautocomplete.TokenCompleteTextView.replaceText(TokenCompleteTextView.java:729)
 10470         AndroidRuntime  E  at com.tokenautocomplete.TokenCompleteTextView.performCompletion(TokenCompleteTextView.java:420)
 10470         AndroidRuntime  E  at com.tokenautocomplete.TokenCompleteTextView.onFocusChanged(TokenCompleteTextView.java:683)
 10470         AndroidRuntime  E  at org.sufficientlysecure.keychain.ui.widget.EncryptKeyCompletionView.onFocusChanged(EncryptKeyCompletionView.java:159)
 10470         AndroidRuntime  E  at android.view.View.clearFocusInternal(View.java:5065)
 10470         AndroidRuntime  E  at android.view.View.unFocus(View.java:5098)
 10470         AndroidRuntime  E  at android.view.ViewGroup.unFocus(ViewGroup.java:962)
 10470         AndroidRuntime  E  at android.view.ViewGroup.removeViewInternal(ViewGroup.java:4148)
 10470         AndroidRuntime  E  at android.view.ViewGroup.removeViewInternal(ViewGroup.java:4136)
 10470         AndroidRuntime  E  at android.view.ViewGroup.removeView(ViewGroup.java:4068)
 10470         AndroidRuntime  E  at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1057)
 10470         AndroidRuntime  E  at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1138)
 10470         AndroidRuntime  E  at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1120)
 10470         AndroidRuntime  E  at android.support.v4.app.FragmentManagerImpl.dispatchDestroy(FragmentManager.java:1966)
 10470         AndroidRuntime  E  at android.support.v4.app.FragmentActivity.onDestroy(FragmentActivity.java:316)
 10470         AndroidRuntime  E  at android.support.v7.app.AppCompatActivity.onDestroy(AppCompatActivity.java:158)
 10470         AndroidRuntime  E  at android.app.Activity.performDestroy(Activity.java:6112)
 10470         AndroidRuntime  E  at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1140)
 10470         AndroidRuntime  E  at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3689)
```

happened at a click on the back button (top left) in the encrypt text dialog while the encrypt to field was focused

**Comment by dschuermann** [comment]
closed with https://github.com/open-keychain/open-keychain/commit/e91dc022fbd5d616c2ac1b5bbd47a693b9f8f8d1
