### ISSUE TITLE
StrictMode policy violation on key creation

### ISSUE THREAD

**Issue by dschuermann** [open-keychain/open-keychain#1255]
On key creation with default config on Android 5.1.1 (cyanogenmod 12.1-20150423-NIGHTLY-z3)
```
 28655             StrictMode  D  StrictMode policy violation; ~duration=192 ms: android.os.StrictMode$StrictModeDiskReadViolation: policy=31 violation=2
 28655             StrictMode  D  at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1137)
 28655             StrictMode  D  at libcore.io.BlockGuardOs.open(BlockGuardOs.java:182)
 28655             StrictMode  D  at libcore.io.IoUtils.canOpenReadOnly(IoUtils.java:165)
 28655             StrictMode  D  at dalvik.system.DexPathList.findLibrary(DexPathList.java:383)
 28655             StrictMode  D  at dalvik.system.BaseDexClassLoader.findLibrary(BaseDexClassLoader.java:77)
 28655             StrictMode  D  at java.lang.Runtime.loadLibrary(Runtime.java:360)
 28655             StrictMode  D  at java.lang.System.loadLibrary(System.java:988)
 28655             StrictMode  D  at com.google.android.apps.gmm.map.util.jni.NativeHelper.initialize(PG:48)
 28655             StrictMode  D  at com.google.android.apps.gmm.map.m.g.<clinit>(PG:86)
 28655             StrictMode  D  at com.google.android.apps.gmm.base.app.d.a(PG:1179)
 28655             StrictMode  D  at com.google.android.apps.gmm.base.app.d.<init>(PG:624)
 28655             StrictMode  D  at com.google.android.apps.gmm.base.app.GoogleMapsApplication.a(PG:156)
 28655             StrictMode  D  at com.google.android.apps.gmm.base.app.GoogleMapsApplication.onCreate(PG:124)
 28655             StrictMode  D  at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1012)
 28655             StrictMode  D  at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4588)
 28655             StrictMode  D  at android.app.ActivityThread.access$1600(ActivityThread.java:154)
 28655             StrictMode  D  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1382)
 28655             StrictMode  D  at android.os.Handler.dispatchMessage(Handler.java:102)
 28655             StrictMode  D  at android.os.Looper.loop(Looper.java:135)
 28655             StrictMode  D  at android.app.ActivityThread.main(ActivityThread.java:5293)
 28655             StrictMode  D  at java.lang.reflect.Method.invoke(Native Method)
 28655             StrictMode  D  at java.lang.reflect.Method.invoke(Method.java:372)
 28655             StrictMode  D  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
 28655             StrictMode  D  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
 28655             StrictMode  D  StrictMode policy violation; ~duration=148 ms: android.os.StrictMode$StrictModeDiskReadViolation: policy=31 violation=2
 28655             StrictMode  D  at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1137)
 28655             StrictMode  D  at libcore.io.BlockGuardOs.access(BlockGuardOs.java:67)
 28655             StrictMode  D  at java.io.File.doAccess(File.java:283)
 28655             StrictMode  D  at java.io.File.exists(File.java:363)
 28655             StrictMode  D  at android.app.ContextImpl.createFilesDirLocked(ContextImpl.java:1035)
 28655             StrictMode  D  at android.app.ContextImpl.getFilesDir(ContextImpl.java:1058)
 28655             StrictMode  D  at android.app.ContextImpl.openFileInput(ContextImpl.java:1000)
 28655             StrictMode  D  at android.content.ContextWrapper.openFileInput(ContextWrapper.java:182)
 28655             StrictMode  D  at com.google.android.apps.gmm.shared.f.h.a(PG:150)
 28655             StrictMode  D  at com.google.android.apps.gmm.map.m.s.a(PG:9675)
 28655             StrictMode  D  at com.google.b.a.cb.a(PG:125)
 28655             StrictMode  D  at com.google.android.apps.gmm.map.m.g.a(PG:1493)
 28655             StrictMode  D  at com.google.android.apps.gmm.base.app.d.a(PG:1179)
 28655             StrictMode  D  at com.google.android.apps.gmm.base.app.d.<init>(PG:624)
 28655             StrictMode  D  at com.google.android.apps.gmm.base.app.GoogleMapsApplication.a(PG:156)
 28655             StrictMode  D  at com.google.android.apps.gmm.base.app.GoogleMapsApplication.onCreate(PG:124)
 28655             StrictMode  D  at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1012)
 28655             StrictMode  D  at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4588)
 28655             StrictMode  D  at android.app.ActivityThread.access$1600(ActivityThread.java:154)
 28655             StrictMode  D  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1382)
 28655             StrictMode  D  at android.os.Handler.dispatchMessage(Handler.java:102)
 28655             StrictMode  D  at android.os.Looper.loop(Looper.java:135)
 28655             StrictMode  D  at android.app.ActivityThread.main(ActivityThread.java:5293)
 28655             StrictMode  D  at java.lang.reflect.Method.invoke(Native Method)
 28655             StrictMode  D  at java.lang.reflect.Method.invoke(Method.java:372)
 28655             StrictMode  D  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
 28655             StrictMode  D  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
 28655             StrictMode  D  StrictMode policy violation; ~duration=148 ms: android.os.StrictMode$StrictModeDiskReadViolation: policy=31 violation=2
 28655             StrictMode  D  at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1137)
 28655             StrictMode  D  at libcore.io.BlockGuardOs.open(BlockGuardOs.java:182)
 28655             StrictMode  D  at libcore.io.IoBridge.open(IoBridge.java:442)
 28655             StrictMode  D  at java.io.FileInputStream.<init>(FileInputStream.java:76)
 28655             StrictMode  D  at android.app.ContextImpl.openFileInput(ContextImpl.java:1001)
 28655             StrictMode  D  at android.content.ContextWrapper.openFileInput(ContextWrapper.java:182)
 28655             StrictMode  D  at com.google.android.apps.gmm.shared.f.h.a(PG:150)
 28655             StrictMode  D  at com.google.android.apps.gmm.map.m.s.a(PG:9675)
 28655             StrictMode  D  at com.google.b.a.cb.a(PG:125)
 28655             StrictMode  D  at com.google.android.apps.gmm.map.m.g.a(PG:1493)
 28655             StrictMode  D  at com.google.android.apps.gmm.base.app.d.a(PG:1179)
 28655             StrictMode  D  at com.google.android.apps.gmm.base.app.d.<init>(PG:624)
 28655             StrictMode  D  at com.google.android.apps.gmm.base.app.GoogleMapsApplication.a(PG:156)
 28655             StrictMode  D  at com.google.android.apps.gmm.base.app.GoogleMapsApplication.onCreate(PG:124)
 28655             StrictMode  D  at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1012)
 28655             StrictMode  D  at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4588)
 28655             StrictMode  D  at android.app.ActivityThread.access$1600(ActivityThread.java:154)
 28655             StrictMode  D  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1382)
 28655             StrictMode  D  at android.os.Handler.dispatchMessage(Handler.java:102)
 28655             StrictMode  D  at android.os.Looper.loop(Looper.java:135)
 28655             StrictMode  D  at android.app.ActivityThread.main(ActivityThread.java:5293)
 28655             StrictMode  D  at java.lang.reflect.Method.invoke(Native Method)
 28655             StrictMode  D  at java.lang.reflect.Method.invoke(Method.java:372)
 28655             StrictMode  D  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
 28655             StrictMode  D  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
 28655             StrictMode  D  StrictMode policy violation; ~duration=147 ms: android.os.StrictMode$StrictModeDiskReadViolation: policy=31 violation=2
 28655             StrictMode  D  at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1137)
 28655             StrictMode  D  at libcore.io.BlockGuardOs.fstat(BlockGuardOs.java:132)
 28655             StrictMode  D  at libcore.io.IoBridge.open(IoBridge.java:445)
 28655             StrictMode  D  at java.io.FileInputStream.<init>(FileInputStream.java:76)
 28655             StrictMode  D  at android.app.ContextImpl.openFileInput(ContextImpl.java:1001)
 28655             StrictMode  D  at android.content.ContextWrapper.openFileInput(ContextWrapper.java:182)
 28655             StrictMode  D  at com.google.android.apps.gmm.shared.f.h.a(PG:150)
 28655             StrictMode  D  at com.google.android.apps.gmm.map.m.s.a(PG:9675)
 28655             StrictMode  D  at com.google.b.a.cb.a(PG:125)
 28655             StrictMode  D  at com.google.android.apps.gmm.map.m.g.a(PG:1493)
 28655             StrictMode  D  at com.google.android.apps.gmm.base.app.d.a(PG:1179)
 28655             StrictMode  D  at com.google.android.apps.gmm.base.app.d.<init>(PG:624)
 28655             StrictMode  D  at com.google.android.apps.gmm.base.app.GoogleMapsApplication.a(PG:156)
 28655             StrictMode  D  at com.google.android.apps.gmm.base.app.GoogleMapsApplication.onCreate(PG:124)
 28655             StrictMode  D  at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1012)
 28655             StrictMode  D  at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4588)
 28655             StrictMode  D  at android.app.ActivityThread.access$1600(ActivityThread.java:154)
 28655             StrictMode  D  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1382)
 28655             StrictMode  D  at android.os.Handler.dispatchMessage(Handler.java:102)
 28655             StrictMode  D  at android.os.Looper.loop(Looper.java:135)
 28655             StrictMode  D  at android.app.ActivityThread.main(ActivityThread.java:5293)
 28655             StrictMode  D  at java.lang.reflect.Method.invoke(Native Method)
 28655             StrictMode  D  at java.lang.reflect.Method.invoke(Method.java:372)
 28655             StrictMode  D  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
 28655             StrictMode  D  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
 28655             StrictMode  D  StrictMode policy violation; ~duration=139 ms: android.os.StrictMode$StrictModeDiskReadViolation: policy=31 violation=2
 28655             StrictMode  D  at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1137)
 28655             StrictMode  D  at libcore.io.BlockGuardOs.read(BlockGuardOs.java:229)
 28655             StrictMode  D  at libcore.io.IoBridge.read(IoBridge.java:472)
 28655             StrictMode  D  at java.io.FileInputStream.read(FileInputStream.java:177)
 28655             StrictMode  D  at java.io.BufferedInputStream.read(BufferedInputStream.java:290)
 28655             StrictMode  D  at java.io.DataInputStream.read(DataInputStream.java:63)
 28655             StrictMode  D  at com.google.r.j.c(PG:1187)
 28655             StrictMode  D  at com.google.r.j.a(PG:2107)
 28655             StrictMode  D  at com.google.v.a.a.ds.<init>(PG:24)
 28655             StrictMode  D  at com.google.v.a.a.ds.a(PG:9409)
 28655             StrictMode  D  at com.google.r.t.a(PG:1196)
 28655             StrictMode  D  at com.google.r.w.a(PG:2223)
 28655             StrictMode  D  at com.google.r.e.b(PG:170)
 28655             StrictMode  D  at com.google.r.e.b(PG:10188)
 28655             StrictMode  D  at com.google.android.apps.gmm.shared.f.h.a(PG:151)
 28655             StrictMode  D  at com.google.android.apps.gmm.map.m.s.a(PG:9675)
 28655             StrictMode  D  at com.google.b.a.cb.a(PG:125)
 28655             StrictMode  D  at com.google.android.apps.gmm.map.m.g.a(PG:1493)
 28655             StrictMode  D  at com.google.android.apps.gmm.base.app.d.a(PG:1179)
 28655             StrictMode  D  at com.google.android.apps.gmm.base.app.d.<init>(PG:624)
 28655             StrictMode  D  at com.google.android.apps.gmm.base.app.GoogleMapsApplication.a(PG:156)
 28655             StrictMode  D  at com.google.android.apps.gmm.base.app.GoogleMapsApplication.onCreate(PG:124)
 28655             StrictMode  D  at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1012)
 28655             StrictMode  D  at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4588)
 28655             StrictMode  D  at android.app.ActivityThread.access$1600(ActivityThread.java:154)
 28655             StrictMode  D  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1382)
 28655             StrictMode  D  at android.os.Handler.dispatchMessage(Handler.java:102)
 28655             StrictMode  D  at android.os.Looper.loop(Looper.java:135)
 28655             StrictMode  D  at android.app.ActivityThread.main(ActivityThread.java:5293)
 28655             StrictMode  D  at java.lang.reflect.Method.invoke(Native Method)
 28655             StrictMode  D  at java.lang.reflect.Method.invoke(Method.java:372)
 28655             StrictMode  D  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
 28655             StrictMode  D  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
 28655             StrictMode  D  StrictMode policy violation; ~duration=137 ms: android.os.StrictMode$StrictModeDiskReadViolation: policy=31 violation=2
 28655             StrictMode  D  at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1137)
 28655             StrictMode  D  at libcore.io.BlockGuardOs.read(BlockGuardOs.java:229)
 28655             StrictMode  D  at libcore.io.IoBridge.read(IoBridge.java:472)
 28655             StrictMode  D  at java.io.FileInputStream.read(FileInputStream.java:177)
 28655             StrictMode  D  at java.io.BufferedInputStream.read(BufferedInputStream.java:290)
 28655             StrictMode  D  at java.io.DataInputStream.read(DataInputStream.java:63)
 28655             StrictMode  D  at com.google.r.j.c(PG:1187)
 28655             StrictMode  D  at com.google.r.j.b(PG:9147)
 28655             StrictMode  D  at com.google.r.j.g(PG:583)
 28655             StrictMode  D  at com.google.v.a.a.ds.<init>(PG:43)
 28655             StrictMode  D  at com.google.v.a.a.ds.a(PG:9409)
 28655             StrictMode  D  at com.google.r.t.a(PG:1196)
 28655             StrictMode  D  at com.google.r.w.a(PG:2223)
 28655             StrictMode  D  at com.google.r.e.b(PG:170)
 28655             StrictMode  D  at com.google.r.e.b(PG:10188)
 28655             StrictMode  D  at com.google.android.apps.gmm.shared.f.h.a(PG:151)
 28655             StrictMode  D  at com.google.android.apps.gmm.map.m.s.a(PG:9675)
 28655             StrictMode  D  at com.google.b.a.cb.a(PG:125)
 28655             StrictMode  D  at com.google.android.apps.gmm.map.m.g.a(PG:1493)
 28655             StrictMode  D  at com.google.android.apps.gmm.base.app.d.a(PG:1179)
 28655             StrictMode  D  at com.google.android.apps.gmm.base.app.d.<init>(PG:624)
 28655             StrictMode  D  at com.google.android.apps.gmm.base.app.GoogleMapsApplication.a(PG:156)
 28655             StrictMode  D  at com.google.android.apps.gmm.base.app.GoogleMapsApplication.onCreate(PG:124)
 28655             StrictMode  D  at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1012)
 28655             StrictMode  D  at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4588)
 28655             StrictMode  D  at android.app.ActivityThread.access$1600(ActivityThread.java:154)
 28655             StrictMode  D  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1382)
 28655             StrictMode  D  at android.os.Handler.dispatchMessage(Handler.java:102)
 28655             StrictMode  D  at android.os.Looper.loop(Looper.java:135)
 28655             StrictMode  D  at android.app.ActivityThread.main(ActivityThread.java:5293)
 28655             StrictMode  D  at java.lang.reflect.Method.invoke(Native Method)
 28655             StrictMode  D  at java.lang.reflect.Method.invoke(Method.java:372)
 28655             StrictMode  D  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
 28655             StrictMode  D  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
 28655             StrictMode  D  StrictMode policy violation; ~duration=118 ms: android.os.StrictMode$StrictModeDiskReadViolation: policy=31 violation=2
 28655             StrictMode  D  at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1137)
 28655             StrictMode  D  at libcore.io.BlockGuardOs.access(BlockGuardOs.java:67)
 28655             StrictMode  D  at java.io.File.doAccess(File.java:283)
 28655             StrictMode  D  at java.io.File.exists(File.java:363)
 28655             StrictMode  D  at android.app.ContextImpl.createFilesDirLocked(ContextImpl.java:1035)
 28655             StrictMode  D  at android.app.ContextImpl.getFilesDir(ContextImpl.java:1058)
 28655             StrictMode  D  at android.app.ContextImpl.getFileStreamPath(ContextImpl.java:1166)
 28655             StrictMode  D  at android.content.ContextWrapper.getFileStreamPath(ContextWrapper.java:198)
 28655             StrictMode  D  at com.google.android.apps.gmm.map.m.s.a(PG:9683)
 28655             StrictMode  D  at com.google.b.a.cb.a(PG:125)
 28655             StrictMode  D  at com.google.android.apps.gmm.map.m.g.a(PG:1493)
 28655             StrictMode  D  at com.google.android.apps.gmm.base.app.d.a(PG:1179)
 28655             StrictMode  D  at com.google.android.apps.gmm.base.app.d.<init>(PG:624)
 28655             StrictMode  D  at com.google.android.apps.gmm.base.app.GoogleMapsApplication.a(PG:156)
 28655             StrictMode  D  at com.google.android.apps.gmm.base.app.GoogleMapsApplication.onCreate(PG:124)
 28655             StrictMode  D  at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1012)
 28655             StrictMode  D  at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4588)
 28655             StrictMode  D  at android.app.ActivityThread.access$1600(ActivityThread.java:154)
 28655             StrictMode  D  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1382)
 28655             StrictMode  D  at android.os.Handler.dispatchMessage(Handler.java:102)
 28655             StrictMode  D  at android.os.Looper.loop(Looper.java:135)
 28655             StrictMode  D  at android.app.ActivityThread.main(ActivityThread.java:5293)
 28655             StrictMode  D  at java.lang.reflect.Method.invoke(Native Method)
 28655             StrictMode  D  at java.lang.reflect.Method.invoke(Method.java:372)
 28655             StrictMode  D  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
 28655             StrictMode  D  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
 28655             StrictMode  D  StrictMode policy violation; ~duration=117 ms: android.os.StrictMode$StrictModeDiskReadViolation: policy=31 violation=2
 28655             StrictMode  D  at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1137)
 28655             StrictMode  D  at libcore.io.BlockGuardOs.access(BlockGuardOs.java:67)
 28655             StrictMode  D  at java.io.File.doAccess(File.java:283)
 28655             StrictMode  D  at java.io.File.exists(File.java:363)
 28655             StrictMode  D  at com.google.android.apps.gmm.map.m.s.a(PG:9685)
 28655             StrictMode  D  at com.google.b.a.cb.a(PG:125)
 28655             StrictMode  D  at com.google.android.apps.gmm.map.m.g.a(PG:1493)
 28655             StrictMode  D  at com.google.android.apps.gmm.base.app.d.a(PG:1179)
 28655             StrictMode  D  at com.google.android.apps.gmm.base.app.d.<init>(PG:624)
 28655             StrictMode  D  at com.google.android.apps.gmm.base.app.GoogleMapsApplication.a(PG:156)
 28655             StrictMode  D  at com.google.android.apps.gmm.base.app.GoogleMapsApplication.onCreate(PG:124)
 28655             StrictMode  D  at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1012)
 28655             StrictMode  D  at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4588)
 28655             StrictMode  D  at android.app.ActivityThread.access$1600(ActivityThread.java:154)
 28655             StrictMode  D  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1382)
 28655             StrictMode  D  at android.os.Handler.dispatchMessage(Handler.java:102)
 28655             StrictMode  D  at android.os.Looper.loop(Looper.java:135)
 28655             StrictMode  D  at android.app.ActivityThread.main(ActivityThread.java:5293)
 28655             StrictMode  D  at java.lang.reflect.Method.invoke(Native Method)
 28655             StrictMode  D  at java.lang.reflect.Method.invoke(Method.java:372)
 28655             StrictMode  D  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
 28655             StrictMode  D  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
 28655             StrictMode  D  StrictMode policy violation; ~duration=117 ms: android.os.StrictMode$StrictModeDiskReadViolation: policy=31 violation=2
 28655             StrictMode  D  at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1137)
 28655             StrictMode  D  at libcore.io.BlockGuardOs.stat(BlockGuardOs.java:292)
 28655             StrictMode  D  at java.io.File.lastModified(File.java:571)
 28655             StrictMode  D  at com.google.android.apps.gmm.map.m.s.a(PG:9686)
 28655             StrictMode  D  at com.google.b.a.cb.a(PG:125)
 28655             StrictMode  D  at com.google.android.apps.gmm.map.m.g.a(PG:1493)
 28655             StrictMode  D  at com.google.android.apps.gmm.base.app.d.a(PG:1179)
 28655             StrictMode  D  at com.google.android.apps.gmm.base.app.d.<init>(PG:624)
 28655             StrictMode  D  at com.google.android.apps.gmm.base.app.GoogleMapsApplication.a(PG:156)
 28655             StrictMode  D  at com.google.android.apps.gmm.base.app.GoogleMapsApplication.onCreate(PG:124)
 28655             StrictMode  D  at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1012)
 28655             StrictMode  D  at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4588)
 28655             StrictMode  D  at android.app.ActivityThread.access$1600(ActivityThread.java:154)
 28655             StrictMode  D  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1382)
 28655             StrictMode  D  at android.os.Handler.dispatchMessage(Handler.java:102)
 28655             StrictMode  D  at android.os.Looper.loop(Looper.java:135)
 28655             StrictMode  D  at android.app.ActivityThread.main(ActivityThread.java:5293)
 28655             StrictMode  D  at java.lang.reflect.Method.invoke(Native Method)
 28655             StrictMode  D  at java.lang.reflect.Method.invoke(Method.java:372)
 28655             StrictMode  D  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
 28655             StrictMode  D  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
  1864            GLSActivity  I  [ab] getting account id
  741         ActivityManager  I  Killing 27320:com.android.keychain/1000 (adj 15): empty #17
```

**Comment by Valodim** [comment]
openkeychain is killed, but are you sure this is an issue on our side?

```
28655             StrictMode  D  at com.google.android.apps.gmm.base.app.GoogleMapsApplication.onCreate(PG:124)
```

**Comment by dschuermann** [comment]
No not sure and second time it worked, but I'd like to investigate more.
