### ISSUE TITLE
java.lang.NoClassDefFoundError: android.support.v7.internal.view.menu.MenuBuilder

### ISSUE THREAD

**Issue by dschuermann** [open-keychain/open-keychain#1263]
Maybe this is a bug in the official support lib. Googling this stacktrace should lead to fixes. :)

From G Play
Android 4.2

```
java.lang.NoClassDefFoundError: android.support.v7.internal.view.menu.MenuBuilder
at android.support.v7.widget.ActionMenuView.getMenu(ActionMenuView.java:622)
at android.support.v7.widget.Toolbar.ensureMenu(Toolbar.java:828)
at android.support.v7.widget.Toolbar.getMenu(Toolbar.java:820)
at android.support.v7.internal.widget.ToolbarWidgetWrapper.getMenu(ToolbarWidgetWrapper.java:708)
at android.support.v7.internal.app.ToolbarActionBar.getMenu(ToolbarActionBar.java:569)
at android.support.v7.internal.app.ToolbarActionBar.populateOptionsMenu(ToolbarActionBar.java:442)
at android.support.v7.internal.app.ToolbarActionBar$1.run(ToolbarActionBar.java:66)
at android.os.Handler.handleCallback(Handler.java:800)
at android.os.Handler.dispatchMessage(Handler.java:100)
at android.os.Looper.loop(Looper.java:194)
at android.app.ActivityThread.main(ActivityThread.java:5391)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:525)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
at dalvik.system.NativeStart.main(Native Method)
```

**Comment by Valodim** [comment]
http://stackoverflow.com/questions/24809580/noclassdeffounderror-android-support-v7-internal-view-menu-menubuilder
