### ISSUE TITLE
ArrayIndexOutOfBoundsException in KeyFormattingUtils.convertFingerprintToHex

### ISSUE THREAD

**Issue by dschuermann** [open-keychain/open-keychain#1265]
From G Play

```
java.lang.RuntimeException: An error occured while executing doInBackground()
at android.support.v4.content.ModernAsyncTask$3.done(ModernAsyncTask.java:137)
at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:352)
at java.util.concurrent.FutureTask.setException(FutureTask.java:219)
at java.util.concurrent.FutureTask.run(FutureTask.java:239)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
at java.lang.Thread.run(Thread.java:841)
Caused by: org.spongycastle.util.encoders.EncoderException: exception encoding Hex string: length=16; index=16
at org.spongycastle.util.encoders.Hex.encode(Hex.java:60)
at org.spongycastle.util.encoders.Hex.toHexString(Hex.java:27)
at org.sufficientlysecure.keychain.ui.util.KeyFormattingUtils.convertFingerprintToHex(KeyFormattingUtils.java:219)
at org.sufficientlysecure.keychain.keyimport.ImportKeysListEntry.<init>(ImportKeysListEntry.java:300)
at org.sufficientlysecure.keychain.ui.adapter.ImportKeysListLoader.generateListOfKeyrings(ImportKeysListLoader.java:121)
at org.sufficientlysecure.keychain.ui.adapter.ImportKeysListLoader.loadInBackground(ImportKeysListLoader.java:70)
at org.sufficientlysecure.keychain.ui.adapter.ImportKeysListLoader.loadInBackground(ImportKeysListLoader.java:39)
at android.support.v4.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:242)
at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:51)
at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:40)
at android.support.v4.content.ModernAsyncTask$2.call(ModernAsyncTask.java:123)
at java.util.concurrent.FutureTask.run(FutureTask.java:234)
... 3 more
Caused by: java.lang.ArrayIndexOutOfBoundsException: length=16; index=16
at org.spongycastle.util.encoders.HexEncoder.encode(HexEncoder.java:62)
at org.spongycastle.util.encoders.Hex.encode(Hex.java:56)
... 14 more
```

**Comment by Valodim** [comment]
a 16 byte fingerprint?? how does that even happen :hurtrealbad:

**Comment by dschuermann** [comment]
Hmmm maybe YubiKey bug?

**Comment by Valodim** [comment]
the fingerprint is calculated from the public key packet in JcaKeyfingerprintCalculator.calculateFingerprint, which returns something like Sha1Digest.digest(), it seems extremely unlikely that this method would return something other than a 160 bits byte array.

but, the fingerprint is not obtained from a ui element or anything, it's from a key obtained from UncachedKeyring.fromStream, and other than some arraycopying, I see nothing inbetween. mh.

did this one occur often?

**Comment by Valodim** [comment]
derp. it's a md5 digest from a v3 key. this is done before any canonicalization, so v3 keys aren't weeded out yet

**Comment by Valodim** [comment]
@dschuermann please refer to the commits where you fixed stuff when you close issues

**Comment by Valodim** [comment]
fixed in e4b7920edcc04bed6524929b85ef1acb2c6a01d6, v3 fingerprints are formatted as 16 byte hexstrings. I don't quite like that solution, that routine shouldn't need to handle v3 keys.

is it necessary to parse keys as UncachedKeyRing before they are actually imported? if it's just for the fingerprint comparison that doesn't make much sense, but it makes error handling very messy and leads to problems like #1279 and #1149.

**Comment by dschuermann** [comment]
We need fingerprint handling to merge key entries from different sources, so yes we also need to handle v3 keys and I don't like new bigger back end changes for now. The small time we have, should go into fixing the bugs without rewriting everything.

**Comment by dschuermann** [comment]
Looking at it again: I am also not sure why we actually need to define a range. As far as I know you introduced it for YubiKeys, but not sure if that should be part of this function.

**Comment by Valodim** [comment]
hmmm, merging is a valid point I guess. still not really happy about this, there are probably more ways than this to create ioexceptions from bouncycastle (thinking algorithm incompatibilities), and those are not handled very gracefully at the moment and more difficult to test in ui code.

yes, the range was for yubikeys, it's not necessary in that place. although fp.length == 16  || fp.length == 20 should be asserted in the function.

**Comment by dschuermann** [comment]
Not sure what that has to do with algorithm incompatibilities. Algorithm incompatibilities don't crash OpenKeychain, the key is shown in import but after clicking the import button the log shows that there is something wrong. So we handle them more or less okay for now. It would be nice to have a better log message but that needs some work in Bouncy Castle (but should be easy).

**Comment by dschuermann** [comment]
Handling changed here: https://github.com/open-keychain/open-keychain/commit/0456e04c1a74285dcc5ca801d0d9afa61fff5469
