### ISSUE TITLE
import fails with eddsa signature packet

### ISSUE THREAD

**Issue by wxl** [open-keychain/open-keychain#1279]
STEPS TO REPRODUCE
----------------------------------
Attempt to add [key 0x1e0a4cce87ea6776][] from the cloud.

EXPECTED RESULTS
----------------------------------
Import succeeds.

ACTUAL RESULTS
----------------------------------
Log reports `[ERROR]Import operation failed!`

AFFECTS
----------------------------------
 * OpenKeychain 3.2.1 (32100), supposedly on Beta
 * Android 5.0
 * Samsung Galaxy S5

[key 0x1e0a4cce87ea6776]: http://keyserver.ubuntu.com/pks/lookup?op=get&search=0x1E0A4CCE87EA6776

**Comment by Valodim** [comment]
```
 10258               Keychain  E  IOException on parsing key file! Return NoValidKeysException!
 10258               Keychain  E  java.io.IOException: unknown signature key algorithm: 22
 10258               Keychain  E  at org.spongycastle.bcpg.SignaturePacket.<init>(SignaturePacket.java:179)
 10258               Keychain  E  at org.spongycastle.bcpg.BCPGInputStream.readPacket(BCPGInputStream.java:232)
 10258               Keychain  E  at org.spongycastle.openpgp.PGPKeyRing.readSignaturesAndTrust(PGPKeyRing.java:53)
 10258               Keychain  E  at org.spongycastle.openpgp.PGPKeyRing.readUserIDs(PGPKeyRing.java:91)
 10258               Keychain  E  at org.spongycastle.openpgp.PGPPublicKeyRing.<init>(PGPPublicKeyRing.java:73)
 10258               Keychain  E  at org.spongycastle.openpgp.PGPObjectFactory.nextObject(PGPObjectFactory.java:131)
 10258               Keychain  E  at org.sufficientlysecure.keychain.pgp.UncachedKeyRing$2.cacheNext(UncachedKeyRing.java:180)
 10258               Keychain  E  at org.sufficientlysecure.keychain.pgp.UncachedKeyRing$2.hasNext(UncachedKeyRing.java:201)
 10258               Keychain  E  at org.sufficientlysecure.keychain.ui.adapter.ImportKeysListLoader.generateListOfKeyrings(ImportKeysListLoader.java:119)
 10258               Keychain  E  at org.sufficientlysecure.keychain.ui.adapter.ImportKeysListLoader.loadInBackground(ImportKeysListLoader.java:70)
 10258               Keychain  E  at org.sufficientlysecure.keychain.ui.adapter.ImportKeysListLoader.loadInBackground(ImportKeysListLoader.java:39)
 10258               Keychain  E  at android.support.v4.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:242)
 10258               Keychain  E  at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:51)
 10258               Keychain  E  at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:40)
 10258               Keychain  E  at android.support.v4.content.ModernAsyncTask$2.call(ModernAsyncTask.java:123)
 10258               Keychain  E  at java.util.concurrent.FutureTask.run(FutureTask.java:237)
 10258               Keychain  E  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
 10258               Keychain  E  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
 10258               Keychain  E  at java.lang.Thread.run(Thread.java:818)
```

it's an eddsa key, so this is related to #1149. see #1265 for further notes.

**Comment by Valodim** [comment]
the more serious issue here is that adding an eddsa-signature will make import fail on our end for any key, which leads to trivial denial of service on arbitrary keys

**Comment by Valodim** [comment]
@iseki-masaya how's progress on this?

**Comment by iseki-masaya** [comment]
I found the reason of the failure.

SignaturePacket class in BouncyCastle at line 167
```java
keyAlgorithm >= PublicKeyAlgorithmTags.EXPERIMENTAL_1 && keyAlgorithm <= PublicKeyAlgorithmTags.EXPERIMENTAL_11
```
This conditional expression returns false since keyAlgorithm = 22, EXPERIMENTAL_1 = 100, and EXPERIMENTAL_11 = 110 when import this key.

The naive solution is to replace the value of EXPERIMENTAL_1 with 22.

Is there any problem in this solution?

**Comment by Valodim** [comment]
yes, because only 100 to 110 is the experimental range defined in rfc4880. eddsa compatibility should be a specific case

**Comment by iseki-masaya** [comment]
I try to build spongycastle, however I can't it.
Could you please tell me the way to build spongycastle independently.

My branch is 2c744eb.

Build error is following:
```
$ gradle build --info
Starting Build
Settings evaluated using settings file '/spongycastle/settings.gradle'.
Projects loaded. Root project using build file '/spongycastle/build.gradle'.
Included projects: [root project 'spongycastle', project ':core', project ':pg', project ':pkix', project ':prov']
Evaluating root project 'spongycastle' using build file /spongycastle/build.gradle'.
Evaluating project ':core' using build file '/spongycastle/core/build.gradle'.
Evaluating project ':pg' using build file '/spongycastle/pg/build.gradle'.

FAILURE: Build failed with an exception.

* Where:
Build file '/spongycastle/pg/build.gradle' line: 5

* What went wrong:
A problem occurred evaluating project ':pg'.
> Project with path ':extern:spongycastle:core' could not be found in project ':pg'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output.

BUILD FAILED

Total time: 4.847 secs
Stopped 0 compiler daemon(s).
```

My gradle version is following:

```
$ gradle -v
------------------------------------------------------------
Gradle 2.3
------------------------------------------------------------

Build time:   2015-02-16 05:09:33 UTC
Build number: none
Revision:     586be72bf6e3df1ee7676d1f2a3afd9157341274

Groovy:       2.3.9
Ant:          Apache Ant(TM) version 1.9.3 compiled on December 23 2013
JVM:          1.7.0_71 (Oracle Corporation 24.71-b01)
OS:           Mac OS X 10.10.3 x86_64
```

**Comment by iseki-masaya** [comment]
I make pull-request.
Please take a look.

https://github.com/open-keychain/spongycastle/pull/2.

**Comment by iseki-masaya** [comment]
@Valodim 

Do you know where the definition of key format of EdDSA ?

I'd like to implement SignaturePacket to derive EdDSA key correctly. (The above PR just avoid the exception error.)

I have searched the way to import the key in GnuPG and I found that GnuPG uses the same procedure to derive the key. However, I can not find the definition of the format of the EdDSA key (I have thought it is defined [RFC](https://tools.ietf.org/html/rfc4880).)

I regard that the procedure is the same by following code in GnuPG.


gnupg-2.1.4/g10/keygen.c:1256~1259
```c
  if (algo == PUBKEY_ALGO_ECDSA
      || algo == PUBKEY_ALGO_EDDSA
      || algo == PUBKEY_ALGO_ECDH )
    err = ecckey_from_sexp (pk->pkey, s_key, algo);
```

gnupg-2.1.4/g10/build-packet.c:342~345
```c
      if (   (pk->pubkey_algo == PUBKEY_ALGO_ECDSA && (i == 0))
          || (pk->pubkey_algo == PUBKEY_ALGO_EDDSA && (i == 0))
          || (pk->pubkey_algo == PUBKEY_ALGO_ECDH  && (i == 0 || i == 2)))
        err = gpg_mpi_write_nohdr (a, pk->pkey[i]);
```
The number of keys is the same defined in gnupg-2.1.4/g10/misc.c like

**Comment by Valodim** [comment]
it was mentioned in the task description: http://tools.ietf.org/html/draft-koch-eddsa-for-openpgp-00

**Comment by Valodim** [comment]
this was fixed with https://github.com/open-keychain/spongycastle/pull/5, the key imports cleanly now
