### ISSUE TITLE
crash when restoring a passphrase

### ISSUE THREAD

**Issue by ptibubu** [open-keychain/open-keychain#1314]
Openkeychain version 3.2.2 crashes when setting a passphrase. Exemple:
1- generate a key.
2- delete the passphrase, then save
3- set a passphrase. OKC crashes on saving

**Comment by Valodim** [comment]
thanks for the report! was able to reproduce, and it seems we finally have a good lead on #1262

```
java.lang.AssertionError: Unhandled SecretKeyType (should not happen)
 at org.sufficientlysecure.keychain.ui.PassphraseDialogActivity$PassphraseDialogFragment.onCreateDialog(PassphraseDialogActivity.java:263)
 at android.support.v4.app.DialogFragment.getLayoutInflater(DialogFragment.java:308)
 at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:955)
 at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1138)
 at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:740)
 at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1501)
 at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:458)
 at android.os.Handler.handleCallback(Handler.java:739)
 at android.os.Handler.dispatchMessage(Handler.java:95)
 at android.os.Looper.loop(Looper.java:135)
 at android.app.ActivityThread.main(ActivityThread.java:5256)
 at java.lang.reflect.Method.invoke(Native Method)
 at java.lang.reflect.Method.invoke(Method.java:372)
 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:898)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:693)
```

**Comment by Valodim** [comment]
fixed this one by handling empty passphrases in PassphraseDialogActivity 3976eadf060a0f5f18a05587dc597f9e83466f84

this *might* #1262, will wait for crash reports (or lack thereof) from the next release
