### ISSUE TITLE
Keybase Search Crashing

### ISSUE THREAD

**Issue by adithyaphilip** [open-keychain/open-keychain#1361]
Keybase search always fails with:
```
06-24 07:45:28.509  19491-20002/org.sufficientlysecure.keychain.debug E/Keychain D﹕ keybase result parsing error
    com.textuality.keybase.lib.KeybaseException: JSON error in Keybase query
            at com.textuality.keybase.lib.Match.getBitStrength(Match.java:85)
            at org.sufficientlysecure.keychain.keyimport.KeybaseKeyserver.makeEntry(KeybaseKeyserver.java:79)
            at org.sufficientlysecure.keychain.keyimport.KeybaseKeyserver.search(KeybaseKeyserver.java:53)
            at org.sufficientlysecure.keychain.keyimport.KeybaseKeyserver.search(KeybaseKeyserver.java:32)
            at org.sufficientlysecure.keychain.keyimport.CloudSearch$1.run(CloudSearch.java:53)
            at java.lang.Thread.run(Thread.java:856)
     Caused by: org.json.JSONException: No value for nbits
            at org.json.JSONObject.get(JSONObject.java:354)
            at org.json.JSONObject.getInt(JSONObject.java:443)
            at com.textuality.keybase.lib.JWalk.getInt(JWalk.java:47)
            at com.textuality.keybase.lib.Match.getBitStrength(Match.java:83)
            at org.sufficientlysecure.keychain.keyimport.KeybaseKeyserver.makeEntry(KeybaseKeyserver.java:79)
            at org.sufficientlysecure.keychain.keyimport.KeybaseKeyserver.search(KeybaseKeyserver.java:53)
            at org.sufficientlysecure.keychain.keyimport.KeybaseKeyserver.search(KeybaseKeyserver.java:32)
            at org.sufficientlysecure.keychain.keyimport.CloudSearch$1.run(CloudSearch.java:53)
            at java.lang.Thread.run(Thread.java:856)
```

**Comment by dschuermann** [comment]
reported here: https://github.com/keybase/keybase-issues/issues/1661

**Comment by dschuermann** [comment]
done by https://github.com/keybase/keybase-issues/issues/1661
