### ISSUE TITLE
Nullpointer in DecryptActivity

### ISSUE THREAD

**Issue by dschuermann** [open-keychain/open-keychain#1384]
```
 AndroidRuntime  E  java.lang.RuntimeException: Unable to start activity ComponentInfo{org.sufficientlysecure.keychain.debug/org.sufficientlysecure.keychain.ui.DecryptActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.content.ClipData.getItemCount()' on a null object reference
  4476         AndroidRuntime  E  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2298)
  4476         AndroidRuntime  E  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2360)
  4476         AndroidRuntime  E  at android.app.ActivityThread.access$800(ActivityThread.java:144)
  4476         AndroidRuntime  E  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278)
  4476         AndroidRuntime  E  at android.os.Handler.dispatchMessage(Handler.java:102)
  4476         AndroidRuntime  E  at android.os.Looper.loop(Looper.java:135)
  4476         AndroidRuntime  E  at android.app.ActivityThread.main(ActivityThread.java:5221)
  4476         AndroidRuntime  E  at java.lang.reflect.Method.invoke(Native Method)
  4476         AndroidRuntime  E  at java.lang.reflect.Method.invoke(Method.java:372)
  4476         AndroidRuntime  E  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
  4476         AndroidRuntime  E  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
  4476         AndroidRuntime  E  Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.content.ClipData.getItemCount()' on a null object reference
  4476         AndroidRuntime  E  at org.sufficientlysecure.keychain.ui.DecryptActivity.handleActions(DecryptActivity.java:127)
  4476         AndroidRuntime  E  at org.sufficientlysecure.keychain.ui.DecryptActivity.onCreate(DecryptActivity.java:61)
  4476         AndroidRuntime  E  at android.app.Activity.performCreate(Activity.java:5933)
  4476         AndroidRuntime  E  at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105)
  4476         AndroidRuntime  E  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2251)
  4476         AndroidRuntime  E  ... 10 more
```

**Comment by Valodim** [comment]
fix in f1c0c3e00c7287cdc501cd9148461f4c1ef1d8ec, test (and fix again) in 473866baaf5c736de74cc8b95f8acc84631c1043
