### ISSUE TITLE
NullPointerException in DecryptListFragment

### ISSUE THREAD

**Issue by dschuermann** [open-keychain/open-keychain#1389]
Looks like this is the bug mentioned on the mailinglist.

Moto X (ghost)

```
java.lang.RuntimeException: An error occured while executing doInBackground()
at android.os.AsyncTask$3.done(AsyncTask.java:300)
at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
at java.util.concurrent.FutureTask.run(FutureTask.java:242)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
at java.lang.Thread.run(Thread.java:818)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.net.Uri.getHost()' on a null object reference
at android.os.Parcel.readException(Parcel.java:1555)
at android.os.Parcel.readException(Parcel.java:1502)
at android.content.pm.IPackageManager$Stub$Proxy.queryIntentActivities(IPackageManager.java:2734)
at android.app.ApplicationPackageManager.queryIntentActivitiesAsUser(ApplicationPackageManager.java:565)
at android.app.ApplicationPackageManager.queryIntentActivities(ApplicationPackageManager.java:557)
at org.sufficientlysecure.keychain.ui.DecryptListFragment$1.doInBackground(DecryptListFragment.java:315)
at org.sufficientlysecure.keychain.ui.DecryptListFragment$1.doInBackground(DecryptListFragment.java:289)
at android.os.AsyncTask$2.call(AsyncTask.java:288)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
... 4 more
```

**Comment by Valodim** [comment]
hmmm, this apparently comes from not setting a uri in the intent for querying the intent filter. the uri is trivially available though and it's not a security risk since we are only querying, might as well set it
