### ISSUE TITLE
Context.getPackageName() on a null object in uploadKey(CreateKeyFinalFragment.java:318)

### ISSUE THREAD

**Issue by Valodim** [open-keychain/open-keychain#1405]
```
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Context.getPackageName()' on a null object reference
at android.content.ComponentName.<init>(ComponentName.java:77)
at android.content.Intent.<init>(Intent.java:4286)
at org.sufficientlysecure.keychain.ui.CreateKeyFinalFragment.uploadKey(CreateKeyFinalFragment.java:318)
at org.sufficientlysecure.keychain.ui.CreateKeyFinalFragment.access$200(CreateKeyFinalFragment.java:57)
at org.sufficientlysecure.keychain.ui.CreateKeyFinalFragment$4.handleMessage(CreateKeyFinalFragment.java:240)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:135)
at android.app.ActivityThread.main(ActivityThread.java:5289)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
```

the uploadKey method looks highly suspicious all around :hurtrealbad:

**Comment by dschuermann** [comment]
What exactly do you mean with highly suspicious?

**Comment by dschuermann** [comment]
Cannot reproduce, thus moving away from milestone

**Comment by Valodim** [comment]
this one is very likely gone or at least completely different with the change to CryptoOperationHelper
