### ISSUE TITLE
NullPointerException: ParcelableProxy.getProxy()

### ISSUE THREAD

**Issue by dschuermann** [open-keychain/open-keychain#1412]
Attach YubiKey with existing key to import this key from a keyserver -> crash

```
  8072         AndroidRuntime  E  FATAL EXCEPTION: ModernAsyncTask #1
  8072         AndroidRuntime  E  Process: org.sufficientlysecure.keychain.debug, PID: 8072
  8072         AndroidRuntime  E  java.lang.RuntimeException: An error occured while executing doInBackground()
  8072         AndroidRuntime  E  at android.support.v4.content.ModernAsyncTask$3.done(ModernAsyncTask.java:137)
  8072         AndroidRuntime  E  at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
  8072         AndroidRuntime  E  at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
  8072         AndroidRuntime  E  at java.util.concurrent.FutureTask.run(FutureTask.java:242)
  8072         AndroidRuntime  E  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
  8072         AndroidRuntime  E  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
  8072         AndroidRuntime  E  at java.lang.Thread.run(Thread.java:818)
  8072         AndroidRuntime  E  Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.net.Proxy org.sufficientlysecure.keychain.util.ParcelableProxy.getProxy()' on a null object reference
  8072         AndroidRuntime  E  at org.sufficientlysecure.keychain.ui.adapter.ImportKeysListCloudLoader.queryServer(ImportKeysListCloudLoader.java:103)
  8072         AndroidRuntime  E  at org.sufficientlysecure.keychain.ui.adapter.ImportKeysListCloudLoader.loadInBackground(ImportKeysListCloudLoader.java:67)
  8072         AndroidRuntime  E  at org.sufficientlysecure.keychain.ui.adapter.ImportKeysListCloudLoader.loadInBackground(ImportKeysListCloudLoader.java:35)
  8072         AndroidRuntime  E  at android.support.v4.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:242)
  8072         AndroidRuntime  E  at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:51)
  8072         AndroidRuntime  E  at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:40)
  8072         AndroidRuntime  E  at android.support.v4.content.ModernAsyncTask$2.call(ModernAsyncTask.java:123)
  8072         AndroidRuntime  E  at java.util.concurrent.FutureTask.run(FutureTask.java:237)
  8072         AndroidRuntime  E  ... 3 more
```

**Comment by dschuermann** [comment]
@adithyaphilip Can you also look into this one. Even when you don't have a YubiKey, maybe you directly see what causes this.

**Comment by dschuermann** [comment]
Ah ok the same happens when you click on a website link to get a key via keyserver like: https://hkps.pool.sks-keyservers.net/pks/lookup?op=get&search=0x73EE2314F65FA92EC2390D3A718C070100012282

stack:
```
  9762         AndroidRuntime  E  FATAL EXCEPTION: ModernAsyncTask #5
  9762         AndroidRuntime  E  Process: org.sufficientlysecure.keychain.debug, PID: 9762
  9762         AndroidRuntime  E  java.lang.RuntimeException: An error occured while executing doInBackground()
  9762         AndroidRuntime  E  at android.support.v4.content.ModernAsyncTask$3.done(ModernAsyncTask.java:137)
  9762         AndroidRuntime  E  at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
  9762         AndroidRuntime  E  at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
  9762         AndroidRuntime  E  at java.util.concurrent.FutureTask.run(FutureTask.java:242)
  9762         AndroidRuntime  E  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
  9762         AndroidRuntime  E  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
  9762         AndroidRuntime  E  at java.lang.Thread.run(Thread.java:818)
  9762         AndroidRuntime  E  Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.net.Proxy org.sufficientlysecure.keychain.util.ParcelableProxy.getProxy()' on a null object reference
  9762         AndroidRuntime  E  at org.sufficientlysecure.keychain.ui.adapter.ImportKeysListCloudLoader.queryServer(ImportKeysListCloudLoader.java:103)
  9762         AndroidRuntime  E  at org.sufficientlysecure.keychain.ui.adapter.ImportKeysListCloudLoader.loadInBackground(ImportKeysListCloudLoader.java:67)
  9762         AndroidRuntime  E  at org.sufficientlysecure.keychain.ui.adapter.ImportKeysListCloudLoader.loadInBackground(ImportKeysListCloudLoader.java:35)
  9762         AndroidRuntime  E  at android.support.v4.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:242)
  9762         AndroidRuntime  E  at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:51)
  9762         AndroidRuntime  E  at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:40)
  9762         AndroidRuntime  E  at android.support.v4.content.ModernAsyncTask$2.call(ModernAsyncTask.java:123)
  9762         AndroidRuntime  E  at java.util.concurrent.FutureTask.run(FutureTask.java:237)
  9762         AndroidRuntime  E  ... 3 more
```

So I am assigning it to you @adithyaphilip . Could you make this higher prio, so we can get make a bugfix release 3.4.1 ?

**Comment by Valodim** [comment]
fixed in b1f5290dfab8991bf88a226578b1e6ca98bf408c

**Comment by dschuermann** [comment]
Please still look into this @adithyaphilip . the proxy should also be used in the described Casey.

**Comment by dschuermann** [comment]
Also got this from Google Play developer console with user message: Crash when attempting key lookup for SANS Newsbites

```
java.lang.RuntimeException: An error occured while executing doInBackground()
at android.support.v4.content.ModernAsyncTask$3.done(ModernAsyncTask.java:137)
at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
at java.util.concurrent.FutureTask.run(FutureTask.java:242)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
at java.lang.Thread.run(Thread.java:818)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.net.Proxy org.sufficientlysecure.keychain.util.ParcelableProxy.getProxy()' on a null object reference
at org.sufficientlysecure.keychain.ui.adapter.ImportKeysListCloudLoader.queryServer(ImportKeysListCloudLoader.java:103)
at org.sufficientlysecure.keychain.ui.adapter.ImportKeysListCloudLoader.loadInBackground(ImportKeysListCloudLoader.java:69)
at org.sufficientlysecure.keychain.ui.adapter.ImportKeysListCloudLoader.loadInBackground(ImportKeysListCloudLoader.java:35)
at android.support.v4.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:242)
at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:51)
at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:40)
at android.support.v4.content.ModernAsyncTask$2.call(ModernAsyncTask.java:123)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
... 3 more
```
