### ISSUE TITLE
NullPointerException in uploadKey (Preferences.updateSharedPreferences)

### ISSUE THREAD

**Issue by dschuermann** [open-keychain/open-keychain#1420]
From G Play

```
java.lang.NullPointerException
at org.sufficientlysecure.keychain.util.Preferences.updateSharedPreferences(Preferences.java:73)
at org.sufficientlysecure.keychain.util.Preferences.getPreferences(Preferences.java:56)
at org.sufficientlysecure.keychain.util.Preferences.getPreferences(Preferences.java:48)
at org.sufficientlysecure.keychain.ui.CreateKeyFinalFragment.uploadKey(CreateKeyFinalFragment.java:363)
at org.sufficientlysecure.keychain.ui.CreateKeyFinalFragment.access$200(CreateKeyFinalFragment.java:56)
at org.sufficientlysecure.keychain.ui.CreateKeyFinalFragment$4.onCryptoOperationSuccess(CreateKeyFinalFragment.java:244)
at org.sufficientlysecure.keychain.ui.CreateKeyFinalFragment$4.onCryptoOperationSuccess(CreateKeyFinalFragment.java:228)
at org.sufficientlysecure.keychain.ui.base.CryptoOperationHelper.onHandleResult(CryptoOperationHelper.java:335)
at org.sufficientlysecure.keychain.ui.base.CryptoOperationHelper$1.handleMessage(CryptoOperationHelper.java:283)
at android.os.Handler.dispatchMessage(Handler.java:107)
at android.os.Looper.loop(Looper.java:194)
at android.app.ActivityThread.main(ActivityThread.java:5455)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:525)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:966)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:733)
at dalvik.system.NativeStart.main(Native Method)
```

**Comment by Valodim** [comment]
this is one of the cases where getActivity() is used withot a null-check. I tried something in c8107bd4ed9962861bf5448731e87f667ab166e0, I wonder if we can find a universal solution to this problem...

**Comment by Valodim** [comment]
this should be fixed in the commit mentioned above, and the generic solution might help in other places. really curious how that will pan out in our crash reports for the next version
