### ISSUE TITLE
crash on subkey-add if primary key is divert-to-card

### ISSUE THREAD

**Issue by Valodim** [open-keychain/open-keychain#1422]
```
java.lang.NullPointerException: Attempt to invoke virtual method 'char[] org.sufficientlysecure.keychain.util.Passphrase.getCharArray()' on a null object reference
at org.sufficientlysecure.keychain.pgp.PgpKeyOperation.internal(PgpKeyOperation.java:1001)
at org.sufficientlysecure.keychain.pgp.PgpKeyOperation.modifySecretKeyRing(PgpKeyOperation.java:482)
at org.sufficientlysecure.keychain.operations.EditKeyOperation.execute(EditKeyOperation.java:87)
at org.sufficientlysecure.keychain.operations.EditKeyOperation.execute(EditKeyOperation.java:54)
at org.sufficientlysecure.keychain.service.KeychainService$1.run(KeychainService.java:142)
at java.lang.Thread.run(Thread.java:818)
```

newly created subkeys use the same passphrase as the primary key. yubikeys don't have a passphrase, leading to a nullpointer crash. there are also a couple of other special scenarios regarding subkey editing which are icky for divert-to-card keys at the moment

**Comment by Valodim** [comment]
creating new subkeys for yubikey primary keys is not supported, added an error case for this d9b07625e8b492d2d3b0ee5b0c898c3315b31439

also improved handling of divert-to-card subkeys. it's sort of an absurd scenario, but stuff like "change expiry for a divert-to-card subkey with signing capability (which is not the primary key)" works now 642f83c1f4a69e513334321f7f5810bdfc7f1ad2
