### ISSUE TITLE
Decrypt example from Intent library crashes OpenKeychain

### ISSUE THREAD

**Issue by dschuermann** [open-keychain/open-keychain#1426]
Decrypt example from Intent library crashes OpenKeychain

**Comment by Valodim** [comment]
any stack trace?

**Comment by dschuermann** [comment]
```
  469          AndroidRuntime  E  FATAL EXCEPTION: Thread-25569
  469          AndroidRuntime  E  Process: org.sufficientlysecure.keychain.debug, PID: 469
  469          AndroidRuntime  E  java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.net.Uri.getScheme()' on a null object reference
  469          AndroidRuntime  E  at android.content.ContentResolver.openInputStream(ContentResolver.java:630)
  469          AndroidRuntime  E  at org.sufficientlysecure.keychain.pgp.PgpDecryptVerify.execute(PgpDecryptVerify.java:98)
  469          AndroidRuntime  E  at org.sufficientlysecure.keychain.pgp.PgpDecryptVerify.execute(PgpDecryptVerify.java:81)
  469          AndroidRuntime  E  at org.sufficientlysecure.keychain.service.KeychainService$1.run(KeychainService.java:142)
  469          AndroidRuntime  E  at java.lang.Thread.run(Thread.java:818)

```
