### ISSUE TITLE
ClassCastException in PgpDecryptVerify.verifyCleartextSignature

### ISSUE THREAD

**Issue by dschuermann** [open-keychain/open-keychain#1442]
From Google Play.

That's a crazy one...

```
java.lang.ClassCastException: org.spongycastle.openpgp.PGPLiteralData cannot be cast to org.spongycastle.openpgp.PGPSignatureList
at org.sufficientlysecure.keychain.pgp.PgpDecryptVerify.verifyCleartextSignature(PgpDecryptVerify.java:918)
at org.sufficientlysecure.keychain.pgp.PgpDecryptVerify.executeInternal(PgpDecryptVerify.java:159)
at org.sufficientlysecure.keychain.pgp.PgpDecryptVerify.execute(PgpDecryptVerify.java:122)
at org.sufficientlysecure.keychain.pgp.PgpDecryptVerify.execute(PgpDecryptVerify.java:81)
at org.sufficientlysecure.keychain.service.KeychainService$1.run(KeychainService.java:142)
at java.lang.Thread.run(Thread.java:818)
```

**Comment by Valodim** [comment]
nah it's not, we just don't deal particularly well with unexpected/malformed pgp packet structures. this happens when there is a literaldata (11) packet where we expect a signature (2) one.

**Comment by dschuermann** [comment]
Yeah, I just wasn't expecting that someone generates a cleartext signature with literal data :grimacing:
