### ISSUE TITLE
Crash on refresh key that is now revoked

### ISSUE THREAD

**Issue by dschuermann** [open-keychain/open-keychain#1447]
1. backup db
2. revoke one of your keys and upload it to keyservers
3. restore db
4. Go to view of this key and click on refresh.
5. OK crashes. Looks like it has something to do with the cursor of the user ids.

```
 24548         AndroidRuntime  D  Shutting down VM
 24548         AndroidRuntime  E  FATAL EXCEPTION: main
 24548         AndroidRuntime  E  Process: org.sufficientlysecure.keychain.debug, PID: 24548
 24548         AndroidRuntime  E  android.database.StaleDataException: Attempting to access a closed CursorWindow.Most probable cause: cursor is deactivated prior to calling this method.
 24548         AndroidRuntime  E  at android.database.AbstractWindowedCursor.checkPosition(AbstractWindowedCursor.java:139)
 24548         AndroidRuntime  E  at android.database.AbstractWindowedCursor.getString(AbstractWindowedCursor.java:50)
 24548         AndroidRuntime  E  at android.database.CursorWrapper.getString(CursorWrapper.java:114)
 24548         AndroidRuntime  E  at org.sufficientlysecure.keychain.ui.adapter.UserIdsAdapter.bindView(UserIdsAdapter.java:74)
 24548         AndroidRuntime  E  at android.support.v4.widget.CursorAdapter.getView(CursorAdapter.java:256)
 24548         AndroidRuntime  E  at android.widget.AbsListView.obtainView(AbsListView.java:2349)
 24548         AndroidRuntime  E  at android.widget.ListView.measureHeightOfChildren(ListView.java:1270)
 24548         AndroidRuntime  E  at android.widget.ListView.onMeasure(ListView.java:1182)
 24548         AndroidRuntime  E  at org.sufficientlysecure.keychain.ui.widget.FixedListView.onMeasure(FixedListView.java:50)
 24548         AndroidRuntime  E  at android.view.View.measure(View.java:17554)
 24548         AndroidRuntime  E  at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5536)
 24548         AndroidRuntime  E  at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1436)
 24548         AndroidRuntime  E  at android.widget.LinearLayout.measureVertical(LinearLayout.java:722)
 24548         AndroidRuntime  E  at android.widget.LinearLayout.onMeasure(LinearLayout.java:613)
 24548         AndroidRuntime  E  at android.view.View.measure(View.java:17554)
 24548         AndroidRuntime  E  at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5536)
 24548         AndroidRuntime  E  at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
 24548         AndroidRuntime  E  at android.support.v7.widget.CardView.onMeasure(CardView.java:198)
 24548         AndroidRuntime  E  at android.view.View.measure(View.java:17554)
 24548         AndroidRuntime  E  at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5536)
 24548         AndroidRuntime  E  at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1436)
 24548         AndroidRuntime  E  at android.widget.LinearLayout.measureVertical(LinearLayout.java:722)
 24548         AndroidRuntime  E  at android.widget.LinearLayout.onMeasure(LinearLayout.java:613)
 24548         AndroidRuntime  E  at android.view.View.measure(View.java:17554)
 24548         AndroidRuntime  E  at android.widget.ScrollView.measureChildWithMargins(ScrollView.java:1260)
 24548         AndroidRuntime  E  at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
 24548         AndroidRuntime  E  at android.widget.ScrollView.onMeasure(ScrollView.java:337)
 24548         AndroidRuntime  E  at android.view.View.measure(View.java:17554)
 24548         AndroidRuntime  E  at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5536)
 24548         AndroidRuntime  E  at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
 24548         AndroidRuntime  E  at android.view.View.measure(View.java:17554)
 24548         AndroidRuntime  E  at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5536)
 24548         AndroidRuntime  E  at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
 24548         AndroidRuntime  E  at android.view.View.measure(View.java:17554)
 24548         AndroidRuntime  E  at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5536)
 24548         AndroidRuntime  E  at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
 24548         AndroidRuntime  E  at android.view.View.measure(View.java:17554)
 24548         AndroidRuntime  E  at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5536)
 24548         AndroidRuntime  E  at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
 24548         AndroidRuntime  E  at android.view.View.measure(View.java:17554)
 24548         AndroidRuntime  E  at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5536)
 24548         AndroidRuntime  E  at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1436)
 24548         AndroidRuntime  E  at android.widget.LinearLayout.measureVertical(LinearLayout.java:722)
 24548         AndroidRuntime  E  at android.widget.LinearLayout.onMeasure(LinearLayout.java:613)
 24548         AndroidRuntime  E  at android.view.View.measure(View.java:17554)
 24548         AndroidRuntime  E  at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:728)
 24548         AndroidRuntime  E  at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:464)
 24548         AndroidRuntime  E  at android.view.View.measure(View.java:17554)
 24548         AndroidRuntime  E  at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5536)
 24548         AndroidRuntime  E  at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
 24548         AndroidRuntime  E  at android.support.v7.internal.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:124)
 24548         AndroidRuntime  E  at android.view.View.measure(View.java:17554)
 24548         AndroidRuntime  E  at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5536)
 24548         AndroidRuntime  E  at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
 24548         AndroidRuntime  E  at android.view.View.measure(View.java:17554)
 24548         AndroidRuntime  E  at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5536)
 24548         AndroidRuntime  E  at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
 24548         AndroidRuntime  E  at android.view.View.measure(View.java:17554)
  743         ActivityManager  W  Force finishing activity 1 org.sufficientlysecure.keychain.debug/org.sufficientlysecure.keychain.ui.ViewKeyActivity
```

**Comment by Valodim** [comment]
A key which I revoked now simply vanishes

```
 25003             Keychain D  E  A key could not be imported during multi-threaded import
 25003             Keychain D  E  java.util.concurrent.ExecutionException: java.lang.AssertionError: Rank 0 user packet must be a user id!
 25003             Keychain D  E  at java.util.concurrent.FutureTask.report(FutureTask.java:93)
 25003             Keychain D  E  at java.util.concurrent.FutureTask.get(FutureTask.java:163)
 25003             Keychain D  E  at org.sufficientlysecure.keychain.operations.ImportOperation.multiThreadedKeyImport(ImportOperation.java:461)
 25003             Keychain D  E  at org.sufficientlysecure.keychain.operations.ImportOperation.execute(ImportOperation.java:413)
 25003             Keychain D  E  at org.sufficientlysecure.keychain.operations.ImportOperation.execute(ImportOperation.java:83)
 25003             Keychain D  E  at org.sufficientlysecure.keychain.service.KeychainService$1.run(KeychainService.java:145)
 25003             Keychain D  E  at java.lang.Thread.run(Thread.java:818)
 25003             Keychain D  E  Caused by: java.lang.AssertionError: Rank 0 user packet must be a user id!
 25003             Keychain D  E  at org.sufficientlysecure.keychain.provider.KeychainProvider.insert(KeychainProvider.java:771)
 25003             Keychain D  E  at android.content.ContentProviderOperation.apply(ContentProviderOperation.java:245)
 25003             Keychain D  E  at android.content.ContentProvider.applyBatch(ContentProvider.java:1756)
 25003             Keychain D  E  at android.content.ContentProvider$Transport.applyBatch(ContentProvider.java:297)
 25003             Keychain D  E  at android.content.ContentProviderClient.applyBatch(ContentProviderClient.java:377)
 25003             Keychain D  E  at android.content.ContentResolver.applyBatch(ContentResolver.java:1244)
 25003             Keychain D  E  at org.sufficientlysecure.keychain.provider.ProviderHelper.saveCanonicalizedPublicKeyRing(ProviderHelper.java:734)
 25003             Keychain D  E  at org.sufficientlysecure.keychain.provider.ProviderHelper.savePublicKeyRing(ProviderHelper.java:963)
 25003             Keychain D  E  at org.sufficientlysecure.keychain.operations.ImportOperation.serialKeyRingImport(ImportOperation.java:284)
 25003             Keychain D  E  at org.sufficientlysecure.keychain.operations.ImportOperation.access$000(ImportOperation.java:83)
 25003             Keychain D  E  at org.sufficientlysecure.keychain.operations.ImportOperation$1.call(ImportOperation.java:451)
 25003             Keychain D  E  at org.sufficientlysecure.keychain.operations.ImportOperation$1.call(ImportOperation.java:443)
 25003             Keychain D  E  at java.util.concurrent.FutureTask.run(FutureTask.java:237)
 25003             Keychain D  E  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
 25003             Keychain D  E  at java.util.concurrent.FutureTask.run(FutureTask.java:237)
 25003             Keychain D  E  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
 25003             Keychain D  E  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
```

(ping @adithyaphilip)

**Comment by Valodim** [comment]
ok that one looks like an error in my code related to userattributes, I'll fix this
