### ISSUE TITLE
nfc sharing is broken

### ISSUE THREAD

**Issue by Valodim** [open-keychain/open-keychain#1452]
sharing keys via nfc does not work currently while OpenKeychain is open, because we enable nfcForegroundDispatch in most of our activities.

```
FATAL EXCEPTION: AsyncTask #1
Process: org.sufficientlysecure.keychain.debug, PID: 26021
java.lang.RuntimeException: An error occured while executing doInBackground()
at android.os.AsyncTask$3.done(AsyncTask.java:304)
at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
at java.util.concurrent.FutureTask.run(FutureTask.java:242)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
at java.lang.Thread.run(Thread.java:818)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.nfc.tech.IsoDep.setTimeout(int)' on

at org.sufficientlysecure.keychain.ui.base.BaseNfcActivity.handleTagDiscoveredIntent(BaseNfcActivity.java:407)
at org.sufficientlysecure.keychain.ui.base.BaseNfcActivity$1.doInBackground(BaseNfcActivity.java:147)
at org.sufficientlysecure.keychain.ui.base.BaseNfcActivity$1.doInBackground(BaseNfcActivity.java:137)
at android.os.AsyncTask$2.call(AsyncTask.java:292)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
... 4 more
Force finishing activity 1 org.sufficientlysecure.keychain.debug/org.sufficientlysecure.keychain.ui.MainActivity
```

**Comment by dschuermann** [comment]
For later: https://github.com/kylelampert/Tapped/blob/master/Tapped-Full-Demo/src/com/enavigo/tapped/activities/HomeActivity.java#L399
