### ISSUE TITLE
App crashes when select backup key on my own key.

### ISSUE THREAD

**Issue by yeoncomi** [open-keychain/open-keychain#1466]
App keep crashes when I select backup keys on my own key, then when I insert password App crashes.

**Comment by Valodim** [comment]
Is your key in any way special, i.e. yubikey or ECC subkeys or something like that?

if you have the app installed from the playstore, it would also be great if you could send a crash report, including a comment of where it happened. crash reports contain technical data which is very useful for us to track down problems.

**Comment by Valodim** [comment]
oh actually I just found one which might be related:

```
java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=2, result=-1, data=Intent { (has extras) }} to activity {org.sufficientlysecure.keychain/org.sufficientlysecure.keychain.ui.ViewKeyActivity}: java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
at android.app.ActivityThread.deliverResults(ActivityThread.java:3153)
at android.app.ActivityThread.handleSendResult(ActivityThread.java:3196)
at android.app.ActivityThread.access$1100(ActivityThread.java:138)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1251)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:137)
at android.app.ActivityThread.main(ActivityThread.java:4822)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:556)
at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
at android.support.v4.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:1377)
at android.support.v4.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1395)
at android.support.v4.app.BackStackRecord.commitInternal(BackStackRecord.java:637)
at android.support.v4.app.BackStackRecord.commit(BackStackRecord.java:616)
at android.support.v4.app.DialogFragment.show(DialogFragment.java:139)
at org.sufficientlysecure.keychain.util.FileHelper$2.run(FileHelper.java:121)
at org.sufficientlysecure.keychain.compatibility.DialogFragmentWorkaround$SDKLevelPriorLevel17Impl.runnableRunDelayed(DialogFragmentWorkaround.java:54)
at org.sufficientlysecure.keychain.util.FileHelper.saveFile(FileHelper.java:115)
at org.sufficientlysecure.keychain.util.ExportHelper.showExportKeysDialog(ExportHelper.java:70)
at org.sufficientlysecure.keychain.ui.ViewKeyActivity.backupToFile(ViewKeyActivity.java:417)
at org.sufficientlysecure.keychain.ui.ViewKeyActivity.onActivityResult(ViewKeyActivity.java:479)
at android.app.Activity.dispatchActivityResult(Activity.java:5192)
at android.app.ActivityThread.deliverResults(ActivityThread.java:3149)
```

**Comment by yeoncomi** [comment]
My keys weren't any special or something. I did sent crash report .Hope you could find the bug. Bye

**Comment by dschuermann** [comment]
@yeoncomi Can you try again with version 3.6? Has this been fixed?

**Comment by yeoncomi** [comment]
@dschuermann Phone that stored my private key dead.
Sorry
