### ISSUE TITLE
App crashes when click "skip setup"

### ISSUE THREAD

**Issue by YodaTheMagistr** [open-keychain/open-keychain#1470]
App crashes when click "skip setup" or "configure key". If i click "skip setup", app will never run again (only after reinstall).
App builded from source (latest). Build without errors. What kind of information i need to provide? 
 
Error log
'''
08-05 19:02:19.289  13241-13241/org.sufficientlysecure.keychain.debug E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: org.sufficientlysecure.keychain.debug, PID: 13241
    java.lang.RuntimeException: Unable to start activity ComponentInfo{org.sufficientlysecure.keychain.debug/org.sufficientlysecure.keychain.ui.EditKeyActivity}: android.view.InflateException: Binary XML file line #12: Error inflating class TextView
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2192)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2241)
            at android.app.ActivityThread.access$800(ActivityThread.java:141)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1204)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5049)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: android.view.InflateException: Binary XML file line #12: Error inflating class TextView
            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:716)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:761)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:495)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:400)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
            at org.sufficientlysecure.keychain.ui.EditKeyFragment.onCreateView(EditKeyFragment.java:131)
            at android.support.v4.app.Fragment.performCreateView(Fragment.java:1789)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:955)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1138)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1120)
            at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:1929)
            at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:547)
            at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1171)
            at android.app.Activity.performStart(Activity.java:5259)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2165)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2241)
            at android.app.ActivityThread.access$800(ActivityThread.java:141)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1204)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5049)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: android.content.res.Resources$NotFoundException: File res/drawable/section_header.xml from drawable resource ID #0x7f0200b1
            at android.content.res.Resources.loadDrawable(Resources.java:2149)
            at android.content.res.MiuiResources.loadDrawable(MiuiResources.java:348)
            at android.content.res.Resources.loadDrawable(Resources.java:2072)
            at android.content.res.TypedArray.getDrawable(TypedArray.java:602)
            at android.widget.TextView.<init>(TextView.java:818)
            at android.support.v7.widget.AppCompatTextView.<init>(AppCompatTextView.java:44)
            at android.support.v7.widget.AppCompatTextView.<init>(AppCompatTextView.java:40)
            at android.support.v7.internal.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:103)
            at android.support.v7.app.AppCompatDelegateImplV7.createView(AppCompatDelegateImplV7.java:802)
            at android.support.v7.app.AppCompatDelegateImplV7.onCreateView(AppCompatDelegateImplV7.java:832)
            at android.support.v4.view.LayoutInflaterCompatHC$FactoryWrapperHC.onCreateView(LayoutInflaterCompatHC.java:44)
            at android.view.LayoutInflater$FactoryMerger.onCreateView(LayoutInflater.java:172)
            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:687)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:761)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:495)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:400)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
            at org.sufficientlysecure.keychain.ui.EditKeyFragment.onCreateView(EditKeyFragment.java:131)
            at android.support.v4.app.Fragment.performCreateView(Fragment.java:1789)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:955)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1138)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1120)
            at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:1929)
            at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:547)
            at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1171)
            at android.app.Activity.performStart(Activity.java:5259)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2165)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2241)
            at android.app.ActivityThread.access$800(ActivityThread.java:141)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1204)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5049)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.UnsupportedOperationException: Can't convert to color: type=0x2
            at android.content.res.TypedArray.getColor(TypedArray.java:327)
            at android.graphics.drawable.GradientDrawable.inflate(GradientDrawable.java:970)
            at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:939)
            at android.graphics.drawable.Drawable.createFromXml(Drawable.java:879)
            at android.content.res.Resources.crea
'''
Thank you.

**Comment by dschuermann** [comment]
Have you tried "./gradlew clean" and then again "./gradlew build" ? Looks like a wrongly packaged apk.

**Comment by adithyaphilip** [comment]
Was crashing on the Kindle (API 15) too. Looks like API < 21 can't have drawables refer to attrs: http://stackoverflow.com/questions/8041537/how-to-reference-style-attributes-from-a-drawable/13471695#13471695. I've used the workarorund there to fix it for now: https://github.com/open-keychain/open-keychain/pull/1474

**Comment by dschuermann** [comment]
@YodaTheMagistr Fixed in master thanks to @adithyaphilip
