### ISSUE TITLE
Crash on "update all": RuntimeException in ImportOperation.java:483

### ISSUE THREAD

**Issue by dschuermann** [open-keychain/open-keychain#1480]
OpenKeychain from git master crashes when I hit "update all"

Assigned to @adithyaphilip 

I got the following log, looks like a key is not on the keyserver:

```
[remved, see comment]
```

**Comment by dschuermann** [comment]
Ah sry this wasn't the right log. This is the right one:
```
 13107             Keychain D  V  query(uri=content://org.sufficientlysecure.keychain.debug.provider/key_rings/-4266035947009897926/unified, proj=[has_any_secret, verified, privkey_data])
 13107             Keychain D  V  query(uri=content://org.sufficientlysecure.keychain.debug.provider/key_rings/unified, proj=[_id, master_key_id, user_id, is_revoked, is_expired, verified, has_any_secret, has_duplicate_user_id, fingerprint, creation])
 13107             Keychain D  D  insert(uri=content://org.sufficientlysecure.keychain.debug.provider/key_rings/4165106460550059802/keys, values=can_certify=false is_revoked=false can_authenticate=false master_key_id=4165106460550059802 fingerprint=[B@11c0b71b rank=1 can_sign=false key_curve_oid=null expiry=1451624722 can_encrypt=true key_id=-7185159641852011494 key_size=4096 algorithm=1 creation=1314575929)
 13107             Keychain D  D  Found class: class org.spongycastle.openpgp.PGPPublicKeyRing
 13107             Keychain D  V  log: LogEntryParcel{mLevel=DEBUG, mType=MSG_IMPORT_FETCH_KEYSERVER_OK, mParameters=null, mIndent=3}
 13107             Keychain D  V  log: LogEntryParcel{mLevel=DEBUG, mType=MSG_IMPORT_FINGERPRINT_OK, mParameters=null, mIndent=2}
 13107             Keychain D  V  log: LogEntryParcel{mLevel=OK, mType=MSG_IP_SUCCESS, mParameters=null, mIndent=5}
 13107             Keychain D  V  log: LogEntryParcel{mLevel=START, mType=MSG_IP, mParameters=[0xb540b362b202db50], mIndent=5}
 13107             Keychain D  V  query(uri=content://org.sufficientlysecure.keychain.debug.provider/key_rings/-5386107917860414640/unified, proj=[has_any_secret, verified, pubkey_data])
 13107             Keychain D  V  log: LogEntryParcel{mLevel=DEBUG, mType=MSG_IP_PREPARE, mParameters=null, mIndent=5}
 13107             Keychain D  V  log: LogEntryParcel{mLevel=DEBUG, mType=MSG_IP_INSERT_KEYRING, mParameters=null, mIndent=6}
 13107             Keychain D  E  A key could not be imported during multi-threaded import
 13107             Keychain D  E  java.util.concurrent.ExecutionException: java.lang.NullPointerException: Attempt to read from field 'org.sufficientlysecure.keychain.operations.results.OperationResult$LogType org.sufficientlysecure.keychain.operations.results.OperationResult$LogEntryParcel.mType' on a null object reference
 13107             Keychain D  E  at java.util.concurrent.FutureTask.report(FutureTask.java:93)
 13107             Keychain D  E  at java.util.concurrent.FutureTask.get(FutureTask.java:163)
 13107             Keychain D  E  at org.sufficientlysecure.keychain.operations.ImportOperation.multiThreadedKeyImport(ImportOperation.java:474)
 13107             Keychain D  E  at org.sufficientlysecure.keychain.operations.ImportOperation.execute(ImportOperation.java:423)
 13107             Keychain D  E  at org.sufficientlysecure.keychain.operations.ImportOperation.execute(ImportOperation.java:84)
 13107             Keychain D  E  at org.sufficientlysecure.keychain.service.KeychainService$1.run(KeychainService.java:145)
 13107             Keychain D  E  at java.lang.Thread.run(Thread.java:818)
 13107             Keychain D  E  Caused by: java.lang.NullPointerException: Attempt to read from field 'org.sufficientlysecure.keychain.operations.results.OperationResult$LogType org.sufficientlysecure.keychain.operations.results.OperationResult$LogEntryParcel.mType' on a null object reference
 13107             Keychain D  E  at org.sufficientlysecure.keychain.operations.results.OperationResult$OperationLog.add(OperationResult.java:841)
 13107             Keychain D  E  at org.sufficientlysecure.keychain.operations.ImportOperation.serialKeyRingImport(ImportOperation.java:319)
 13107             Keychain D  E  at org.sufficientlysecure.keychain.operations.ImportOperation.serialKeyRingImport(ImportOperation.java:118)
 13107             Keychain D  E  at org.sufficientlysecure.keychain.operations.ImportOperation$1.call(ImportOperation.java:465)
 13107             Keychain D  E  at org.sufficientlysecure.keychain.operations.ImportOperation$1.call(ImportOperation.java:457)
 13107             Keychain D  E  at java.util.concurrent.FutureTask.run(FutureTask.java:237)
 13107             Keychain D  E  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
 13107             Keychain D  E  at java.util.concurrent.FutureTask.run(FutureTask.java:237)
 13107             Keychain D  E  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
 13107             Keychain D  E  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
 13107             Keychain D  E  ... 1 more
 13107         AndroidRuntime  E  FATAL EXCEPTION: Thread-3938
 13107         AndroidRuntime  E  Process: org.sufficientlysecure.keychain.debug, PID: 13107
 13107         AndroidRuntime  E  java.lang.RuntimeException
 13107         AndroidRuntime  E  at org.sufficientlysecure.keychain.operations.ImportOperation.multiThreadedKeyImport(ImportOperation.java:483)
 13107         AndroidRuntime  E  at org.sufficientlysecure.keychain.operations.ImportOperation.execute(ImportOperation.java:423)
 13107         AndroidRuntime  E  at org.sufficientlysecure.keychain.operations.ImportOperation.execute(ImportOperation.java:84)
 13107         AndroidRuntime  E  at org.sufficientlysecure.keychain.service.KeychainService$1.run(KeychainService.java:145)
 13107         AndroidRuntime  E  at java.lang.Thread.run(Thread.java:818)

```

**Comment by dschuermann** [comment]
@adithyaphilip Can you prioritize this bug? Do you need more information?

**Comment by dschuermann** [comment]
It's the RuntimeException in ImportOperation.java:483

**Comment by Valodim** [comment]
that method is also annotated NonNull but contains a "return null;"

**Comment by adithyaphilip** [comment]
Turns out the issue was `mProviderHelper.clearLog()` being called in parallel before a return from `mProviderHelper.savePublicKeyring()`
