### ISSUE TITLE
Password Store: class not found exception for CryptoInputParcel

### ISSUE THREAD

**Issue by dschuermann** [open-keychain/open-keychain#1489]
Needs investigation. Related to OpenPgpDecryptionResult?

From mailinglist:
```
Looks like the latest update broke Password Store ( using yubikey neo ). Is
that to be expected? Does the developer of Password Store need to update?
I'm getting a class not found exception for CryproInputParcel when trying
to decrypt using the neo. Thanks.
```

**Comment by dschuermann** [comment]
I was able to reproduce, will look into it

**Comment by dschuermann** [comment]
It's not OpenPgpDecryptionResult...

```
 18209                 Parcel  E  Class not found when unmarshalling: org.sufficientlysecure.keychain.service.input.CryptoInputParcel
 18209                 Parcel  E  java.lang.ClassNotFoundException: org.sufficientlysecure.keychain.service.input.CryptoInputParcel
 18209                 Parcel  E  at java.lang.Class.classForName(Native Method)
 18209                 Parcel  E  at java.lang.Class.forName(Class.java:309)
 18209                 Parcel  E  at android.os.Parcel.readParcelableCreator(Parcel.java:2281)
 18209                 Parcel  E  at android.os.Parcel.readParcelable(Parcel.java:2245)
 18209                 Parcel  E  at android.os.Parcel.readValue(Parcel.java:2152)
 18209                 Parcel  E  at android.os.Parcel.readArrayMapInternal(Parcel.java:2485)
 18209                 Parcel  E  at android.os.BaseBundle.unparcel(BaseBundle.java:221)
 18209                 Parcel  E  at android.os.BaseBundle.putBoolean(BaseBundle.java:333)
 18209                 Parcel  E  at android.content.Intent.putExtra(Intent.java:6033)
 18209                 Parcel  E  at com.fsck.k9.activity.MessageCompose.executeOpenPgpMethod(MessageCompose.java:1903)
 18209                 Parcel  E  at com.fsck.k9.activity.MessageCompose.onActivityResult(MessageCompose.java:2250)
 18209                 Parcel  E  at android.app.Activity.dispatchActivityResult(Activity.java:6192)
 18209                 Parcel  E  at android.app.ActivityThread.deliverResults(ActivityThread.java:3601)
 18209                 Parcel  E  at android.app.ActivityThread.handleSendResult(ActivityThread.java:3648)
 18209                 Parcel  E  at android.app.ActivityThread.access$1400(ActivityThread.java:154)
 18209                 Parcel  E  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1370)
 18209                 Parcel  E  at android.os.Handler.dispatchMessage(Handler.java:102)
 18209                 Parcel  E  at android.os.Looper.loop(Looper.java:135)
 18209                 Parcel  E  at android.app.ActivityThread.main(ActivityThread.java:5289)
 18209                 Parcel  E  at java.lang.reflect.Method.invoke(Native Method)
 18209                 Parcel  E  at java.lang.reflect.Method.invoke(Method.java:372)
 18209                 Parcel  E  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
 18209                 Parcel  E  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
 18209                 Parcel  E  Caused by: java.lang.ClassNotFoundException: Didn't find class "org.sufficientlysecure.keychain.service.input.CryptoInputParcel" on path: DexPathList[[zip file "/data/app/com.fsck.k9-1/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
 18209                 Parcel  E  at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
 18209                 Parcel  E  at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
 18209                 Parcel  E  at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
 18209                 Parcel  E  ... 23 more
 18209                 Parcel  E  Suppressed: java.lang.ClassNotFoundException: org.sufficientlysecure.keychain.service.input.CryptoInputParcel
 18209                 Parcel  E  at java.lang.Class.classForName(Native Method)
 18209                 Parcel  E  at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
 18209                 Parcel  E  at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
 18209                 Parcel  E  at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
 18209                 Parcel  E  ... 24 more
 18209                 Parcel  E  Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available
 18209         AndroidRuntime  D  Shutting down VM
 18209         AndroidRuntime  E  FATAL EXCEPTION: main
 18209         AndroidRuntime  E  Process: com.fsck.k9, PID: 18209
 18209         AndroidRuntime  E  java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=12, result=-1, data=Intent { act=org.openintents.openpgp.action.SIGN_AND_ENCRYPT (has extras) }} to activity {com.fsck.k9/com.fsck.k9.activity.MessageCompose}: android.os.BadParcelableException: ClassNotFoundException when unmarshalling: org.sufficientlysecure.keychain.service.input.CryptoInputParcel
 18209         AndroidRuntime  E  at android.app.ActivityThread.deliverResults(ActivityThread.java:3605)
 18209         AndroidRuntime  E  at android.app.ActivityThread.handleSendResult(ActivityThread.java:3648)
 18209         AndroidRuntime  E  at android.app.ActivityThread.access$1400(ActivityThread.java:154)
 18209         AndroidRuntime  E  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1370)
 18209         AndroidRuntime  E  at android.os.Handler.dispatchMessage(Handler.java:102)
 18209         AndroidRuntime  E  at android.os.Looper.loop(Looper.java:135)
 18209         AndroidRuntime  E  at android.app.ActivityThread.main(ActivityThread.java:5289)
 18209         AndroidRuntime  E  at java.lang.reflect.Method.invoke(Native Method)
 18209         AndroidRuntime  E  at java.lang.reflect.Method.invoke(Method.java:372)
 18209         AndroidRuntime  E  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
 18209         AndroidRuntime  E  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
 18209         AndroidRuntime  E  Caused by: android.os.BadParcelableException: ClassNotFoundException when unmarshalling: org.sufficientlysecure.keychain.service.input.CryptoInputParcel
 18209         AndroidRuntime  E  at android.os.Parcel.readParcelableCreator(Parcel.java:2295)
 18209         AndroidRuntime  E  at android.os.Parcel.readParcelable(Parcel.java:2245)
 18209         AndroidRuntime  E  at android.os.Parcel.readValue(Parcel.java:2152)
 18209         AndroidRuntime  E  at android.os.Parcel.readArrayMapInternal(Parcel.java:2485)
 18209         AndroidRuntime  E  at android.os.BaseBundle.unparcel(BaseBundle.java:221)
 18209         AndroidRuntime  E  at android.os.BaseBundle.putBoolean(BaseBundle.java:333)
 18209         AndroidRuntime  E  at android.content.Intent.putExtra(Intent.java:6033)
 18209         AndroidRuntime  E  at com.fsck.k9.activity.MessageCompose.executeOpenPgpMethod(MessageCompose.java:1903)
 18209         AndroidRuntime  E  at com.fsck.k9.activity.MessageCompose.onActivityResult(MessageCompose.java:2250)
 18209         AndroidRuntime  E  at android.app.Activity.dispatchActivityResult(Activity.java:6192)
 18209         AndroidRuntime  E  at android.app.ActivityThread.deliverResults(ActivityThread.java:3601)
 18209         AndroidRuntime  E  ... 10 more
```

**Comment by dschuermann** [comment]
closed with https://github.com/open-keychain/open-keychain/commit/979605b5de92314736e43506ca262d5f57675485
