### ISSUE TITLE
Unhandled exception when scanning NFC Yubikey during seemingly any crypto operation

### ISSUE THREAD

**Issue by Orbixx** [open-keychain/open-keychain#1493]
I submitted a couple of crash reports about 10 minutes ago via Google Play, it seems to happen every time I scan the Yubikey when requested by Open Keychain. Seems like something is getting missed when firing off an async operation. Device is a Nexus 6 running latest stock firmware.

**Comment by Orbixx** [comment]
This seems to have been caused by me leaving the "use default PINs for YubiKey" option checked after messing around with it before having set up my keypair on the YubiKey. Amusingly, after trying several times, it (unknowingly to me) locked my PIN and without much further thought, I tried using it on my desktop again only to find it had stopped working.

GPG was being hilariously unhelpful and I genuinely thought I had changed something and it had come into play after a reboot, then I happened to notice the PIN retry counter being zero. Reset the counter with the admin PIN and now it's working with Open Keychain!

You might want to handle that exception though, and also really just remove that "use default PINs" option completely.

**Comment by dschuermann** [comment]
Sounds like a regression bug. Thanks for reporting. Your stacktrace:
```
java.lang.RuntimeException: An error occured while executing doInBackground()
at android.os.AsyncTask$3.done(AsyncTask.java:304)
at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
at java.util.concurrent.FutureTask.run(FutureTask.java:242)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
at java.lang.Thread.run(Thread.java:818)
Caused by: java.lang.RuntimeException: Can't create handler inside thread that has not called Looper.prepare()
at android.os.Handler.<init>(Handler.java:200)
at android.os.Handler.<init>(Handler.java:114)
at android.widget.Toast$TN.<init>(Toast.java:344)
at android.widget.Toast.<init>(Toast.java:100)
at android.widget.Toast.makeText(Toast.java:258)
at org.sufficientlysecure.keychain.ui.base.BaseNfcActivity.toast(BaseNfcActivity.java:914)
at org.sufficientlysecure.keychain.ui.NfcOperationActivity.handlePinError(NfcOperationActivity.java:313)
at org.sufficientlysecure.keychain.ui.base.BaseNfcActivity.nfcVerifyPIN(BaseNfcActivity.java:685)
at org.sufficientlysecure.keychain.ui.base.BaseNfcActivity.nfcCalculateSignature(BaseNfcActivity.java:530)
at org.sufficientlysecure.keychain.ui.NfcOperationActivity.doNfcInBackground(NfcOperationActivity.java:159)
at org.sufficientlysecure.keychain.ui.base.BaseNfcActivity.handleTagDiscoveredIntent(BaseNfcActivity.java:436)
at org.sufficientlysecure.keychain.ui.base.BaseNfcActivity$1.doInBackground(BaseNfcActivity.java:149)
at org.sufficientlysecure.keychain.ui.base.BaseNfcActivity$1.doInBackground(BaseNfcActivity.java:139)
at android.os.AsyncTask$2.call(AsyncTask.java:292)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
... 4 more
```

Should be an easy fix.

**Comment by dschuermann** [comment]
Default PIN setting is now removed in https://github.com/open-keychain/open-keychain/commit/4f2e02d6064202689eab0201b2bf06a6c842472d

I can no longer reproduce the exception, closing
