### ISSUE TITLE
Adding linked identity crashes OK

### ISSUE THREAD

**Issue by dschuermann** [open-keychain/open-keychain#1509]
```
16096             Keychain D  D  Everything okay!
 16096             Keychain D  D  Caching entered passphrase
 16096             Keychain D  D  PassphraseCacheService.addCachedPassphrase() for 8181922323901784706
 12252             Keychain D  D  PassphraseCacheService.onStartCommand()
 16096         OpenGLRenderer  D  endAllStagingAnimators on 0x9ce7b280 (RippleDrawable) with handle 0x9e0492b0
 12252             Keychain D  D  PassphraseCacheService: Received ACTION_PASSPHRASE_CACHE_ADD intent in onStartCommand() with masterkeyId: 8181922323901784706, subKeyId: 8181922323901784706, ttl: 28800, usrId: Dominik Schürmann <dominik@dominikschuermann.de>
  4656   WaitForWifiAsyncTask  D  waiting for an IP address...
 16096             Keychain D  D  received activity result in OperationHelper
 16096             Keychain D  D  handling activity result in OperationHelper
 16096             Keychain D  V  log: LogEntryParcel{mLevel=START, mType=MSG_ED, mParameters=null, mIndent=0}
 16096             Keychain D  V  log: LogEntryParcel{mLevel=DEBUG, mType=MSG_ED_FETCHING, mParameters=[0x718c070100012282], mIndent=1}
 16096             Keychain D  V  query(uri=content://org.sufficientlysecure.keychain.debug.provider/key_rings/8181922323901784706/unified, proj=[has_any_secret, verified, privkey_data])
 16096             Keychain D  V  log: LogEntryParcel{mLevel=START, mType=MSG_MF, mParameters=[0x718c070100012282], mIndent=0}
 16096             Keychain D  D  Send message by setProgress with progress=10, max=100
 16096             Keychain D  D  Send message by setProgress with progress=10, max=100
 16096             Keychain D  D  Send message by setProgress with progress=15, max=100
 16096             Keychain D  V  log: LogEntryParcel{mLevel=DEBUG, mType=MSG_MF_UNLOCK, mParameters=null, mIndent=1}
 16096             Keychain D  D  Send message by setProgress with progress=17, max=100
 16096             Keychain D  V  log: LogEntryParcel{mLevel=INFO, mType=MSG_MF_UAT_ADD_UNKNOWN, mParameters=null, mIndent=1}
 16096         AndroidRuntime  E  FATAL EXCEPTION: Thread-11716
 16096         AndroidRuntime  E  Process: org.sufficientlysecure.keychain.debug, PID: 16096
 16096         AndroidRuntime  E  java.lang.NullPointerException: Attempt to invoke virtual method 'long java.util.Date.getTime()' on a null object reference
 16096         AndroidRuntime  E  at org.spongycastle.bcpg.sig.SignatureCreationTime.timeToBytes(SignatureCreationTime.java:18)
 16096         AndroidRuntime  E  at org.spongycastle.bcpg.sig.SignatureCreationTime.<init>(SignatureCreationTime.java:39)
 16096         AndroidRuntime  E  at org.spongycastle.openpgp.PGPSignatureSubpacketGenerator.setSignatureCreationTime(PGPSignatureSubpacketGenerator.java:100)
 16096         AndroidRuntime  E  at org.sufficientlysecure.keychain.pgp.PgpKeyOperation.generateHashedSelfSigSubpackets(PgpKeyOperation.java:1483)
 16096         AndroidRuntime  E  at org.sufficientlysecure.keychain.pgp.PgpKeyOperation.generateUserAttributeSignature(PgpKeyOperation.java:1516)
 16096         AndroidRuntime  E  at org.sufficientlysecure.keychain.pgp.PgpKeyOperation.internal(PgpKeyOperation.java:614)
 16096         AndroidRuntime  E  at org.sufficientlysecure.keychain.pgp.PgpKeyOperation.modifySecretKeyRing(PgpKeyOperation.java:483)
 16096         AndroidRuntime  E  at org.sufficientlysecure.keychain.operations.EditKeyOperation.execute(EditKeyOperation.java:100)
 16096         AndroidRuntime  E  at org.sufficientlysecure.keychain.operations.EditKeyOperation.execute(EditKeyOperation.java:59)
 16096         AndroidRuntime  E  at org.sufficientlysecure.keychain.service.KeychainService$1.run(KeychainService.java:145)
 16096         AndroidRuntime  E  at java.lang.Thread.run(Thread.java:818)
```

**Comment by dschuermann** [comment]
Looks like a regression due to refactorings of the parcel
