### ISSUE TITLE
Importing key: "import operation failed"

### ISSUE THREAD

**Issue by tasn** [open-keychain/open-keychain#1531]
I have tried importing keys, and everything works as expected. This key however, doesn't. It's the pubkey corresponding to my private key. "Update my keys" also doesn't work.

Log:

[START]Importing key
    [DEBUG]Using keyserver hkps://hkps.pool.sks-keyservers.net
        [INFO]Retrieving from keyserver: 0xd2e584c37c477933
    [ERROR]Import operation failed!

Please let me know if you need any other information.

**Comment by adithyaphilip** [comment]
What encryption algorithm does your key use?
The trace:
```
09-16 01:14:48.558    7156-9013/org.sufficientlysecure.keychain.debug D/Keychain D﹕ hkp keyserver query: https://hkps.pool.sks-keyservers.net:443/pks/lookup?op=get&options=mr&search=0x9e21f091fc395f366a4743e2d2e584c37c477933 Proxy: null
09-16 01:14:49.778    7156-9013/org.sufficientlysecure.keychain.debug E/Keychain D﹕ Encountered bad key on import!
    java.io.IOException: unknown signature key algorithm: 22
            at org.spongycastle.bcpg.SignaturePacket.<init>(SignaturePacket.java:179)
            at org.spongycastle.bcpg.BCPGInputStream.readPacket(BCPGInputStream.java:232)
            at org.spongycastle.openpgp.PGPKeyRing.readSignaturesAndTrust(PGPKeyRing.java:53)
            at org.spongycastle.openpgp.PGPKeyRing.readUserIDs(PGPKeyRing.java:91)
            at org.spongycastle.openpgp.PGPPublicKeyRing.<init>(PGPPublicKeyRing.java:73)
            at org.spongycastle.openpgp.PGPObjectFactory.nextObject(PGPObjectFactory.java:131)
            at org.sufficientlysecure.keychain.pgp.UncachedKeyRing$2.cacheNext(UncachedKeyRing.java:181)
            at org.sufficientlysecure.keychain.pgp.UncachedKeyRing$2.hasNext(UncachedKeyRing.java:202)
            at org.sufficientlysecure.keychain.pgp.UncachedKeyRing.decodeFromData(UncachedKeyRing.java:145)
            at org.sufficientlysecure.keychain.operations.ImportOperation.serialKeyRingImport(ImportOperation.java:206)
            at org.sufficientlysecure.keychain.operations.ImportOperation.access$000(ImportOperation.java:83)
            at org.sufficientlysecure.keychain.operations.ImportOperation$1.call(ImportOperation.java:447)
            at org.sufficientlysecure.keychain.operations.ImportOperation$1.call(ImportOperation.java:439)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)
```
 @dschuermann @Valodim Looks like we don't support it yet?

**Comment by adithyaphilip** [comment]
Okay, had a look at the key (https://pgp.mit.edu/pks/lookup?op=get&search=0xd2e584c37c477933) with `gpg --list-packets` and it seems that there are a couple of signatures (6 to be precise) which use algorithm 22. 
```
:signature packet: algo 22, keyid A3B5C016618D9AAA
	version 4, created 1441476269, md5len 0, sigclass 0x10
	digest algo 10, begin of digest 76 3c
	hashed subpkt 2 len 4 (sig created 2015-09-05)
	subpkt 16 len 8 (issuer key ID A3B5C016618D9AAA)
	unknown algorithm 22
```
Looks like spongycastle throws an error when it can't parse a signature instead of skipping it and continuing. I guess this might be a serious issue since you could sign anyone's key with an invalid algorithm and upload it and spongycastle (and consequently us) wouldn't be able to deal with it?

**Comment by dschuermann** [comment]
@adithyaphilip yeah, we noticed this behavior before. You are totally right that it poses a serious DoS attack.
We should definitely change the behavior to skip unsupported signature packets.

**Comment by adithyaphilip** [comment]
Should be fixed with https://github.com/open-keychain/spongycastle/pull/5

**Comment by tasn** [comment]
Thanks for your very quick response. Sorry for my lack of response. I was away, with very limited connectivity. Looking forward to a release that includes the fix.

Thanks.
