### ISSUE TITLE
NetworkOnMainThreadException during import

### ISSUE THREAD

**Issue by Valodim** [open-keychain/open-keychain#1568]
```
java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=94211, result=-1, data=Intent { dat=content://com.microsoft.skydrive.content.StorageAccessProvider/document/content://com.microsoft.skydrive.content.metadata/property/danny%40trisect.uk/Items/69D7517BB0D682B7!4329/Danny%20Horne%20danny%40trisect.uk%20(0x51691E5F)%20pub-sec.asc flg=0x1 }} to activity {org.sufficientlysecure.keychain/org.sufficientlysecure.keychain.ui.ImportKeysActivity}: android.os.NetworkOnMainThreadException
	at android.app.ActivityThread.deliverResults(ActivityThread.java:3680)
	at android.app.ActivityThread.handleSendResult(ActivityThread.java:3723)
	at android.app.ActivityThread.access$1300(ActivityThread.java:156)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1400)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:211)
	at android.app.ActivityThread.main(ActivityThread.java:5373)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1020)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:815)
Caused by: android.os.NetworkOnMainThreadException
	at android.os.Parcel.readException(Parcel.java:1568)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:185)
	at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:148)
	at android.content.ContentProviderProxy.openTypedAssetFile(ContentProviderNative.java:691)
	at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1108)
	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:948)
	at android.content.ContentResolver.openInputStream(ContentResolver.java:673)
	at org.sufficientlysecure.keychain.ui.ImportKeysListFragment.getInputData(ImportKeysListFragment.java:440)
	at org.sufficientlysecure.keychain.ui.ImportKeysListFragment.onCreateLoader(ImportKeysListFragment.java:308)
	at android.support.v4.app.LoaderManagerImpl.createLoader(LoaderManager.java:490)
	at android.support.v4.app.LoaderManagerImpl.createAndInstallLoader(LoaderManager.java:499)
	at android.support.v4.app.LoaderManagerImpl.restartLoader(LoaderManager.java:646)
	at org.sufficientlysecure.keychain.ui.ImportKeysListFragment.restartLoaders(ImportKeysListFragment.java:293)
	at org.sufficientlysecure.keychain.ui.ImportKeysListFragment.loadNew(ImportKeysListFragment.java:273)
	at org.sufficientlysecure.keychain.ui.ImportKeysActivity.loadCallback(ImportKeysActivity.java:353)
	at org.sufficientlysecure.keychain.ui.ImportKeysFileFragment.onActivityResult(ImportKeysFileFragment.java:104)
	at android.support.v4.app.FragmentActivity.onActivityResult(FragmentActivity.java:165)
	at org.sufficientlysecure.keychain.ui.base.BaseNfcActivity.onActivityResult(BaseNfcActivity.java:385)
	at org.sufficientlysecure.keychain.ui.ImportKeysActivity.onActivityResult(ImportKeysActivity.java:463)
	at android.app.Activity.dispatchActivityResult(Activity.java:6236)
	at android.app.ActivityThread.deliverResults(ActivityThread.java:3676)
	... 10 more
```

this happens when a non-local uri is opened in the import dialog, e.g. from a cloud storage DocumentProvider. the `getInputData` method is called directly in the `onActivityResult` stack (ui thread), which breaks if the uri resolves to a non-local address.

**Comment by Valodim** [comment]
should be fixed in c55ca09a0658e3602a1f349f2d1b58a54c7f95b4. could anyone test if this works with some cloud DocumentProvider for me?

**Comment by Valodim** [comment]
...no?
