### ISSUE TITLE
"not attached to window manager" trying to run orbot silent start

### ISSUE THREAD

**Issue by Valodim** [open-keychain/open-keychain#1572]
```
java.lang.IllegalArgumentException: View=com.android.internal.policy.PhoneWindow$DecorView{b6f0f9a V.E...... R.....ID 0,0-1368,0} not attached to window manager
	at android.view.WindowManagerGlobal.findViewLocked(WindowManagerGlobal.java:424)
	at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:350)
	at android.view.WindowManagerImpl.removeViewImmediate(WindowManagerImpl.java:116)
	at android.app.Dialog.dismissDialog(Dialog.java:362)
	at android.app.Dialog.dismiss(Dialog.java:345)
	at org.sufficientlysecure.keychain.util.orbot.OrbotHelper$SilentStartManager$1$1.run(OrbotHelper.java:428)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5417)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by adithyaphilip** [comment]
Will check it out
