### ISSUE TITLE
service: check if supplied signing key exists

### ISSUE THREAD

**Issue by Valodim** [open-keychain/open-keychain#1577]
we have a couple crash reports where a nonexistent signing subkey is used by the API. this doesn't happen from our UI, but an app using the API might supply nonexistent signing keys:

```
java.lang.NullPointerException: Attempt to invoke virtual method 'org.spongycastle.openpgp.PGPPublicKey org.spongycastle.openpgp.PGPSecretKey.getPublicKey()' on a null object reference
	at org.sufficientlysecure.keychain.pgp.CanonicalizedSecretKey.<init>(CanonicalizedSecretKey.java:73)
	at org.sufficientlysecure.keychain.pgp.CanonicalizedSecretKeyRing.getSecretKey(CanonicalizedSecretKeyRing.java:70)
	at org.sufficientlysecure.keychain.pgp.PgpSignEncryptOperation.execute(PgpSignEncryptOperation.java:173)
	at org.sufficientlysecure.keychain.operations.SignEncryptOperation.execute(SignEncryptOperation.java:153)
	at org.sufficientlysecure.keychain.operations.SignEncryptOperation.execute(SignEncryptOperation.java:61)
	at org.sufficientlysecure.keychain.service.KeychainService$1.run(KeychainService.java:143)
	at java.lang.Thread.run(Thread.java:818)
```

**Comment by RolandKluge** [comment]
I also experienced this bug using OpenKeychain (4.5) and K-9 Mail (5.207)

**Comment by dschuermann** [comment]
@RolandKluge This should really not happen in the latest K-9 Mail. Are you using a special configuration of K-9?
Can you post your logcat?

**Comment by RolandKluge** [comment]
I have recently installed K-9 Mail and OpenKeychain from scratch (Google Play Store).
The problem occurs, when I try to send a message to myself (sender account = receiver account, mail AT roland DASH kluge DOT de). The key is a little outdated (1024bit, DAS)
Encryption ("lock icon") is set to "Encrypt if possible" (middle position).

I have also attached the logcat output:
[K9MailLogcat_2017-09-06.txt](https://github.com/open-keychain/open-keychain/files/1281523/K9MailLogcat_2017-09-06.txt)
