### ISSUE TITLE
Permission Denial: reading MediaProvider uri content://media/external/fs_id

### ISSUE THREAD

**Issue by dschuermann** [open-keychain/open-keychain#1583]
I get this in logcat when saving a backup on Android 6, not sure why, still everything works.

```
11-02 19:24:17.499   938      956           DatabaseUtils  E  Writing exception to parcel
11-02 19:24:17.499   938      956           DatabaseUtils  E  java.lang.SecurityException: Permission Denial: reading com.android.providers.media.MediaProvider uri content://media/external/fs_id from pid=9373, uid=10062 requires android.permission.READ_EXTERNAL_STORAGE, or grantUriPermission()
11-02 19:24:17.499   938      956           DatabaseUtils  E  at android.content.ContentProvider.enforceReadPermissionInner(ContentProvider.java:605)
11-02 19:24:17.499   938      956           DatabaseUtils  E  at android.content.ContentProvider$Transport.enforceReadPermission(ContentProvider.java:480)
11-02 19:24:17.499   938      956           DatabaseUtils  E  at android.content.ContentProvider$Transport.query(ContentProvider.java:211)
11-02 19:24:17.499   938      956           DatabaseUtils  E  at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:112)
11-02 19:24:17.499   938      956           DatabaseUtils  E  at android.os.Binder.execTransact(Binder.java:453)
```

**Comment by dschuermann** [comment]
Same when encrypting a file to the storage.

**Comment by dschuermann** [comment]
Related: https://commonsware.com/blog/2015/10/07/runtime-permissions-files-action-send.html
"READ_EXTERNAL_STORAGE is a dangerous permission on Android 6.0, and therefore is subject to the runtime permission system if your targetSdkVersion is 23 or higher."

Still not sure how this is relevant here.

**Comment by dschuermann** [comment]
Looks like the MediaScanner fails to index the file: http://stackoverflow.com/questions/33129884/mediascannerconnection-fails-on-android-6-because-of-permission-denial

**Comment by dschuermann** [comment]
not sure if this is problem is really relevant, moving out of milestone
