### ISSUE TITLE
v3.7 crashes when you click encrypt text icon

### ISSUE THREAD

**Issue by marix11** [open-keychain/open-keychain#1611]
After upgrading from 3.6.1, when you clixk encrypt text icom it crashes on some keys, but not all

**Comment by dschuermann** [comment]
What Android version are you using?

**Comment by Valodim** [comment]
related stack trace

```
java.lang.RuntimeException: Unable to destroy activity {org.sufficientlysecure.keychain/org.sufficientlysecure.keychain.ui.EncryptTextActivity}: java.lang.NullPointerException
	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3886)
	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3904)
	at android.app.ActivityThread.access$1500(ActivityThread.java:172)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1361)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:146)
	at android.app.ActivityThread.main(ActivityThread.java:5694)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1291)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1107)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.NullPointerException
	at android.support.v4.app.LoaderManagerImpl.restartLoader(LoaderManager.java:692)
	at org.sufficientlysecure.keychain.ui.widget.EncryptKeyCompletionView.performFiltering(EncryptKeyCompletionView.java:196)
	at android.widget.MultiAutoCompleteTextView.performFiltering(MultiAutoCompleteTextView.java:96)
	at android.widget.AutoCompleteTextView.doAfterTextChanged(AutoCompleteTextView.java:780)
	at android.widget.AutoCompleteTextView$MyWatcher.afterTextChanged(AutoCompleteTextView.java:745)
	at android.widget.TextView.sendAfterTextChanged(TextView.java:8961)
	at android.widget.TextView$ChangeWatcher.afterTextChanged(TextView.java:11314)
	at android.text.SpannableStringBuilder.sendAfterTextChanged(SpannableStringBuilder.java:978)
	at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:499)
	at android.text.SpannableStringBuilder.delete(SpannableStringBuilder.java:212)
	at android.text.SpannableStringBuilder.delete(SpannableStringBuilder.java:30)
	at com.tokenautocomplete.TokenCompleteTextView.removeSpan(TokenCompleteTextView.java:905)
	at com.tokenautocomplete.TokenCompleteTextView.performCollapse(TokenCompleteTextView.java:668)
	at com.tokenautocomplete.TokenCompleteTextView.onFocusChanged(TokenCompleteTextView.java:720)
	at org.sufficientlysecure.keychain.ui.widget.EncryptKeyCompletionView.onFocusChanged(EncryptKeyCompletionView.java:176)
	at android.view.View.clearFocusInternal(View.java:4951)
	at android.view.View.unFocus(View.java:4985)
	at android.view.ViewGroup.unFocus(ViewGroup.java:832)
	at android.view.ViewGroup.unFocus(ViewGroup.java:832)
	at android.view.ViewGroup.removeViewInternal(ViewGroup.java:4056)
	at android.view.ViewGroup.removeViewInternal(ViewGroup.java:4044)
	at android.view.ViewGroup.removeView(ViewGroup.java:3976)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1167)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1248)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1230)
	at android.support.v4.app.FragmentManagerImpl.dispatchDestroy(FragmentManager.java:2079)
	at android.support.v4.app.FragmentController.dispatchDestroy(FragmentController.java:235)
	at android.support.v4.app.FragmentActivity.onDestroy(FragmentActivity.java:326)
	at android.support.v7.app.AppCompatActivity.onDestroy(AppCompatActivity.java:161)
	at android.app.Activity.performDestroy(Activity.java:5713)
	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1123)
	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3873)
	... 11 more
```

**Comment by marix11** [comment]
Yes galaxy s4, cm12.1. Notjing in logs about openkeychain

**Comment by JasperWeiss** [comment]
Same problem here. HTC One M8, Cyanogenmod 12.1 nightly

**Comment by tagru** [comment]
Same here. Crashes when click on text field and when click on icon to encrypt file. 
Sony Xperia V Android 4.3 no root
OpenKeyChain 3.7 from F-Droid

**Comment by Valodim** [comment]
Wow, I just tested a bit and we have a *ton* of crashes from that To field under various conditions. I wonder if this changed a lot from the recent update of the lib? Some crashes are fixable, one which caused a lot of crash reports should be fixed in cb1527e2a1a790455b4d2e2041ed07accbe3c80f. What I really couldn't find a very good fix for is handling of the prefix over the activity lifecycle... hmmm. I'll sleep on it. Maybe we could just ditch the prefix and use a hint instead.

**Comment by dschuermann** [comment]
@Valodim Are we done with this issue or are there more problems?

**Comment by Valodim** [comment]
Yes, I would stick to the hint instead of the prefix.
