### ISSUE TITLE
ActivityNotFoundException: android.intent.action.OPEN_DOCUMENT 

### ISSUE THREAD

**Issue by liphistius** [open-keychain/open-keychain#1625]
Steps to reproduce:
1) Encrypt/Decrypt
2.1) Encrypt files
3) Add Files ("Unfortunately, OpenKeychain has stopped.")
2.2) Decrypt/Verify
3) Select input file ("Unfortunately, OpenKeychain has stopped.")

Device: Redmi Note 2
Chipset: Mediatek MT6795 Helio X10
CPU: Octa-core 2.0 GHz Cortex-A53

**Comment by Valodim** [comment]
this seems to be a stack trace of a related issue:

```
android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.OPEN_DOCUMENT cat=[android.intent.category.OPENABLE] typ=*/* (has extras) }
	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java)
	at android.app.Activity.startActivityForResult(Activity.java)
	at android.app.Activity.startActivityForResult(Activity.java)
	at android.support.v4.app.FragmentActivity.startActivityFromFragment(FragmentActivity.java:855)
	at android.support.v4.app.FragmentActivity$HostCallbacks.onStartActivityFromFragment(FragmentActivity.java:907)
	at android.support.v4.app.Fragment.startActivityForResult(Fragment.java:927)
	at org.sufficientlysecure.keychain.util.FileHelper.openDocumentKitKat(FileHelper.java:135)
	at org.sufficientlysecure.keychain.util.FileHelper.openDocument(FileHelper.java:97)
	at org.sufficientlysecure.keychain.ui.ImportKeysFileFragment$1.onClick(ImportKeysFileFragment.java:70)
	at android.view.View.performClick(View.java)
	at android.view.View$PerformClick.run(View.java)
	at android.os.Handler.handleCallback(Handler.java)
	at android.os.Handler.dispatchMessage(Handler.java)
	at android.os.Looper.loop(Looper.java)
	at android.app.ActivityThread.main(ActivityThread.java)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java)
```

it seems like the vendor of these phones, Xiaomi, ships an Android version which breaks basic  functionality... I'm afraid the best we can do there is fail more gracefully with an error message :(

**Comment by Valodim** [comment]
signal handled the issue similarly: https://github.com/WhisperSystems/Signal-Android/commit/6e3751a0c5870f8dc4ad9d210ce08b153c3307bf

**Comment by liphistius** [comment]
Thank you for the prompt reply!
I had a feeling this was the case. I have many other apps malfunctioning in MIUI.
This is probably out of your area of expertise, but do you think an AOSP ROM would fix these errors, or is the problem rooted deeper?

Thanks for having a look! :)

**Comment by Valodim** [comment]
Yes, pretty sure this issue isn't present on the AOSP rom.

**Comment by liphistius** [comment]
Thanks!

**Comment by dschuermann** [comment]
@Valodim This hasn't been fixed right?

**Comment by liphistius** [comment]
The issue has been fixed.
Currently the app crashes at pressing "Encrypt and Save File".
The latest APG (1.1.1 from 2014) from F-Droid is able to encrypt/decrypt correctly.
Should I reopen the issue?

![photo_2016-01-16_11-49-16](https://cloud.githubusercontent.com/assets/16261334/12371752/4114f628-bc47-11e5-8f61-062775d54688.jpg)
![photo_2016-01-16_11-49-29](https://cloud.githubusercontent.com/assets/16261334/12371753/45561f3c-bc47-11e5-8609-b4e38b2b050a.jpg)


My apologies for closing the issue, I'm new to github and don't know how to code :).

Kind regards,

L

**Comment by Valodim** [comment]
Yup, this is still a bug. The vendor of your phone apparently didn't care much to keep basic assumptions of the android operating system intact. They also apparently intercept bug reports so they never reach us in the developer console but go to them instead. Good job, vendor!

Is this Xiamoi? Either way please *do* report this issue using that dialog, maybe with enough reports they'll fix (as in "no longer break") their shipped android version.

We'll fix the crash, and maybe save the file in a fixed location (`/sdcard/OpenKeychain/`) as a fallback, but that's all we can do.

**Comment by Valodim** [comment]
btw this is a simple fix, just needs handling in FileHelper. there is nothing we can do, so an error Snackbar is the way to go.

**Comment by ShadowRZ** [comment]
@liphistius Mine doesn't crash, but I can't save the file.
"Save" looks gray.
