### ISSUE TITLE
jacoco.exec: open failed: EROFS

### ISSUE THREAD

**Issue by dschuermann** [open-keychain/open-keychain#1626]
Not important, but would be nice to get rid of this

```
System.err  W  java.io.FileNotFoundException: /jacoco.exec: open failed: EROFS (Read-only file system)
 17234             System.err  W  at libcore.io.IoBridge.open(IoBridge.java:409)
 17234             System.err  W  at java.io.FileOutputStream.<init>(FileOutputStream.java:88)
 17234             System.err  W  at org.jacoco.agent.rt.internal_773e439.output.FileOutput.openFile(FileOutput.java:67)
 17234             System.err  W  at org.jacoco.agent.rt.internal_773e439.output.FileOutput.startup(FileOutput.java:49)
 17234             System.err  W  at org.jacoco.agent.rt.internal_773e439.Agent.startup(Agent.java:122)
 17234             System.err  W  at org.jacoco.agent.rt.internal_773e439.Agent.getInstance(Agent.java:50)
 17234             System.err  W  at org.jacoco.agent.rt.internal_773e439.Offline.<clinit>(Offline.java:31)
 17234             System.err  W  at org.sufficientlysecure.keychain.KeychainApplication.$jacocoInit(KeychainApplication.java)
 17234             System.err  W  at org.sufficientlysecure.keychain.KeychainApplication.<clinit>(KeychainApplication.java)
 17234             System.err  W  at java.lang.Class.newInstanceImpl(Native Method)
 17234             System.err  W  at java.lang.Class.newInstance(Class.java:1208)
 17234             System.err  W  at android.app.Instrumentation.newApplication(Instrumentation.java:990)
 17234             System.err  W  at android.app.Instrumentation.newApplication(Instrumentation.java:975)
 17234             System.err  W  at android.app.LoadedApk.makeApplication(LoadedApk.java:502)
 17234             System.err  W  at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4301)
 17234             System.err  W  at android.app.ActivityThread.access$1500(ActivityThread.java:135)
 17234             System.err  W  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
 17234             System.err  W  at android.os.Handler.dispatchMessage(Handler.java:102)
 17234             System.err  W  at android.os.Looper.loop(Looper.java:136)
 17234             System.err  W  at android.app.ActivityThread.main(ActivityThread.java:5001)
 17234             System.err  W  at java.lang.reflect.Method.invokeNative(Native Method)
 17234             System.err  W  at java.lang.reflect.Method.invoke(Method.java:515)
 17234             System.err  W  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
 17234             System.err  W  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
 17234             System.err  W  at dalvik.system.NativeStart.main(Native Method)
 17234             System.err  W  Caused by: libcore.io.ErrnoException: open failed: EROFS (Read-only file system)
 17234             System.err  W  at libcore.io.Posix.open(Native Method)
 17234             System.err  W  at libcore.io.BlockGuardOs.open(BlockGuardOs.java:110)
 17234             System.err  W  at libcore.io.IoBridge.open(IoBridge.java:393)
 17234             System.err  W  ... 24 more
```

**Comment by shreyas29** [comment]
The "/data/data/" folder is accessed while setting the destfile property for jacoco-agent in JacocoWorkaroundJUnitRunner.java file. It requires superuser privileges to access "/data/data" folder. So if you run an application without super user permission it will generate an error.

**Comment by jdour1121** [comment]
I put the .ec file into storage/sdcard0, but i still meet the same error, why ?

**Comment by anshulvij** [comment]
Hi @jdour1121,
It's been quite sometime but I still make a comment here for other people who end up to this thread discussion.
The destination file could be put into "<path to internal storage dir>/Android/data/<app-package-name>/files/" dir.
<path to internal storage dir> can be different for different devices.
You can use path to external storage dir but then app needs the permission to write to external storage.
Try: adb install **-g** <your apk> to grant permission at install time (Android 6.0/api 23 and above)
