### ISSUE TITLE
android 6 crash on key search

### ISSUE THREAD

**Issue by Valodim** [open-keychain/open-keychain#1630]
```
12-17 16:25:54.488  17008    17008         AndroidRuntime  E  java.lang.RuntimeException: Unable to start activity ComponentInfo{org.sufficientlysecure.keychain/org.sufficientlysecure.keychain.ui.ImportKeysActivity}: java.lang.SecurityException: Permission Denial: opening provider com.android.providers.contacts.ContactsProvider2 from ProcessRecord{e9b9d6e 17008:org.sufficientlysecure.keychain/u0a85} (pid=17008, uid=10085) requires android.permission.READ_CONTACTS or android.permission.WRITE_CONTACTS
12-17 16:25:54.488  17008    17008         AndroidRuntime  E  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
12-17 16:25:54.488  17008    17008         AndroidRuntime  E  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
12-17 16:25:54.488  17008    17008         AndroidRuntime  E  at android.app.ActivityThread.-wrap11(ActivityThread.java)
12-17 16:25:54.488  17008    17008         AndroidRuntime  E  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
12-17 16:25:54.488  17008    17008         AndroidRuntime  E  at android.os.Handler.dispatchMessage(Handler.java:102)
12-17 16:25:54.488  17008    17008         AndroidRuntime  E  at android.os.Looper.loop(Looper.java:148)
12-17 16:25:54.488  17008    17008         AndroidRuntime  E  at android.app.ActivityThread.main(ActivityThread.java:5417)
12-17 16:25:54.488  17008    17008         AndroidRuntime  E  at java.lang.reflect.Method.invoke(Native Method)
12-17 16:25:54.488  17008    17008         AndroidRuntime  E  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
12-17 16:25:54.488  17008    17008         AndroidRuntime  E  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
12-17 16:25:54.488  17008    17008         AndroidRuntime  E  Caused by: java.lang.SecurityException: Permission Denial: opening provider com.android.providers.contacts.ContactsProvider2 from ProcessRecord{e9b9d6e 17008:org.sufficientlysecure.keychain/u0a85} (pid=17008, uid=10085) requires android.permission.READ_CONTACTS or android.permission.WRITE_CONTACTS
12-17 16:25:54.488  17008    17008         AndroidRuntime  E  at android.os.Parcel.readException(Parcel.java:1599)
12-17 16:25:54.488  17008    17008         AndroidRuntime  E  at android.os.Parcel.readException(Parcel.java:1552)
12-17 16:25:54.488  17008    17008         AndroidRuntime  E  at android.app.ActivityManagerProxy.getContentProvider(ActivityManagerNative.java:3550)
12-17 16:25:54.488  17008    17008         AndroidRuntime  E  at android.app.ActivityThread.acquireProvider(ActivityThread.java:4778)
12-17 16:25:54.488  17008    17008         AndroidRuntime  E  at android.app.ContextImpl$ApplicationContentResolver.acquireUnstableProvider(ContextImpl.java:2018)
12-17 16:25:54.488  17008    17008         AndroidRuntime  E  at android.content.ContentResolver.acquireUnstableProvider(ContentResolver.java:1468)
12-17 16:25:54.488  17008    17008         AndroidRuntime  E  at android.content.ContentResolver.query(ContentResolver.java:475)
12-17 16:25:54.488  17008    17008         AndroidRuntime  E  at android.content.ContentResolver.query(ContentResolver.java:434)
12-17 16:25:54.488  17008    17008         AndroidRuntime  E  at org.sufficientlysecure.keychain.util.ContactHelper.getContactNames(ContactHelper.java:298)
12-17 16:25:54.488  17008    17008         AndroidRuntime  E  at org.sufficientlysecure.keychain.ui.ImportKeysCloudFragment.onCreateView(ImportKeysCloudFragment.java:89)
12-17 16:25:54.488  17008    17008         AndroidRuntime  E  at android.support.v4.app.Fragment.performCreateView(Fragment.java:1962)
12-17 16:25:54.488  17008    17008         AndroidRuntime  E  at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1067)
12-17 16:25:54.488  17008    17008         AndroidRuntime  E  at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1248)
12-17 16:25:54.488  17008    17008         AndroidRuntime  E  at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:738)
12-17 16:25:54.488  17008    17008         AndroidRuntime  E  at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1613)
12-17 16:25:54.488  17008    17008         AndroidRuntime  E  at android.support.v4.app.FragmentController.execPendingActions(FragmentController.java:330)
12-17 16:25:54.488  17008    17008         AndroidRuntime  E  at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:547)
12-17 16:25:54.488  17008    17008         AndroidRuntime  E  at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1237)
12-17 16:25:54.488  17008    17008         AndroidRuntime  E  at android.app.Activity.performStart(Activity.java:6253)
12-17 16:25:54.488  17008    17008         AndroidRuntime  E  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2379)
```

**Comment by dschuermann** [comment]
Dublicate of #1606
