### ISSUE TITLE
fix queueing control flow for initiateInputActivity in QueueingCryptoOperationFragment

### ISSUE THREAD

**Issue by Valodim** [open-keychain/open-keychain#1651]
```
E/AndroidRuntime( 6071): Process: org.sufficientlysecure.keychain, PID: 6071
E/AndroidRuntime( 6071): java.lang.NullPointerException
E/AndroidRuntime( 6071):        at android.content.ComponentName.<init>(ComponentName.java:77)
E/AndroidRuntime( 6071):        at android.content.Intent.<init>(Intent.java:3972)
E/AndroidRuntime( 6071):        at org.sufficientlysecure.keychain.ui.base.CryptoOperationHelper.initiateInputActivity(CryptoOperationHelper.java:146)
E/AndroidRuntime( 6071):        at org.sufficientlysecure.keychain.ui.base.CryptoOperationHelper.onHandleResult(CryptoOperationHelper.java:336)
E/AndroidRuntime( 6071):        at org.sufficientlysecure.keychain.ui.base.CryptoOperationHelper$1.handleMessage(CryptoOperationHelper.java:299)
E/AndroidRuntime( 6071):        at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime( 6071):        at android.os.Looper.loop(Looper.java:136)
E/AndroidRuntime( 6071):        at android.app.ActivityThread.main(ActivityThread.java:5179)
E/AndroidRuntime( 6071):        at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 6071):        at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime( 6071):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:732)
E/AndroidRuntime( 6071):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:566)
E/AndroidRuntime( 6071):        at dalvik.system.NativeStart.main(Native Method)
W/ActivityManager( 1491):   Force finishing activity org.sufficientlysecure.keychain/.ui.DecryptActivity
W/ActivityManager( 1491): Activity pause timeout for ActivityRecord{41f30c40 u0 org.sufficientlysecure.keychain/.ui.DecryptActivity t28 f}
```

**Comment by Valodim** [comment]
the point of QueueingCryptoOperationFragment is that if the fragment isn't attached to an activity at the point where the message is delivered, the result is queued and delivered after the fragment is reattached. this works fine for the success and error case, but the user interaction case is handled directly in CryptoOperationHelper, crashing if such result is delivered while no activity is attached.

**Comment by advaita13** [comment]
@Valodim How can I reproduce the crash?

**Comment by Valodim** [comment]
this should be reproducably by enabling `Don't keep activities` in the developer options
