### ISSUE TITLE
java.lang.AssertionError: cannot clearsign in non-ascii armored text, this is a bug!

### ISSUE THREAD

**Issue by dschuermann** [open-keychain/open-keychain#1654]
From Google Play dev console.

Message from user: just crashes when trying to access with another app.

```
java.lang.AssertionError: cannot clearsign in non-ascii armored text, this is a bug!
	at org.sufficientlysecure.keychain.pgp.PgpSignEncryptOperation.execute(PgpSignEncryptOperation.java:501)
	at org.sufficientlysecure.keychain.remote.OpenPgpService.encryptAndSignImpl(OpenPgpService.java:437)
	at org.sufficientlysecure.keychain.remote.OpenPgpService.executeInternalWithStreams(OpenPgpService.java:874)
	at org.sufficientlysecure.keychain.remote.OpenPgpService.executeInternal(OpenPgpService.java:829)
	at org.sufficientlysecure.keychain.remote.OpenPgpService2$1.execute(OpenPgpService2.java:62)
	at org.openintents.openpgp.IOpenPgpService2$Stub.onTransact(IOpenPgpService2.java:80)
	at android.os.Binder.execTransact(Binder.java:446)
```

**Comment by Valodim** [comment]
yeah well, that's an invalid api request from that app...

**Comment by dschuermann** [comment]
We should return a proper api error instead of crashing.

**Comment by Valodim** [comment]
yeah I guess..

**Comment by icyflame** [comment]
Hey @Valodim and @dschuermann, I want to work on this. I am a bit confused about what error message should be returned in the result object from the `execute` function.

The Line 501 from the stack trace above is here: [b84c9a8f - PgpSignEncryptOperation.java - L502](https://github.com/open-keychain/open-keychain/blob/b84c9a8fb6b14b219bf6daf6240d3b89e7d4bfca/OpenKeychain/src/main/java/org/sufficientlysecure/keychain/pgp/PgpSignEncryptOperation.java#L502)

In the present master branch that is at: [8193cf8 - PgpSignEncryptOperation.java - L578](https://github.com/open-keychain/open-keychain/blob/8193cf82b9283b184bfc16dc2feb85071141becd/OpenKeychain/src/main/java/org/sufficientlysecure/keychain/pgp/PgpSignEncryptOperation.java#L578)

Instead of doing:

```java
if (enableEncryption) {
  ...
} else if (enableSignature && data.isCleartextSignature() && data.isEnableAsciiArmorOutput()) {
  ...
} else if (enableSignature && data.isDetachedSignature()) {
  ...
} else if (enableSignature && !data.isCleartextSignature() && !data.isDetachedSignature()) {
  ...
} else {
  throw new AssertionError("cannot clearsign in non-ascii armored text, this is a bug!");
}
```

We would have, in the last `else` block:

```java
} else {
    log.add(LogType.MSG_PSE_ERROR_SIG, indent);
    return new PgpSignEncryptResult(PgpSignEncryptResult.RESULT_ERROR, log);
}
```

I went through the [strings.xml](https://github.com/open-keychain/open-keychain/blob/master/OpenKeychain/src/main/res/values/strings.xml) file but couldn't find anything close to an API error or API invalid. The closest I could get was a `wrong signature message`

```xml
<string name="api_error_wrong_signature">
"Signature check failed! Have you installed this app from a 
different source? If you are sure that this is not an attack, 
revoke this app's registration in OpenKeychain and 
then register the app again."
</string>
```

Is this approach fine? If I am totally off track, please point me to one file that I can refer to, and I shall dig into that and reply here again! :slightly_smiling_face:

**Comment by Valodim** [comment]
This error should be caught before the operation, the code in OpenPgpService should check if this condition is met (sign + no encrypt + no ascii armor), and return an appropriate instance of OpenPgpError.

The assertion error is fine where it is I think, if there is ever a way our UI code calls SignEncryptOperation with these parameters, it's a bug and we *should* crash so we get the reports.
