### ISSUE TITLE
KeyserverSyncAdapterService: NullPointerException

### ISSUE THREAD

**Issue by dschuermann** [open-keychain/open-keychain#1655]
From Google Play developer console

Always Android 4.4

```
java.lang.RuntimeException: Unable to start service org.sufficientlysecure.keychain.service.KeyserverSyncAdapterService@21f63140 with null: java.lang.NullPointerException
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2759)
	at android.app.ActivityThread.access$2100(ActivityThread.java:138)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1333)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:149)
	at android.app.ActivityThread.main(ActivityThread.java:5061)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:788)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:604)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.NullPointerException
	at org.sufficientlysecure.keychain.service.KeyserverSyncAdapterService.onStartCommand(KeyserverSyncAdapterService.java:80)
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2742)
	... 10 more
```

**Comment by dschuermann** [comment]
@adithyaphilip can you look into this one?

**Comment by adithyaphilip** [comment]
Which release was this reported on? It was a known issue prior to 3.7 (https://github.com/open-keychain/open-keychain/issues/1573). The line number matches up with the cause of the error on 3.6.1 too (https://github.com/open-keychain/open-keychain/blob/v3.6.1/OpenKeychain/src/main/java/org/sufficientlysecure/keychain/service/KeyserverSyncAdapterService.java#L80). 
Was fixed with https://github.com/open-keychain/open-keychain/commit/c31f760110ffdf188c54f9a9fc0ae95463594279.

**Comment by Valodim** [comment]
I concur, this is probably misassigned

**Comment by dschuermann** [comment]
Looks like I filtered the bug reports in Google Play dev console wrong.
