### ISSUE TITLE
PassphraseDialogActivity: NullPointerException

### ISSUE THREAD

**Issue by dschuermann** [open-keychain/open-keychain#1656]
From Google Play developer console

```
java.lang.NullPointerException: Attempt to read from field 'org.sufficientlysecure.keychain.service.input.CryptoInputParcel org.sufficientlysecure.keychain.ui.PassphraseDialogActivity.mCryptoInputParcel' on a null object reference
	at org.sufficientlysecure.keychain.ui.PassphraseDialogActivity.access$300(PassphraseDialogActivity.java:75)
	at org.sufficientlysecure.keychain.ui.PassphraseDialogActivity$PassphraseDialogFragment$5$1.onPostExecute(PassphraseDialogActivity.java:481)
	at org.sufficientlysecure.keychain.ui.PassphraseDialogActivity$PassphraseDialogFragment$5$1.onPostExecute(PassphraseDialogActivity.java:435)
	at android.os.AsyncTask.finish(AsyncTask.java:632)
	at android.os.AsyncTask.access$600(AsyncTask.java:177)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:645)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5438)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:917)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:712)
```

**Comment by Valodim** [comment]
I think I fixed this along the way in 67b316155fbf09de45d39e42b07f6976031a4693, where I replaced the `getActivity()` call in question by keeping the required data in the fragment arguments (and a field)
