### ISSUE TITLE
`Unfortunately, OpenKeyChain has stopped` on importing revoked pub and secret key

### ISSUE THREAD

**Issue by MartiUK** [open-keychain/open-keychain#1660]
This may be related to #1447 

The .asc file I'm importing is formatted as:

```
-----BEGIN PGP PUBLIC KEY BLOCK-----
[snip]
-----END PGP PUBLIC KEY BLOCK-----
-----BEGIN PGP PRIVATE KEY BLOCK-----
[snip]
-----END PGP PUBLIC KEY BLOCK-----
```

**Comment by skorokithakis** [comment]
I'm getting this too, no revoked keys in my chain. I just can't import my keys at all. I also get the crash when importing just the private key, so it seems to somehow be the private key causing this. I currently can't import my private key into OKC at all.

**Comment by dschuermann** [comment]
I you have installed OpenKeychain from Google Play, please report the crash, so we can see the full stacktrace in the developer console.

The bug is unrelated to #1447

**Comment by skorokithakis** [comment]
I don't want to do that, as I don't know if it'll send you my raw private key. However, here's the stack trace:

~~~
02-18 16:57:16.048 6435-6435/org.sufficientlysecure.keychain.debug E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                     Process: org.sufficientlysecure.keychain.debug, PID: 6435
                                                                                     java.lang.IndexOutOfBoundsException: Invalid index 0, size is 0
                                                                                         at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
                                                                                         at java.util.ArrayList.get(ArrayList.java:308)
                                                                                         at org.sufficientlysecure.keychain.ui.adapter.ImportKeysAdapter.getView(ImportKeysAdapter.java:143)
                                                                                         at android.widget.AbsListView.obtainView(AbsListView.java:2346)
                                                                                         at android.widget.ListView.makeAndAddView(ListView.java:1876)
                                                                                         at android.widget.ListView.fillDown(ListView.java:702)
                                                                                         at android.widget.ListView.fillFromTop(ListView.java:763)
                                                                                         at android.widget.ListView.layoutChildren(ListView.java:1685)
                                                                                         at android.widget.AbsListView.onLayout(AbsListView.java:2148)
                                                                                         at android.view.View.layout(View.java:16630)
                                                                                         at android.view.ViewGroup.layout(ViewGroup.java:5437)
                                                                                         at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
                                                                                         at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
                                                                                         at android.view.View.layout(View.java:16630)
                                                                                         at android.view.ViewGroup.layout(ViewGroup.java:5437)
                                                                                         at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
                                                                                         at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
                                                                                         at android.view.View.layout(View.java:16630)
                                                                                         at android.view.ViewGroup.layout(ViewGroup.java:5437)
                                                                                         at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
                                                                                         at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
                                                                                         at android.view.View.layout(View.java:16630)
                                                                                         at android.view.ViewGroup.layout(ViewGroup.java:5437)
                                                                                         at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
                                                                                         at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1586)
                                                                                         at android.widget.LinearLayout.onLayout(LinearLayout.java:1495)
                                                                                         at android.view.View.layout(View.java:16630)
                                                                                         at android.view.ViewGroup.layout(ViewGroup.java:5437)
                                                                                         at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1079)
                                                                                         at android.view.View.layout(View.java:16630)
                                                                                         at android.view.ViewGroup.layout(ViewGroup.java:5437)
                                                                                         at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
                                                                                         at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
                                                                                         at android.view.View.layout(View.java:16630)
                                                                                         at android.view.ViewGroup.layout(ViewGroup.java:5437)
                                                                                         at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
                                                                                         at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
                                                                                         at android.view.View.layout(View.java:16630)
                                                                                         at android.view.ViewGroup.layout(ViewGroup.java:5437)
                                                                                         at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
                                                                                         at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
                                                                                         at android.view.View.layout(View.java:16630)
                                                                                         at android.view.ViewGroup.layout(ViewGroup.java:5437)
                                                                                         at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
                                                                                         at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1586)
                                                                                         at android.widget.LinearLayout.onLayout(LinearLayout.java:1495)
                                                                                         at android.view.View.layout(View.java:16630)
                                                                                         at android.view.ViewGroup.layout(ViewGroup.java:5437)
                                                                                         at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
                                                                                         at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
                                                                                         at com.android.internal.policy.PhoneWindow$DecorView.onLayout(PhoneWindow.java:2678)
                                                                                         at android.view.View.layout(View.java:16630)
                                                                                         at android.view.ViewGroup.layout(ViewGroup.java:5437)
                                                                                         at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2171)
                                                                                         at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1931)
                                                                                         at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1107)
                                                                                         at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6013)
                                                                                         at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
                                                                                         at android.view.Choreographer.doCallbacks(Choreographer.java:670)
                                                                                         at android.view.Choreographer.doFrame(Choreographer.java:606)
                                                                                         at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
                                                                                         at android.os.Handler.handleCallback(Handler.java:739)
                                                                                         at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                         at android.os.Looper.loop(Looper.java:148)
                                                                                     	at and
~~~

**Comment by Valodim** [comment]
Is your key available on public keyservers? If so, what's the key id? If not, can you send me the public part? (mailto look@my.amazin.horse)

**Comment by skorokithakis** [comment]
Yep, here:

https://pgp.mit.edu/pks/lookup?op=get&search=0x91DDF089422CEFA2

I have already imported this key (by doing a search), it's the private part that crashes.

**Comment by skorokithakis** [comment]
@Valodim here's what poking around reveals:

~~~
org.bouncycastle.openpgp.PGPException: cannot create cipher: Provider BC does not provide CAST5/OpenPGPCFB/NoPadding
~~~

**Comment by skorokithakis** [comment]
Apparently the fix for that error is to replace BouncyCastle with SpongyCastle:

https://stackoverflow.com/questions/24913313/bouncycastle-error

**Comment by dschuermann** [comment]
@skorolithakis what Version of OpenKeychain are you using?

**Comment by skorokithakis** [comment]
That was latest master, the one that crashes is latest play store version.

**Comment by dschuermann** [comment]
@skorokithakis what device and Android Version?

**Comment by skorokithakis** [comment]
Nexus 6P, 6.0.0

**Comment by dschuermann** [comment]
@skorokithakis The issue you encountered with current git master has now been fixed in https://github.com/open-keychain/open-keychain/commit/c9018e1844293eb2c47f642c5940531a3496dce5 . Many many thanks for reporting this, this problem has escaped my eyes when switching from Bouncy Castle to Spongy Castle!

**Comment by skorokithakis** [comment]
Fantastic! Will there be a release soon so I can begin using the app, or should I compile from source?

**Comment by dschuermann** [comment]
@skorokithakis Sry, maybe I wasn't clear enough. I only fixed the new bug with ``Provider BC does not provide CAST5/OpenPGPCFB/NoPadding``. But you can now try to re-compile from source and test again.

**Comment by skorokithakis** [comment]
No, that's what I meant, are you planning to make a release to the Play store with this fix soon, or should I compile my own? I'll test it and report back when I get home either way.

**Comment by dschuermann** [comment]
We have some other fixes and changes in the pipeline for the next release, so it will take some more days. Better compile on your own :P

**Comment by skorokithakis** [comment]
I'm afraid latest master still doesn't work (unless I did something wrong) :( Stack trace:

~~~
02-21 22:01:36.931 19904-19904/org.sufficientlysecure.keychain.debug E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                       Process: org.sufficientlysecure.keychain.debug, PID: 19904
                                                                                       java.lang.IndexOutOfBoundsException: Invalid index 0, size is 0
                                                                                           at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
                                                                                           at java.util.ArrayList.get(ArrayList.java:308)
                                                                                           at org.sufficientlysecure.keychain.ui.adapter.ImportKeysAdapter.getView(ImportKeysAdapter.java:143)
                                                                                           at android.widget.AbsListView.obtainView(AbsListView.java:2346)
                                                                                           at android.widget.ListView.makeAndAddView(ListView.java:1876)
                                                                                           at android.widget.ListView.fillDown(ListView.java:702)
                                                                                           at android.widget.ListView.fillFromTop(ListView.java:763)
                                                                                           at android.widget.ListView.layoutChildren(ListView.java:1685)
                                                                                           at android.widget.AbsListView.onLayout(AbsListView.java:2148)
                                                                                           at android.view.View.layout(View.java:16630)
                                                                                           at android.view.ViewGroup.layout(ViewGroup.java:5437)
                                                                                           at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
                                                                                           at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
                                                                                           at android.view.View.layout(View.java:16630)
                                                                                           at android.view.ViewGroup.layout(ViewGroup.java:5437)
                                                                                           at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
                                                                                           at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
                                                                                           at android.view.View.layout(View.java:16630)
                                                                                           at android.view.ViewGroup.layout(ViewGroup.java:5437)
                                                                                           at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
                                                                                           at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
                                                                                           at android.view.View.layout(View.java:16630)
                                                                                           at android.view.ViewGroup.layout(ViewGroup.java:5437)
                                                                                           at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
                                                                                           at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1586)
                                                                                           at android.widget.LinearLayout.onLayout(LinearLayout.java:1495)
                                                                                           at android.view.View.layout(View.java:16630)
                                                                                           at android.view.ViewGroup.layout(ViewGroup.java:5437)
                                                                                           at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1079)
                                                                                           at android.view.View.layout(View.java:16630)
                                                                                           at android.view.ViewGroup.layout(ViewGroup.java:5437)
                                                                                           at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
                                                                                           at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
                                                                                           at android.view.View.layout(View.java:16630)
                                                                                           at android.view.ViewGroup.layout(ViewGroup.java:5437)
                                                                                           at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
                                                                                           at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
                                                                                           at android.view.View.layout(View.java:16630)
                                                                                           at android.view.ViewGroup.layout(ViewGroup.java:5437)
                                                                                           at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
                                                                                           at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
                                                                                           at android.view.View.layout(View.java:16630)
                                                                                           at android.view.ViewGroup.layout(ViewGroup.java:5437)
                                                                                           at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
                                                                                           at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1586)
                                                                                           at android.widget.LinearLayout.onLayout(LinearLayout.java:1495)
                                                                                           at android.view.View.layout(View.java:16630)
                                                                                           at android.view.ViewGroup.layout(ViewGroup.java:5437)
                                                                                           at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
                                                                                           at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
                                                                                           at com.android.internal.policy.PhoneWindow$DecorView.onLayout(PhoneWindow.java:2678)
                                                                                           at android.view.View.layout(View.java:16630)
                                                                                           at android.view.ViewGroup.layout(ViewGroup.java:5437)
                                                                                           at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2171)
                                                                                           at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1931)
                                                                                           at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1107)
                                                                                           at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6013)
                                                                                           at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
                                                                                           at android.view.Choreographer.doCallbacks(Choreographer.java:670)
                                                                                           at android.view.Choreographer.doFrame(Choreographer.java:606)
                                                                                           at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
                                                                                           at android.os.Handler.handleCallback(Handler.java:739)
                                                                                           at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                           at android.os.Looper.loop(Looper.java:148)
                                                                                       	at an
~~~

**Comment by dschuermann** [comment]
@skorokithakis That's what I meant :P . I only fixed the new bug with ``Provider BC does not provide CAST5/OpenPGPCFB/NoPadding``. We still need to investigate this bug. If you like to help: Can you create a new private key in the same way you created the one that OpenKeychain currently refuses to import?

**Comment by skorokithakis** [comment]
Ah, given that this was generated twenty years ago, I rather doubt it :-( I think I used PGP version 2 or something.

**Comment by dschuermann** [comment]
@skorokithakis I know it's not a proper fix, but given that your master key is a DSA 1024 bit key, I advise you to create a new key with 2048 bit or 4096 bit RSA ;)

**Comment by skorokithakis** [comment]
Hmm, you may be right... Switching keys is going to be rough, but I just got a new Yubikey, so I might as well give it a shot. Thanks!

**Comment by Valodim** [comment]
did you ever extend the expiry of that key with gpg 1.X? if so, can you try exporting it with gpg 2.X and see if that works?

**Comment by skorokithakis** [comment]
If you mean me, I don't think I did, I think it was always non-expiring. I did export it with GPG 2, no dice.

**Comment by dschuermann** [comment]
Closing because we have no further information how to debug this.
