### ISSUE TITLE
Null pointer exception on private key import

### ISSUE THREAD

**Issue by gjedeer** [open-keychain/open-keychain#1668]
I was able to import one of my private keys from file, but not the other. Using 3.7.

```
build.board: smdk4x12
build.bootloader: N7100XXUFOB1
build.brand: samsung
build.cpu_abi: armeabi-v7a
build.cpu_abi2: armeabi
build.device: t03g
build.display: cm_n7100-userdebug 4.4.4 KTU84Q aa8aa93211 test-keys
build.fingerprint: samsung/t03gxx/t03g:4.3/JSS15J/N7100XXUENB2:user/release-keys
build.hardware: smdk4x12
build.host: cyanogenmod
build.id: KTU84Q
build.manufacturer: samsung
build.model: GT-N7100
build.product: t03gxx
build.radio: unknown
build.serial: 4df7ce886274cf6f
build.tags: test-keys
build.time: 1412767754000
build.type: userdebug
build.user: jenkins
version.codename: REL
version.incremental: aa8aa93211
version.release: 4.4.4
version.sdk_int: 19

01-10 11:52:05.960 E/AndroidRuntime(5081): FATAL EXCEPTION: Thread-320
01-10 11:52:05.960 E/AndroidRuntime(5081): Process: org.sufficientlysecure.keychain, PID: 5081
01-10 11:52:05.960 E/AndroidRuntime(5081): java.lang.NullPointerException
01-10 11:52:05.960 E/AndroidRuntime(5081): 	at org.spongycastle.openpgp.PGPPublicKey.<init>(PGPPublicKey.java:144)
01-10 11:52:05.960 E/AndroidRuntime(5081): 	at org.spongycastle.openpgp.PGPPublicKey.removeCert(PGPPublicKey.java:808)
01-10 11:52:05.960 E/AndroidRuntime(5081): 	at org.spongycastle.openpgp.PGPPublicKey.removeCertification(PGPPublicKey.java:801)
01-10 11:52:05.960 E/AndroidRuntime(5081): 	at org.sufficientlysecure.keychain.pgp.UncachedKeyRing.canonicalize(UncachedKeyRing.java:606)
01-10 11:52:05.960 E/AndroidRuntime(5081): 	at org.sufficientlysecure.keychain.pgp.UncachedKeyRing.canonicalize(UncachedKeyRing.java:271)
01-10 11:52:05.960 E/AndroidRuntime(5081): 	at org.sufficientlysecure.keychain.provider.ProviderHelper.saveSecretKeyRing(ProviderHelper.java:1046)
01-10 11:52:05.960 E/AndroidRuntime(5081): 	at org.sufficientlysecure.keychain.operations.ImportOperation.serialKeyRingImport(ImportOperation.java:271)
01-10 11:52:05.960 E/AndroidRuntime(5081): 	at org.sufficientlysecure.keychain.operations.ImportOperation.serialKeyRingImport(ImportOperation.java:112)
01-10 11:52:05.960 E/AndroidRuntime(5081): 	at org.sufficientlysecure.keychain.operations.ImportOperation.execute(ImportOperation.java:390)
01-10 11:52:05.960 E/AndroidRuntime(5081): 	at org.sufficientlysecure.keychain.operations.ImportOperation.execute(ImportOperation.java:83)
01-10 11:52:05.960 E/AndroidRuntime(5081): 	at org.sufficientlysecure.keychain.service.KeychainService$1.run(KeychainService.java:146)
01-10 11:52:05.960 E/AndroidRuntime(5081): 	at java.lang.Thread.run(Thread.java:841)
```

**Comment by dschuermann** [comment]
Is this key on a keyserver? Can you tell us the Key ID?

**Comment by gjedeer** [comment]
Sure, it's 4ED3D2B7 gdr@gdr.name

I have been importing the private part from a file on the phone.

**Comment by Valodim** [comment]
public key looks ok, but there's more I can look at. quick question though, do you know why the subkey C284C38544161BFB was created on 2010-12-24 but its subkey binding signature was created on 2014-11-12?

**Comment by gjedeer** [comment]
I have no idea, I've prolonged the expiration date of the key with gpg --edit-key, so maybe there's something I did wrong.

Should I try removing C284C38544161BFB (it's expired anyway) and importing again?

**Comment by Valodim** [comment]
Ah, the expiration thing. Your key is likely suffering from [this bug](https://www.openkeychain.org/faq/#importing-your-own-key-from-gnupg-fails). please try exporting it with a newer version of gpg and see if that works.

**Comment by gjedeer** [comment]
Thanks! That was it. Sent a small donation as a thank you.
