### ISSUE TITLE
IllegalStateException with ViewKeyKeybaseFragment and OrbotHelper

### ISSUE THREAD

**Issue by dschuermann** [open-keychain/open-keychain#1682]
From Google Play dev console

@adithyaphilip Can you look into this one? I think it's not that important since it is related to the keybase support which is an experimental feature, which actually needs more polishing in general...

v3.8.1
Android 6.0 
Nexus 6 (shamu)

```
java.lang.IllegalStateException: Can not perform this action inside of onLoadFinished
	at android.support.v4.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:1493)
	at android.support.v4.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1507)
	at android.support.v4.app.BackStackRecord.commitInternal(BackStackRecord.java:634)
	at android.support.v4.app.BackStackRecord.commit(BackStackRecord.java:613)
	at android.support.v4.app.DialogFragment.show(DialogFragment.java:139)
	at org.sufficientlysecure.keychain.util.orbot.OrbotHelper.putOrbotInRequiredState(OrbotHelper.java:326)
	at org.sufficientlysecure.keychain.util.orbot.OrbotHelper.putOrbotInRequiredState(OrbotHelper.java:374)
	at org.sufficientlysecure.keychain.ui.ViewKeyKeybaseFragment.startSearch(ViewKeyKeybaseFragment.java:206)
	at org.sufficientlysecure.keychain.ui.ViewKeyKeybaseFragment.onLoadFinished(ViewKeyKeybaseFragment.java:178)
	at org.sufficientlysecure.keychain.ui.ViewKeyKeybaseFragment.onLoadFinished(ViewKeyKeybaseFragment.java:64)
	at android.support.v4.app.LoaderManagerImpl$LoaderInfo.callOnLoadFinished(LoaderManager.java:476)
	at android.support.v4.app.LoaderManagerImpl$LoaderInfo.onLoadComplete(LoaderManager.java:444)
	at android.support.v4.content.Loader.deliverResult(Loader.java:126)
	at android.support.v4.content.CursorLoader.deliverResult(CursorLoader.java:105)
	at android.support.v4.content.CursorLoader.deliverResult(CursorLoader.java:37)
	at android.support.v4.content.AsyncTaskLoader.dispatchOnLoadComplete(AsyncTaskLoader.java:249)
	at android.support.v4.content.AsyncTaskLoader$LoadTask.onPostExecute(AsyncTaskLoader.java:77)
	at android.support.v4.content.ModernAsyncTask.finish(ModernAsyncTask.java:466)
	at android.support.v4.content.ModernAsyncTask.access$400(ModernAsyncTask.java:48)
	at android.support.v4.content.ModernAsyncTask$InternalHandler.handleMessage(ModernAsyncTask.java:483)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5417)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by adithyaphilip** [comment]
Yup, looking into it.

**Comment by dschuermann** [comment]
Maybe we could move the keybase code out of a special fragment and integrate it like the linked id card, could be more clean...
