### ISSUE TITLE
App crashes when importing exported keychain

### ISSUE THREAD

**Issue by sedrubal** [open-keychain/open-keychain#1684]
I exported my public keychain with `gpg2` and want to import it in OpenKeychain, but it  always crashes.

I think this is the relevant `adb logcat` output:

``` adb
01-14 00:17:49.887 21972 21972 D AndroidRuntime: Shutting down VM
01-14 00:17:49.888 21972 21972 E AndroidRuntime: FATAL EXCEPTION: main
01-14 00:17:49.888 21972 21972 E AndroidRuntime: Process: org.sufficientlysecure.keychain, PID: 21972
01-14 00:17:49.888 21972 21972 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object android.support.v4.util.LongSparseArray.get(long)' on a null object reference
01-14 00:17:49.888 21972 21972 E AndroidRuntime:        at org.sufficientlysecure.keychain.ui.ImportKeysListFragment$1.next(ImportKeysListFragment.java:118)
01-14 00:17:49.888 21972 21972 E AndroidRuntime:        at org.sufficientlysecure.keychain.ui.ImportKeysListFragment$1.next(ImportKeysListFragment.java:103)
01-14 00:17:49.888 21972 21972 E AndroidRuntime:        at org.sufficientlysecure.keychain.util.ParcelableFileCache.writeCache(ParcelableFileCache.java:77)
01-14 00:17:49.888 21972 21972 E AndroidRuntime:        at org.sufficientlysecure.keychain.util.ParcelableFileCache.writeCache(ParcelableFileCache.java:56)
01-14 00:17:49.888 21972 21972 E AndroidRuntime:        at org.sufficientlysecure.keychain.ui.ImportKeysActivity.importSelectedKeys(ImportKeysActivity.java:373)
01-14 00:17:49.888 21972 21972 E AndroidRuntime:        at org.sufficientlysecure.keychain.ui.ImportKeysActivity.access$000(ImportKeysActivity.java:51)
01-14 00:17:49.888 21972 21972 E AndroidRuntime:        at org.sufficientlysecure.keychain.ui.ImportKeysActivity$1.onClick(ImportKeysActivity.java:106)
01-14 00:17:49.888 21972 21972 E AndroidRuntime:        at android.view.View.performClick(View.java:5204)
01-14 00:17:49.888 21972 21972 E AndroidRuntime:        at android.view.View$PerformClick.run(View.java:21153)
01-14 00:17:49.888 21972 21972 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:739)
01-14 00:17:49.888 21972 21972 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:95)
01-14 00:17:49.888 21972 21972 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:148)
01-14 00:17:49.888 21972 21972 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:5417)
01-14 00:17:49.888 21972 21972 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
01-14 00:17:49.888 21972 21972 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
01-14 00:17:49.888 21972 21972 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
01-14 00:17:49.889   803  2958 W ActivityManager:   Force finishing activity org.sufficientlysecure.keychain/.ui.ImportKeysActivity
01-14 00:17:49.929   803  1180 I OpenGLRenderer: Initialized EGL, version 1.4
01-14 00:17:50.392   803   872 W ActivityManager: Activity pause timeout for ActivityRecord{3d845f2 u0 org.sufficientlysecure.keychain/.ui.ImportKeysActivity t331 f}
```

And this is an animation :sunglasses: 

![anim](https://cloud.githubusercontent.com/assets/5571650/12311067/f3142b90-ba54-11e5-8ec4-3ac8ab5f6f0b.gif)

Additionally there is a very confusing error message ;)

**Comment by skorokithakis** [comment]
Seems related to #1660. I exported my key, I try to open it in OKC, and it says "no valid keys found". If I open it in my file manager and select "decrypt with OKC", it asks me for the encryption key, I type it in, then it tells me "import key", at which point it crashes.

If I don't encrypt the key, #1660 happens.

**Comment by Valodim** [comment]
Sorry for the lack of reply, we're fairly busy with other stuff at the moment. We'll get back to this issue.

So the crash happens during import but after the keys are already listed, right?

**Comment by sedrubal** [comment]
Yes, that's right. It lists some keys and when tabbing "Import Selected Keys" it crashes (sorry, the gif is not as helpful as I thought ;) )

But I think I found the problem. I exported my keys from my laptop using

```shell
gpg2 --export --armor > keys.asc
```

The result is something like this (one large block):

```pgp
-----BEGIN PGP PUBLIC KEY BLOCK-----
wrJULLVuzTnlRlHfjTNznwmutsWKrHzgjetDjtPPbbkgmYErLoVLinwqxyyHDUAaP
[...]
JZnFUIzRTIejOdFmCcXFavMxYFkyqtipDmYeSANvIfxjUUBIbNqWwlVaLkAhpuqJo
-----END PGP PUBLIC KEY BLOCK-----
```

Instead of something like this (one block for each key):

```pgp
-----BEGIN PGP PUBLIC KEY BLOCK-----
wrJULLVuzTnlRlHfjTNznwmutsWKrHzgjetDjtPPbbkgmYErLoVLinwqxyyHDUAaP
[...]
JZnFUIzRTIejOdFmCcXFavMxYFkyqtipDmYeSANvIfxjUUBIbNqWwlVaLkAhpuqJo
-----END PGP PUBLIC KEY BLOCK-----

-----BEGIN PGP PUBLIC KEY BLOCK-----
nOzuQyAZSadIXFnoscgrhqemTygsiyqXTHavMCAyXQmsssNWSemxNKkgkyMTLKhwU
[...]
JZnFUIzRTIejOdFmCcXFavMxYFkyqtipDmYeSANvIfxjUUBIbNqWwlVaLkAhpuqJo
-----END PGP PUBLIC KEY BLOCK-----

-----BEGIN PGP PUBLIC KEY BLOCK-----
wrJULLVuzTnlRlHfjTNznwmutsWKrHzgjetDjtPPbbkgmYErLoVLinwqxyyHDUAaP
[...]
ZMmUnBNAqgBigmmVzQLnBLvpzgqqaHUsFUiWPWhwUEnkMVTUVeBXAwfVdAvtLXvZm
-----END PGP PUBLIC KEY BLOCK-----
```

How can I export something like the second one?

**Comment by skorokithakis** [comment]
Specify the key's email address, although I doubt that's it. I only exported one key and it still crashed.

**Comment by sedrubal** [comment]
Oh with this export command, it works completely as it should (even if it takes even more time to process...)

```bash
gpg2 --list-keys | grep ^pub | grep -v "expired" | sed 's/\// /g' | awk '{print $3}' | xargs -I '{}' gpg2 --export -a '{}' >> keys.asc
```

It lists all keys, takes every line wich contains pub, removes all expired keys, gets the key id and exports it by appending it to keys.asc.

I tested it without removing expired keys. Then the same happens as described above. So I think, this is caused by **expired keys**. Maybe it's related to #1660?

**Comment by dschuermann** [comment]
Can you re-try with version 4.3 and report back? If this still persists I will then re-open the issue.
