### ISSUE TITLE
Lookup missing key under tor results in loop

### ISSUE THREAD

**Issue by sedrubal** [open-keychain/open-keychain#1685]
I want to lookup a missing key from k9 Mail with OpenKeychain and I'm using tor (configured in OpenKeychain settings), but this results in following loop, even if tor is running and is connected:

![anim](https://cloud.githubusercontent.com/assets/5571650/12311269/5c574168-ba56-11e5-8cb7-60a0fb6d2530.gif)

This might be a useful `adb logcat`:

``` adb
01-14 00:34:11.084   803  2957 W InputMethodManagerService: Window already focused, ignoring focus gain of: com.android.internal.view.IInputMethodClient$Stub$Proxy@6ee59c6 attribute=null, token = android.os.BinderProxy@c907cf1
01-14 00:34:11.092 25198 25198 W pidof   : type=1400 audit(0.0:103385): avc: denied { search } for name="1" dev="proc" ino=6098 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:r:init:s0 tclass=dir permissive=0
01-14 00:34:11.092 25198 25198 W pidof   : type=1400 audit(0.0:103386): avc: denied { search } for name="2" dev="proc" ino=10655 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:r:kernel:s0 tclass=dir permissive=0
01-14 00:34:11.092 25198 25198 W pidof   : type=1400 audit(0.0:103387): avc: denied { search } for name="3" dev="proc" ino=10656 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:r:kernel:s0 tclass=dir permissive=0
01-14 00:34:11.092 25198 25198 W pidof   : type=1400 audit(0.0:103388): avc: denied { search } for name="7" dev="proc" ino=10660 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:r:kernel:s0 tclass=dir permissive=0
01-14 00:34:11.092 25198 25198 W pidof   : type=1400 audit(0.0:103389): avc: denied { search } for name="8" dev="proc" ino=10661 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:r:kernel:s0 tclass=dir permissive=0
01-14 00:34:11.092 25198 25198 W pidof   : type=1400 audit(0.0:103390): avc: denied { search } for name="13" dev="proc" ino=10662 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:r:kernel:s0 tclass=dir permissive=0
01-14 00:34:11.092 25198 25198 W pidof   : type=1400 audit(0.0:103391): avc: denied { search } for name="14" dev="proc" ino=10663 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:r:kernel:s0 tclass=dir permissive=0
01-14 00:34:11.092 25198 25198 W pidof   : type=1400 audit(0.0:103392): avc: denied { search } for name="18" dev="proc" ino=10666 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:r:kernel:s0 tclass=dir permissive=0
01-14 00:34:11.092 25198 25198 W pidof   : type=1400 audit(0.0:103393): avc: denied { search } for name="19" dev="proc" ino=10667 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:r:kernel:s0 tclass=dir permissive=0
01-14 00:34:11.092 25198 25198 W pidof   : type=1400 audit(0.0:103394): avc: denied { search } for name="20" dev="proc" ino=10668 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:r:kernel:s0 tclass=dir permissive=0
01-14 00:34:11.092 25198 25198 W pidof   : type=1400 audit(0.0:103395): avc: denied { search } for name="22" dev="proc" ino=10670 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:r:kernel:s0 tclass=dir permissive=0
01-14 00:34:11.092 25198 25198 W pidof   : type=1400 audit(0.0:103396): avc: denied { search } for name="23" dev="proc" ino=10671 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:r:kernel:s0 tclass=dir permissive=0
01-14 00:34:11.092 25198 25198 W pidof   : type=1400 audit(0.0:103397): avc: denied { search } for name="24" dev="proc" ino=10672 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:r:kernel:s0 tclass=dir permissive=0
01-14 00:34:11.092 25198 25198 W pidof   : type=1400 audit(0.0:103398): avc: denied { search } for name="25" dev="proc" ino=10673 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:r:kernel:s0 tclass=dir permissive=0
01-14 00:34:11.092 25198 25198 W pidof   : type=1400 audit(0.0:103399): avc: denied { search } for name="26" dev="proc" ino=10674 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:r:kernel:s0 tclass=dir permissive=0
01-14 00:34:11.092 25198 25198 W pidof   : type=1400 audit(0.0:103400): avc: denied { search } for name="27" dev="proc" ino=10675 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:r:kernel:s0 tclass=dir permissive=0
01-14 00:34:11.092 25198 25198 W pidof   : type=1400 audit(0.0:103401): avc: denied { search } for name="28" dev="proc" ino=10676 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:r:kernel:s0 tclass=dir permissive=0
01-14 00:34:11.092 25198 25198 W pidof   : type=1400 audit(0.0:103402): avc: denied { search } for name="29" dev="proc" ino=10677 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:r:kernel:s0 tclass=dir permissive=0
01-14 00:34:11.092 25198 25198 W pidof   : type=1400 audit(0.0:103403): avc: denied { search } for name="30" dev="proc" ino=10678 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:r:kernel:s0 tclass=dir permissive=0
01-14 00:34:11.092 25198 25198 W pidof   : type=1400 audit(0.0:103404): avc: denied { search } for name="31" dev="proc" ino=10679 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:r:kernel:s0 tclass=dir permissive=0
01-14 00:34:11.118 23533 23839 E TorServiceUtils: unable to parse process pid: 332 3260 3289 3345 3367 3464 3516 3649 3811 4038 4066 4602 4707 4818 4853 5077 17927 17997 18348 18501 18668 18833 18856 21737 22087 23506 23533 23563 23583 23798 24956 25133 25167 25175 25179 25198 26567 27269 27299 31480
01-14 00:34:11.118 23533 23839 E TorServiceUtils: java.lang.NumberFormatException: Invalid int: "332 3260 3289 3345 3367 3464 3516 3649 3811 4038 4066 4602 4707 4818 4853 5077 17927 17997 18348 18501 18668 18833 18856 21737 22087 23506 23533 23563 23583 23798 24956 25133 25167 25175 25179 25198 26567 27269 27299 31480"
01-14 00:34:11.118 23533 23839 E TorServiceUtils:       at java.lang.Integer.invalidInt(Integer.java:138)
01-14 00:34:11.118 23533 23839 E TorServiceUtils:       at java.lang.Integer.parse(Integer.java:410)
01-14 00:34:11.118 23533 23839 E TorServiceUtils:       at java.lang.Integer.parseInt(Integer.java:367)
01-14 00:34:11.118 23533 23839 E TorServiceUtils:       at java.lang.Integer.parseInt(Integer.java:334)
01-14 00:34:11.118 23533 23839 E TorServiceUtils:       at org.sufficientlysecure.keychain.util.orbot.TorServiceUtils.findProcessIdWithPidOf(TorServiceUtils.java:116)
01-14 00:34:11.118 23533 23839 E TorServiceUtils:       at org.sufficientlysecure.keychain.util.orbot.TorServiceUtils.findProcessId(TorServiceUtils.java:78)
01-14 00:34:11.118 23533 23839 E TorServiceUtils:       at org.sufficientlysecure.keychain.util.orbot.OrbotHelper.isOrbotRunning(OrbotHelper.java:154)
01-14 00:34:11.118 23533 23839 E TorServiceUtils:       at org.sufficientlysecure.keychain.util.orbot.OrbotHelper.isOrbotInRequiredState(OrbotHelper.java:287)
01-14 00:34:11.118 23533 23839 E TorServiceUtils:       at org.sufficientlysecure.keychain.ui.adapter.ImportKeysListCloudLoader.queryServer(ImportKeysListCloudLoader.java:119)
01-14 00:34:11.118 23533 23839 E TorServiceUtils:       at org.sufficientlysecure.keychain.ui.adapter.ImportKeysListCloudLoader.loadInBackground(ImportKeysListCloudLoader.java:82)
01-14 00:34:11.118 23533 23839 E TorServiceUtils:       at org.sufficientlysecure.keychain.ui.adapter.ImportKeysListCloudLoader.loadInBackground(ImportKeysListCloudLoader.java:39)
01-14 00:34:11.118 23533 23839 E TorServiceUtils:       at android.support.v4.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:296)
01-14 00:34:11.118 23533 23839 E TorServiceUtils:       at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:54)
01-14 00:34:11.118 23533 23839 E TorServiceUtils:       at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:42)
01-14 00:34:11.118 23533 23839 E TorServiceUtils:       at android.support.v4.content.ModernAsyncTask$2.call(ModernAsyncTask.java:128)
01-14 00:34:11.118 23533 23839 E TorServiceUtils:       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
01-14 00:34:11.118 23533 23839 E TorServiceUtils:       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
01-14 00:34:11.118 23533 23839 E TorServiceUtils:       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
01-14 00:34:11.118 23533 23839 E TorServiceUtils:       at java.lang.Thread.run(Thread.java:818)
01-14 00:34:11.278 23533 23533 E TorServiceUtils: unable to parse process pid: 332 3260 3289 3345 3367 3464 3516 3649 3811 4038 4066 4602 4707 4818 4853 5077 17927 17997 18348 18501 18668 18833 18856 21737 22087 23506 23533 23563 23583 23798 24956 25133 25167 25175 25179 25200 26567 27269 27299 31480
01-14 00:34:11.278 23533 23533 E TorServiceUtils: java.lang.NumberFormatException: Invalid int: "332 3260 3289 3345 3367 3464 3516 3649 3811 4038 4066 4602 4707 4818 4853 5077 17927 17997 18348 18501 18668 18833 18856 21737 22087 23506 23533 23563 23583 23798 24956 25133 25167 25175 25179 25200 26567 27269 27299 31480"
01-14 00:34:11.278 23533 23533 E TorServiceUtils:       at java.lang.Integer.invalidInt(Integer.java:138)
01-14 00:34:11.278 23533 23533 E TorServiceUtils:       at java.lang.Integer.parse(Integer.java:410)
01-14 00:34:11.278 23533 23533 E TorServiceUtils:       at java.lang.Integer.parseInt(Integer.java:367)
01-14 00:34:11.278 23533 23533 E TorServiceUtils:       at java.lang.Integer.parseInt(Integer.java:334)
01-14 00:34:11.278 23533 23533 E TorServiceUtils:       at org.sufficientlysecure.keychain.util.orbot.TorServiceUtils.findProcessIdWithPidOf(TorServiceUtils.java:116)
01-14 00:34:11.278 23533 23533 E TorServiceUtils:       at org.sufficientlysecure.keychain.util.orbot.TorServiceUtils.findProcessId(TorServiceUtils.java:78)
01-14 00:34:11.278 23533 23533 E TorServiceUtils:       at org.sufficientlysecure.keychain.util.orbot.OrbotHelper.isOrbotRunning(OrbotHelper.java:154)
01-14 00:34:11.278 23533 23533 E TorServiceUtils:       at org.sufficientlysecure.keychain.util.orbot.OrbotHelper.putOrbotInRequiredState(OrbotHelper.java:332)
01-14 00:34:11.278 23533 23533 E TorServiceUtils:       at org.sufficientlysecure.keychain.util.orbot.OrbotHelper.putOrbotInRequiredState(OrbotHelper.java:374)
01-14 00:34:11.278 23533 23533 E TorServiceUtils:       at org.sufficientlysecure.keychain.ui.ImportKeysListFragment$3.run(ImportKeysListFragment.java:457)
01-14 00:34:11.278 23533 23533 E TorServiceUtils:       at android.os.Handler.handleCallback(Handler.java:739)
01-14 00:34:11.278 23533 23533 E TorServiceUtils:       at android.os.Handler.dispatchMessage(Handler.java:95)
01-14 00:34:11.278 23533 23533 E TorServiceUtils:       at android.os.Looper.loop(Looper.java:148)
01-14 00:34:11.278 23533 23533 E TorServiceUtils:       at android.app.ActivityThread.main(ActivityThread.java:5417)
01-14 00:34:11.278 23533 23533 E TorServiceUtils:       at java.lang.reflect.Method.invoke(Native Method)
01-14 00:34:11.278 23533 23533 E TorServiceUtils:       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
01-14 00:34:11.278 23533 23533 E TorServiceUtils:       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by dschuermann** [comment]
@sedrubal What Android rom and version are you using?

It looks like Tor's PID could not be read from command line. While I think in general this is a bad API design by Orbot, we should gracefully show an error when this happens instead of looping endlessly.

**Comment by sedrubal** [comment]
Sorry: Android `6.0.1`, OmniRom `6.0.1`

Zou're right. I'm no Android developer but for users Orbot looks very messy and bad. But other apps can use tor, too...

**Comment by dschuermann** [comment]
@sedrubal Can you reproduce this with the newest OpenKeychain version 4.2.2?

**Comment by sedrubal** [comment]
No I can't. It seems to be fixed. Thank you :+1:

**Comment by dschuermann** [comment]
great
