### ISSUE TITLE
crash on FileNotFoundException in ImportKeysListLoader

### ISSUE THREAD

**Issue by Valodim** [open-keychain/open-keychain#1688]
```
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.io.InputStream org.sufficientlysecure.keychain.util.InputData.getInputStream()' on a null object reference
	at org.sufficientlysecure.keychain.ui.adapter.ImportKeysListLoader.generateListOfKeyrings(ImportKeysListLoader.java:111)
	at org.sufficientlysecure.keychain.ui.adapter.ImportKeysListLoader.loadInBackground(ImportKeysListLoader.java:77)
	at org.sufficientlysecure.keychain.ui.adapter.ImportKeysListLoader.loadInBackground(ImportKeysListLoader.java:45)
```

From a quick glance, `getInputData` returns null on a FileNotFoundException which simply isn't handled

**Comment by Valodim** [comment]
had this lying around for a while but forgot to push
