### ISSUE TITLE
Refresh of my own public key fails

### ISSUE THREAD

**Issue by jovandeginste** [open-keychain/open-keychain#1707]
I'm unsure if there is something wrong with my keypair, or with openkeychain. I search the issues, but couldn't find a solution so far.

When I refresh my own key (or all keys) I get an error (Dutch):

```
[START] Bezig met importeren van sleutel
 [DEBUG] Sleutelserver hkps://hkps.pool.sks-keyservers.net wordt gebruikt
  [INFO] Bezig met ophalen van sleutelserver: 0xe40adc64193e10fd
 [ERROR] Importeren mislukt!
```

However, I can use it for everything else, I can trust people, encrypt data, etc. How can I see more details about the error?

**Comment by adithyaphilip** [comment]
Stacktrace on downloading `0xe40adc64193e10fd`
```
Encountered bad key on import!
org.sufficientlysecure.keychain.pgp.exception.PgpGeneralException: Expected single keyring in stream, found at least two
at org.sufficientlysecure.keychain.pgp.UncachedKeyRing.decodeFromData(UncachedKeyRing.java:153)
at org.sufficientlysecure.keychain.operations.ImportOperation.serialKeyRingImport(ImportOperation.java:209)
at org.sufficientlysecure.keychain.operations.ImportOperation.access$000(ImportOperation.java:84)
at org.sufficientlysecure.keychain.operations.ImportOperation$1.call(ImportOperation.java:490)
at org.sufficientlysecure.keychain.operations.ImportOperation$1.call(ImportOperation.java:478)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
at java.lang.Thread.run(Thread.java:818)
```

**Comment by jovandeginste** [comment]
Any context? Is my key the problem, or an issue with the code?

**Comment by Valodim** [comment]
wow uh, this is a really weird case. can you tell us what software you used to create or ever modify this key? gpg, keybase, openkeychain, etc?

**Comment by jovandeginste** [comment]
By now, all three of those. I was testing stuff like creating subkeys, merging keys. Sadly, I'm far from an expert on gpg so I will accept it if you would tell me my key is broken... I could not find any other place to 'validate' my key, and gpg, mailvelope, open-keychain, eyaml, keybase all have no issue to _use_ it. Only open-keychain is telling me something is wrong (with the public part?)

**Comment by Valodim** [comment]
what did you do to "merge" keys?

**Comment by jovandeginste** [comment]
I'm not behind my computer now, can't be really specific. Also, this happened around July 2015, so memory is a bit hazy... I think I failed and thus restored a backup of my key (without publishing anything).

This was the guide I followed: http://security.stackexchange.com/a/62480

**Comment by Valodim** [comment]
Yes, that wall of text explains it. And holy moly, that is a completely unreasonable thing to do with your key, which introduces several assumptions making everyone's life harder. I'm just glad it happened "by force" and not accidentally.

In short, you appended your master key as a subkey to a different master key, so now a search on keyservers for your key id brings up both of those keyblocks - one where that key is the master key, one where it's a subkey. This is a situation which doesn't "naturally" occur, and the problem is that OpenKeychain has no way to tell which one to actually use in all situations.

Either way, if your key isn't very valuable to you, I suggest you create a new one and move on. We might try and handle this differently to be more "liberal in what we accept", but whatever decision we make which of these keys to use will always be guesswork, which might work for your case but not for others or the other way around.

**Comment by jovandeginste** [comment]
Like I said, I was experimenting :-)

I don't expect software to work with all (if any) edge cases, however I was not certain this was the case. 

I am not particularly attached to this key, but I need it for some things. This means obviously I will convert those things to use a new key...! Until this is done, I'm kinda attached ;-)

Thanks for feedback! I will close the issue. Unless you plan to follow up on this edge case - then feel free to open it again...

**Comment by Valodim** [comment]
I would propose we check all keys and pick the first which has the correct key id for a master key, or the first which has it as a subkey id if none exists with a master key id.

**Comment by dschuermann** [comment]
@Valodim sounds like the right approach.

**Comment by AlexFJW** [comment]
Just for confirmation, this is approach essentially checks each keyring's master key if they match with the key id(or fingerprint) used to fetch it. And, if none of the keyrings fit the bill, we examine all subkeys in each keyring, and pick the first keyring which contains a subkey that has the particular key id?

I think Valodim's comment answers this quite clearly but I'm trying to pick out the gaps in my understanding with respect to PGP & open-keychain's project structure so do pardon the question. :)
