### ISSUE TITLE
ArrayIndexOutOfBoundsException in BaseSecurityTokenNfcActivity.nfcPutKey

### ISSUE THREAD

**Issue by dschuermann** [open-keychain/open-keychain#1709]
Got this while testing https://github.com/open-keychain/open-keychain/pull/1705 but I think it's unrelated. I created a new key and took of the YubiKey NEO while the key was being transmitted to interrupt the process.

```
 18155         AndroidRuntime  E  FATAL EXCEPTION: AsyncTask #3
 18155         AndroidRuntime  E  Process: org.sufficientlysecure.keychain.debug, PID: 18155
 18155         AndroidRuntime  E  java.lang.RuntimeException: An error occured while executing doInBackground()
 18155         AndroidRuntime  E  at android.os.AsyncTask$3.done(AsyncTask.java:304)
 18155         AndroidRuntime  E  at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
 18155         AndroidRuntime  E  at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
 18155         AndroidRuntime  E  at java.util.concurrent.FutureTask.run(FutureTask.java:242)
 18155         AndroidRuntime  E  at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
 18155         AndroidRuntime  E  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
 18155         AndroidRuntime  E  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
 18155         AndroidRuntime  E  at java.lang.Thread.run(Thread.java:818)
 18155         AndroidRuntime  E  Caused by: java.lang.ArrayIndexOutOfBoundsException: src.length=127 srcPos=-1 dst.length=934 dstPos=550 length=128
 18155         AndroidRuntime  E  at java.lang.System.arraycopy(Native Method)
 18155         AndroidRuntime  E  at org.sufficientlysecure.keychain.ui.base.BaseSecurityTokenNfcActivity.nfcPutKey(BaseSecurityTokenNfcActivity.java:900)
 18155         AndroidRuntime  E  at org.sufficientlysecure.keychain.ui.SecurityTokenOperationActivity.doNfcInBackground(SecurityTokenOperationActivity.java:226)
 18155         AndroidRuntime  E  at org.sufficientlysecure.keychain.ui.base.BaseSecurityTokenNfcActivity.handleTagDiscovered(BaseSecurityTokenNfcActivity.java:450)
 18155         AndroidRuntime  E  at org.sufficientlysecure.keychain.ui.base.BaseSecurityTokenNfcActivity$1.doInBackground(BaseSecurityTokenNfcActivity.java:168)
 18155         AndroidRuntime  E  at org.sufficientlysecure.keychain.ui.base.BaseSecurityTokenNfcActivity$1.doInBackground(BaseSecurityTokenNfcActivity.java:158)
 18155         AndroidRuntime  E  at android.os.AsyncTask$2.call(AsyncTask.java:292)
 18155         AndroidRuntime  E  at java.util.concurrent.FutureTask.run(FutureTask.java:237)
 18155         AndroidRuntime  E  ... 4 more
```

**Comment by Franzaine** [comment]
@petter-fidesmo do you know anything about this?

**Comment by dschuermann** [comment]
haven't encountered this since... closing
