### ISSUE TITLE
NullPointerException in ImportKeysListFragment.checkAndRequestReadPermission

### ISSUE THREAD

**Issue by dschuermann** [open-keychain/open-keychain#1766]
Looks like a regression bug.

```
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.net.Uri.getScheme()' on a null object reference
	at org.sufficientlysecure.keychain.ui.ImportKeysListFragment.checkAndRequestReadPermission(ImportKeysListFragment.java:271)
	at org.sufficientlysecure.keychain.ui.ImportKeysListFragment.loadNew(ImportKeysListFragment.java:338)
	at org.sufficientlysecure.keychain.ui.ImportKeysActivity.loadCallback(ImportKeysActivity.java:331)
	at org.sufficientlysecure.keychain.ui.ImportKeysFileFragment$2.onClick(ImportKeysFileFragment.java:89)
	at android.view.View.performClick(View.java:4803)
	at android.view.View$PerformClick.run(View.java:19981)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5430)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:913)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:706)
```

**Comment by themouli** [comment]
Hey @dschuermann, can you help me reproduce this?

**Comment by dschuermann** [comment]
No, it's from the automatic crash reports from Google Play

**Comment by themouli** [comment]
Will a null check be sufficient for this ?

**Comment by 007durgesh219** [comment]
This is because it will try to get file reading permission for android 6. But because we copied key from clipboard datauri will be null ImportKeyFileFragment.java:89 
```
mImportActivity.loadCallback(new ImportKeysListFragment.BytesLoaderState(sendText.getBytes(), null));
```
But we don't need file reading in case key is copied from the clipboard. So, Just checking for null will be fine
I am able to reproduce and fix it. Please see #1769

**Comment by runnerway** [comment]
@007durgesh219 Yes this is the reason. 

I was writing the same when i saw your post.
Checking for the null is enough. :)
