### ISSUE TITLE
app crash on mi4i

### ISSUE THREAD

**Issue by trims** [open-keychain/open-keychain#1806]
hi... it's always crash everytime i tried to encrypt a file on xiaomi mi4i (mui 7.1)
any idea or workaround?

**Comment by Valodim** [comment]
Hi, thanks for your bug report!

I can't find a matching bug report in the play store developer console, did you report this crash? If you didn't, please do as it will provide us with helpful information to get this fixed :+1:

**Comment by trims** [comment]
i've just sent a report for this issue

thank you

**Comment by Valodim** [comment]
```
android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.CREATE_DOCUMENT cat=[android.intent.category.OPENABLE] typ=*/* (has extras) }
	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1765)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1485)
	at android.app.Activity.startActivityForResult(Activity.java:3787)
	at android.support.v4.app.ActivityCompatJB.startActivityForResult(ActivityCompatJB.java:30)
	at android.support.v4.app.ActivityCompat.startActivityForResult(ActivityCompat.java:162)
	at android.support.v4.app.FragmentActivity.startActivityFromFragment(FragmentActivity.java:925)
	at android.support.v4.app.FragmentActivity$HostCallbacks.onStartActivityFromFragment(FragmentActivity.java:1008)
	at android.support.v4.app.Fragment.startActivityForResult(Fragment.java:940)
	at android.support.v4.app.Fragment.startActivityForResult(Fragment.java:929)
	at org.sufficientlysecure.keychain.util.FileHelper.saveDocument(FileHelper.java:98)
	at org.sufficientlysecure.keychain.util.FileHelper.saveDocument(FileHelper.java:86)
	at org.sufficientlysecure.keychain.ui.EncryptFilesFragment.showOutputFileDialog(EncryptFilesFragment.java:325)
	at org.sufficientlysecure.keychain.ui.EncryptFilesFragment.prepareOutputStreams(EncryptFilesFragment.java:557)
	at org.sufficientlysecure.keychain.ui.EncryptFilesFragment.createOperationInput(EncryptFilesFragment.java:601)
	at org.sufficientlysecure.keychain.ui.EncryptFilesFragment.createOperationInput(EncryptFilesFragment.java:81)
	at org.sufficientlysecure.keychain.ui.base.CryptoOperationHelper.cryptoOperation(CryptoOperationHelper.java:271)
	at org.sufficientlysecure.keychain.ui.base.CryptoOperationFragment.cryptoOperation(CryptoOperationFragment.java:89)
	at org.sufficientlysecure.keychain.ui.EncryptFilesFragment.onOptionsItemSelected(EncryptFilesFragment.java:345)
	at android.support.v4.app.Fragment.performOptionsItemSelected(Fragment.java:2085)
	at android.support.v4.app.FragmentManagerImpl.dispatchOptionsItemSelected(FragmentManager.java:2163)
	at android.support.v4.app.FragmentController.dispatchOptionsItemSelected(FragmentController.java:304)
	at android.support.v4.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:410)
	at android.support.v7.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:167)
	at android.support.v7.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:100)
	at android.support.v7.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:100)
	at android.support.v7.app.ToolbarActionBar$2.onMenuItemClick(ToolbarActionBar.java:69)
	at android.support.v7.widget.Toolbar$1.onMenuItemClick(Toolbar.java:169)
	at android.support.v7.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(ActionMenuView.java:760)
	at android.support.v7.view.menu.f.dispatchMenuItemSelected(MenuBuilder.java:811)
	at android.support.v7.view.menu.h.a(MenuItemImpl.java:152)
	at android.support.v7.view.menu.f.performItemAction(MenuBuilder.java:958)
	at android.support.v7.view.menu.f.performItemAction(MenuBuilder.java:948)
	at android.support.v7.widget.ActionMenuView.invokeItem(ActionMenuView.java:618)
	at android.support.v7.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:139)
	at android.view.View.performClick(View.java:4759)
	at android.view.View$PerformClick.run(View.java:19770)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5234)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:909)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:704)
```

**Comment by 007durgesh219** [comment]
Might be related to [this one](http://stackoverflow.com/questions/21045091/no-activity-found-to-handle-intent-android-intent-action-open-document)

**Comment by Valodim** [comment]
It's not, we do set that mime type. I suspect this particular vendor breaks the Android `CREATE_DOCUMENT` workflow..

**Comment by Frouk** [comment]
I believe it's related to #1625
This quickfix fixed it https://github.com/open-keychain/open-keychain/pull/1740 but was a hackish temporarily solution,so i closed the PR.

**Comment by trims** [comment]
hi all,

today i just received an update for mui (7.2) and this issue seems has been gone.
we can close this issue now.

thank you :)
