### ISSUE TITLE
crash with MaskedEditText

### ISSUE THREAD

**Issue by Valodim** [open-keychain/open-keychain#1809]
```
java.lang.StringIndexOutOfBoundsException: length=29; index=72
	at java.lang.String.charAt(Native Method)
	at com.github.pinball83.maskededittext.MaskedEditText$MaskedInputFilter.filter(MaskedEditText.java:349)
	at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:504)
	at android.text.SpannableStringBuilder.delete(SpannableStringBuilder.java:225)
	at android.text.SpannableStringBuilder.delete(SpannableStringBuilder.java:34)
	at android.text.method.BaseKeyListener.backspaceOrForwardDelete(BaseKeyListener.java:106)
	at android.text.method.BaseKeyListener.backspace(BaseKeyListener.java:51)
	at android.text.method.BaseKeyListener.onKeyDown(BaseKeyListener.java:215)
	at android.text.method.QwertyKeyListener.onKeyDown(QwertyKeyListener.java:357)
	at android.text.method.TextKeyListener.onKeyDown(TextKeyListener.java:136)
	at android.widget.TextView.doKeyDown(TextView.java:7122)
	at android.widget.TextView.onKeyDown(TextView.java:6929)
	at android.view.KeyEvent.dispatch(KeyEvent.java:3249)
	at android.view.View.dispatchKeyEvent(View.java:9833)
```

**Comment by Valodim** [comment]
see #1815
