### ISSUE TITLE
Crash when no encryption subkey is available

### ISSUE THREAD

**Issue by Valodim** [open-keychain/open-keychain#1817]
Follow-up on #1807

```
 java.lang.IllegalStateException: no encryption methods specified
 at org.bouncycastle.openpgp.PGPEncryptedDataGenerator.open(PGPEncryptedDataGenerator.java:178)
 at org.bouncycastle.openpgp.PGPEncryptedDataGenerator.open(PGPEncryptedDataGenerator.java:333)
 at org.sufficientlysecure.keychain.pgp.PgpSignEncryptOperation.execute(PgpSignEncryptOperation.java:340)
 at org.sufficientlysecure.keychain.operations.SignEncryptOperation.execute(SignEncryptOperation.java:153)
 at org.sufficientlysecure.keychain.operations.SignEncryptOperation.execute(SignEncryptOperation.java:61)
 at org.sufficientlysecure.keychain.service.KeychainService$1.run(KeychainService.java:146)
```

This error should be handled with a log entry and error status in PgpSignEncryptOperation, and display an error message. For the extra mile, it could also highlight the problematic recipients in our own encryption activities.

**Comment by 007durgesh219** [comment]
If the key is revoked or don't have valid encryption subkey then there is no option to use it in entire app except use it from the home screen. There should be a way to avoid that too.  In my suggestion, we should show a message to the user that one of the selected keys is revoked or don't have a valid encryption subkey when he/she tries to use it from the home screen and should not take to encryption activity.

**Comment by 007durgesh219** [comment]
setting mFailOnMissingEncryptionKeyIds flag of PgpSignEncryptInputParcel to true will fix this. Will it create any additional problem?? or it's a correct fix.
