### ISSUE TITLE
Security Token: NullPointerException on UsbConnectionDispatcher

### ISSUE THREAD

**Issue by dschuermann** [open-keychain/open-keychain#1849]
From Google developer console:
version 39510
Android-Version Android 6.0

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{org.sufficientlysecure.keychain/org.sufficientlysecure.keychain.ui.CreateKeyActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void org.sufficientlysecure.keychain.util.UsbConnectionDispatcher.rescanDevices()' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2434)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2494)
	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4120)
	at android.app.ActivityThread.access$1000(ActivityThread.java:157)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1362)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5525)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:730)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:620)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void org.sufficientlysecure.keychain.util.UsbConnectionDispatcher.rescanDevices()' on a null object reference
	at org.sufficientlysecure.keychain.ui.base.BaseSecurityTokenNfcActivity.checkDeviceConnection(BaseSecurityTokenNfcActivity.java:486)
	at org.sufficientlysecure.keychain.ui.CreateSecurityTokenWaitFragment.onCreate(CreateSecurityTokenWaitFragment.java:43)
	at android.support.v4.app.Fragment.performCreate(Fragment.java:1951)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1029)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1252)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1234)
	at android.support.v4.app.FragmentManagerImpl.dispatchCreate(FragmentManager.java:2041)
	at android.support.v4.app.FragmentController.dispatchCreate(FragmentController.java:163)
	at android.support.v4.app.FragmentActivity.onCreate(FragmentActivity.java:332)
	at android.support.v7.app.AppCompatActivity.onCreate(AppCompatActivity.java:74)
	at org.sufficientlysecure.keychain.ui.base.BaseActivity.onCreate(BaseActivity.java:49)
	at org.sufficientlysecure.keychain.ui.base.BaseSecurityTokenNfcActivity.onCreate(BaseSecurityTokenNfcActivity.java:203)
	at org.sufficientlysecure.keychain.ui.CreateKeyActivity.onCreate(CreateKeyActivity.java:74)
	at android.app.Activity.performCreate(Activity.java:6272)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2387)
	... 10 more
```

**Comment by dschuermann** [comment]
@nmikhailov can you look into this?

**Comment by nmikhailov** [comment]
Seems like checkDeviceConnection should be callend in onActivityCreated instead of in onCreate otherwise it will crash on rotations...

**Comment by nmikhailov** [comment]
I will make a PR for that
