### ISSUE TITLE
'Unfortunately, OpenKeyChain has stopped' on automatic reimport after upgrade to 3.9.5

### ISSUE THREAD

**Issue by jotbe** [open-keychain/open-keychain#1853]
Hi,

I am stuck with a 'broken' Open-Keychain update on my phone. When opening the application it will try to reimport the keys and crashes at around 65%. I have several secret keys and >300 public keys. 

Stacktrace from `logcat`:

```
E/AndroidRuntime(20571): FATAL EXCEPTION: Thread-48963
E/AndroidRuntime(20571): Process: org.sufficientlysecure.keychain, PID: 20571
E/AndroidRuntime(20571): java.lang.AssertionError: Rank 0 user packet must be a user id!
E/AndroidRuntime(20571):        at org.sufficientlysecure.keychain.provider.KeychainProvider.insert(KeychainProvider.java:810)
E/AndroidRuntime(20571):        at android.content.ContentProviderOperation.apply(ContentProviderOperation.java:214)
E/AndroidRuntime(20571):        at android.content.ContentProvider.applyBatch(ContentProvider.java:1617)
E/AndroidRuntime(20571):        at android.content.ContentProvider$Transport.applyBatch(ContentProvider.java:260)
E/AndroidRuntime(20571):        at android.content.ContentProviderClient.applyBatch(ContentProviderClient.java:377)
E/AndroidRuntime(20571):        at android.content.ContentResolver.applyBatch(ContentResolver.java:1233)
E/AndroidRuntime(20571):        at org.sufficientlysecure.keychain.provider.ProviderHelper.saveCanonicalizedPublicKeyRing(ProviderHelper.java:730)
E/AndroidRuntime(20571):        at org.sufficientlysecure.keychain.provider.ProviderHelper.savePublicKeyRing(ProviderHelper.java:978)
E/AndroidRuntime(20571):        at org.sufficientlysecure.keychain.operations.ImportOperation.serialKeyRingImport(ImportOperation.java:321)
E/AndroidRuntime(20571):        at org.sufficientlysecure.keychain.operations.ImportOperation.serialKeyRingImport(ImportOperation.java:101)
E/AndroidRuntime(20571):        at org.sufficientlysecure.keychain.provider.ProviderHelper.consolidateDatabaseStep2(ProviderHelper.java:1357)
E/AndroidRuntime(20571):        at org.sufficientlysecure.keychain.provider.ProviderHelper.consolidateDatabaseStep2(ProviderHelper.java:1259)
E/AndroidRuntime(20571):        at org.sufficientlysecure.keychain.operations.ConsolidateOperation.execute(ConsolidateOperation.java:43)
E/AndroidRuntime(20571):        at org.sufficientlysecure.keychain.operations.ConsolidateOperation.execute(ConsolidateOperation.java:31)
E/AndroidRuntime(20571):        at org.sufficientlysecure.keychain.service.KeychainService$1.run(KeychainService.java:146)
E/AndroidRuntime(20571):        at java.lang.Thread.run(Thread.java:841)

```
Unfortunately I couldn't find out yet which key is affected.

Maybe related to #1660? There are a couple of revoked keys (pub and sec) in my keyrings.

**Comment by dschuermann** [comment]
That looks like a different problem than #1660 
This is a weird issue, the assertion check at line 810 is not new in 3.9.5, it has been introduced before. I am not sure why you haven't encountered this error before, it should have happened before when saving the key the first time/updating it and not just now on db update.

**Comment by jotbe** [comment]
I had crashes on an earlier update a couple of months ago, I think it was also related to some parsing issue. Back then I didn't report it (time constraints, forgot about it later) and I was able to workaround that error by purging the whole installation, starting over again and deselecting all keys that I didn't explicitly need. It was quite some work. Honestly I don't understand why this issue appeared again as I should not have been able to import any "broken" key. Importing such a key should have triggered the crash. Weird.

**Comment by dschuermann** [comment]
Also seeing some report of this in the Google Dev Console
