### ISSUE TITLE
Key import fails with "truncated subpacket data"

### ISSUE THREAD

**Issue by kerlerm** [open-keychain/open-keychain#1902]
I'm trying to import key 0x2A411DFD from keyserver
[hkps://hkps.pool.sks-keyservers.net](hkps://hkps.pool.sks-keyservers.net)

open-keychain fails with the following:

```
E/Keychain( 8111): Encountered bad key on import!
E/Keychain( 8111): java.io.EOFException: truncated subpacket data.
E/Keychain( 8111):      at org.bouncycastle.bcpg.SignatureSubpacketInputStream.readPacket(SignatureSubpacketInputStream.java:116)
E/Keychain( 8111):      at org.bouncycastle.bcpg.SignaturePacket.<init>(SignaturePacket.java:76)
E/Keychain( 8111):      at org.bouncycastle.bcpg.BCPGInputStream.readPacket(BCPGInputStream.java:230)
E/Keychain( 8111):      at org.bouncycastle.openpgp.PGPKeyRing.readSignaturesAndTrust(PGPKeyRing.java:53)
E/Keychain( 8111):      at org.bouncycastle.openpgp.PGPKeyRing.readUserIDs(PGPKeyRing.java:91)
E/Keychain( 8111):      at org.bouncycastle.openpgp.PGPPublicKeyRing.<init>(PGPPublicKeyRing.java:76)
E/Keychain( 8111):      at org.bouncycastle.openpgp.PGPObjectFactory.nextObject(PGPObjectFactory.java:114)
E/Keychain( 8111):      at org.sufficientlysecure.keychain.pgp.UncachedKeyRing$2.cacheNext(UncachedKeyRing.java:191)
E/Keychain( 8111):      at org.sufficientlysecure.keychain.pgp.UncachedKeyRing$2.hasNext(UncachedKeyRing.java:212)
E/Keychain( 8111):      at org.sufficientlysecure.keychain.pgp.UncachedKeyRing.decodeFromData(UncachedKeyRing.java:155)
E/Keychain( 8111):      at org.sufficientlysecure.keychain.operations.ImportOperation.serialKeyRingImport(ImportOperation.java:209)
E/Keychain( 8111):      at org.sufficientlysecure.keychain.operations.ImportOperation.access$000(ImportOperation.java:84)
E/Keychain( 8111):      at org.sufficientlysecure.keychain.operations.ImportOperation$1.call(ImportOperation.java:490)
E/Keychain( 8111):      at org.sufficientlysecure.keychain.operations.ImportOperation$1.call(ImportOperation.java:478)
E/Keychain( 8111):      at java.util.concurrent.FutureTask.run(FutureTask.java:237)
E/Keychain( 8111):      at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
E/Keychain( 8111):      at java.util.concurrent.FutureTask.run(FutureTask.java:237)
E/Keychain( 8111):      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
E/Keychain( 8111):      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
E/Keychain( 8111):      at java.lang.Thread.run(Thread.java:818)

```

Enigmail, gpg CLI have no problems importing this key from the same keyserver(pool).

**Comment by kerlerm** [comment]
Works with OpenKeychain 5.2 (52009) Thanks for fixing. Closing now.
