### ISSUE TITLE
BufferUnderflowException

### ISSUE THREAD

**Issue by votingsystem** [open-keychain/open-keychain#1952]
I've installed on a FIDESMO CARD with Dual Interface de PGP application from Fidesmo and when I try to use it as a security token I get this exception:

                                                                                 Caused by: java.nio.BufferUnderflowException
                                                                                           at java.nio.Buffer.checkGetBounds(Buffer.java:171)
                                                                                           at java.nio.ByteArrayBuffer.get(ByteArrayBuffer.java:108)
                                                                                           at java.nio.ByteBuffer.get(ByteBuffer.java:376)
                                                                                           at org.sufficientlysecure.keychain.util.Iso7816TLV.readSingle(Iso7816TLV.java:106)
                                                                                           at org.sufficientlysecure.keychain.util.Iso7816TLV.readList(Iso7816TLV.java:140)
                                                                                           at org.sufficientlysecure.keychain.securitytoken.OpenPgpCapabilities.<init>(OpenPgpCapabilities.java:46)
                                                                                           at org.sufficientlysecure.keychain.securitytoken.SecurityTokenHelper.connectToDevice(SecurityTokenHelper.java:168)
                                                                                           at org.sufficientlysecure.keychain.ui.base.BaseSecurityTokenActivity.handleSecurityToken(BaseSecurityTokenActivity.java:437)
                                                                                           at org.sufficientlysecure.keychain.ui.base.BaseSecurityTokenActivity$1.doInBackground(BaseSecurityTokenActivity.java:171)
                                                                                           at org.sufficientlysecure.keychain.ui.base.BaseSecurityTokenActivity$1.doInBackground(BaseSecurityTokenActivity.java:161)

**Comment by Valodim** [comment]
This one's going to be difficult to debug without reproducing it first. Looks like somewhere, the expected length and actual length of a TLV packet don't match.
