### ISSUE TITLE
RuntimeException in ImportOperation

### ISSUE THREAD

**Issue by dschuermann** [open-keychain/open-keychain#1997]
From Google Play dev console

Just one report until now and only with 4.2
```
java.lang.RuntimeException
	at org.sufficientlysecure.keychain.operations.ImportOperation.multiThreadedKeyImport(ImportOperation.java:515)
	at org.sufficientlysecure.keychain.operations.ImportOperation.execute(ImportOperation.java:456)
	at org.sufficientlysecure.keychain.operations.ImportOperation.execute(ImportOperation.java:83)
	at org.sufficientlysecure.keychain.service.KeychainService$1.run(KeychainService.java:149)
	at java.lang.Thread.run(Thread.java:818)
```

**Comment by Valodim** [comment]
Phew, the code at that position is *not* well suited for debugging. Since this seems to be a rare issue, I added the caught exception as cause to the runtime exception, that way we at least have a way to know what's happening.

3e7e520c300da780c6805edda526f5c8bd7e358b

**Comment by dschuermann** [comment]
Hmm, we now have 2 reports about this bug. One comment: "app repeatedly crashes when attempting to update keys"
Looks like something that has been introduced in 4.2(.1)

**Comment by Valodim** [comment]
Yup. Nothing we can do though, before a release with the fix above is out.
