### ISSUE TITLE
NPE in CardCapabilities

### ISSUE THREAD

**Issue by dschuermann** [open-keychain/open-keychain#2000]
From Google Play dev console
App-Version 42100
Android-Version Android 6.0

Unfortunately, we don't know which security token has been used as this is not provided by the user.

```
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$3.done(AsyncTask.java:309)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	at java.lang.Thread.run(Thread.java:818)
Caused by: java.lang.NullPointerException: Attempt to read from null array
	at org.sufficientlysecure.keychain.securitytoken.CardCapabilities.<init>(CardCapabilities.java:31)
	at org.sufficientlysecure.keychain.securitytoken.SecurityTokenHelper.connectToDevice(SecurityTokenHelper.java:203)
	at org.sufficientlysecure.keychain.ui.base.BaseSecurityTokenActivity.handleSecurityToken(BaseSecurityTokenActivity.java:444)
	at org.sufficientlysecure.keychain.ui.base.BaseSecurityTokenActivity$1.doInBackground(BaseSecurityTokenActivity.java:172)
	at org.sufficientlysecure.keychain.ui.base.BaseSecurityTokenActivity$1.doInBackground(BaseSecurityTokenActivity.java:162)
	at android.os.AsyncTask$2.call(AsyncTask.java:295)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	... 4 more
```

**Comment by af-anssi** [comment]
I walked through the code, and it appears to be the field mHistoricalBytes in OpenPgpCapabilities instance that is not initialized. The only path I find in the code where it can happen is a token responding without error to the getData(0x00, 0x6E), but without any data to parse, which is not an expected behaviour. A simple workaround that will not affect any other tokens could be to test the nullity of this array in CardCapabilities, line 31, before trying to access the array.

**Comment by Valodim** [comment]
Wouldn't it make more sense to check if the `getData` call returns the expected data, and trigger the error earlier?

**Comment by af-anssi** [comment]
The expected data are parsed in the constructor of OpenPgpCardCapabilities just after the call to the constructor of CardCapabilities containing the null array dereference (SecurityTokenHelper class, lines 202-203). The fix I propose is simply to test if the array argument passed in the CardCapabilities constructor is not null before accessing it.

**Comment by af-anssi** [comment]
We could test the nullity of historical bytes in the method updateWithData of the OpenPgpCardCapabilities, but I am not sure this is a good place for this test as this method could be used to parse some other data not containing the historical bytes data...

**Comment by dschuermann** [comment]
Great, I think it's okay to test for null at this point.
