### ISSUE TITLE
cursor error during key refresh

### ISSUE THREAD

**Issue by Valodim** [open-keychain/open-keychain#2033]
## Expected Behavior
A key could not be imported during multi-threaded import
java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Couldn't read row 0, col 0 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
at java.util.concurrent.FutureTask.report(FutureTask.java:94)
at java.util.concurrent.FutureTask.get(FutureTask.java:164)
at org.sufficientlysecure.keychain.operations.ImportOperation.multiThreadedKeyImport(ImportOperation.java:506)
at org.sufficientlysecure.keychain.operations.ImportOperation.execute(ImportOperation.java:456)
at org.sufficientlysecure.keychain.service.KeyserverSyncAdapterService.directUpdate(KeyserverSyncAdapterService.java:324)
at org.sufficientlysecure.keychain.service.KeyserverSyncAdapterService.updateKeysFromKeyserver(KeyserverSyncAdapterService.java:313)
at org.sufficientlysecure.keychain.service.KeyserverSyncAdapterService.access$300(KeyserverSyncAdapterService.java:55)
at org.sufficientlysecure.keychain.service.KeyserverSyncAdapterService$3.run(KeyserverSyncAdapterService.java:291)
at java.lang.Thread.run(Thread.java:818)
Caused by: java.lang.IllegalStateException: Couldn't read row 0, col 0 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
at android.database.CursorWindow.nativeGetLong(Native Method)
at android.database.CursorWindow.getLong(CursorWindow.java:511)
at android.database.CursorWindow.getInt(CursorWindow.java:578)
at android.database.AbstractWindowedCursor.getInt(AbstractWindowedCursor.java:69)
at android.database.CursorWrapper.getInt(CursorWrapper.java:122)
at org.sufficientlysecure.keychain.provider.ProviderHelper.getCanonicalizedKeyRing(ProviderHelper.java:311)
at org.sufficientlysecure.keychain.provider.ProviderHelper.getCanonicalizedPublicKeyRing(ProviderHelper.java:263)
at org.sufficientlysecure.keychain.provider.ProviderHelper.savePublicKeyRing(ProviderHelper.java:935)
at org.sufficientlysecure.keychain.operations.ImportOperation.serialKeyRingImport(ImportOperation.java:325)
at org.sufficientlysecure.keychain.operations.ImportOperation.access$000(ImportOperation.java:83)
at org.sufficientlysecure.keychain.operations.ImportOperation$1.call(ImportOperation.java:495)
at org.sufficientlysecure.keychain.operations.ImportOperation$1.call(ImportOperation.java:483)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
```


This does not happen reproducibly, but it does happen in the auto update service, meaning random crash popup from OpenKeychain :\

**Comment by dschuermann** [comment]
@Valodim is this the same stack trace you got today?

**Comment by jyn514** [comment]
Hi, I was hoping to help with this issue, but it seems that ProviderHelper.java has been refactored out of existence? Where should I start?

**Comment by Valodim** [comment]
There's not much to go on here, if you want to help out I'd suggest working on other issues. I would particularly appreciate help on #1881 :)

more on point, ProviderHelper has been renamed to KeyRepository
