### ISSUE TITLE
IllegalArgumentException in SecurityTokenUtils (not enough width to fit value: 256/128)

### ISSUE THREAD

**Issue by dschuermann** [open-keychain/open-keychain#2036]
App-Version 42202

Android-Version Android 6.0

Device Galaxy S7 Edge (hero2lte) 3

```
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$3.done(AsyncTask.java:309)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	at java.lang.Thread.run(Thread.java:818)
Caused by: java.lang.IllegalArgumentException: not enough width to fit value: 256/128
	at org.sufficientlysecure.keychain.securitytoken.SecurityTokenUtils.writeBits(SecurityTokenUtils.java:228)
	at org.sufficientlysecure.keychain.securitytoken.SecurityTokenUtils.createRSAPrivKeyTemplate(SecurityTokenUtils.java:87)
	at org.sufficientlysecure.keychain.securitytoken.SecurityTokenHelper.putKey(SecurityTokenHelper.java:513)
	at org.sufficientlysecure.keychain.securitytoken.SecurityTokenHelper.changeKey(SecurityTokenHelper.java:163)
	at org.sufficientlysecure.keychain.ui.SecurityTokenOperationActivity.doSecurityTokenInBackground(SecurityTokenOperationActivity.java:264)
	at org.sufficientlysecure.keychain.ui.base.BaseSecurityTokenActivity.handleSecurityToken(BaseSecurityTokenActivity.java:446)
	at org.sufficientlysecure.keychain.ui.base.BaseSecurityTokenActivity$1.doInBackground(BaseSecurityTokenActivity.java:172)
	at org.sufficientlysecure.keychain.ui.base.BaseSecurityTokenActivity$1.doInBackground(BaseSecurityTokenActivity.java:162)
	at android.os.AsyncTask$2.call(AsyncTask.java:295)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	... 4 more
```

**Comment by dschuermann** [comment]
@af-anssi could you look into this?

**Comment by af-anssi** [comment]
According to this stack trace, it appears to be a token with a 4096 RSA. I can try to include the support for tokens with RSA keys above 2048 bits, but I have no such token to test, so I could just ensure it will not break support of 2048 bits RSA keys. Is this OK for you ?

**Comment by dschuermann** [comment]
@af-anssi Yup that's okay. We can also buy you a token if you like!
