### ISSUE TITLE
OutOfMemoryError with Nitrokey Pro

### ISSUE THREAD

**Issue by dschuermann** [open-keychain/open-keychain#2043]
Bug from Google Play dev console

## Current Behavior
"Nitrokey Pro key import crash"

devices: Nexus 5X (bullhead), Galaxy S6 (zeroflte)

```
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$3.done(AsyncTask.java:325)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:761)
Caused by: java.lang.OutOfMemoryError: Failed to allocate a 1503930806 byte allocation with 14513802 free bytes and 171MB until OOM
	at org.sufficientlysecure.keychain.securitytoken.usb.CcidTransceiver.receive(CcidTransceiver.java:139)
	at org.sufficientlysecure.keychain.securitytoken.usb.CcidTransceiver.receiveRaw(CcidTransceiver.java:50)
	at org.sufficientlysecure.keychain.securitytoken.usb.CcidTransceiver.iccPowerOn(CcidTransceiver.java:81)
	at org.sufficientlysecure.keychain.securitytoken.usb.tpdu.T1TpduProtocol.<init>(T1TpduProtocol.java:41)
	at org.sufficientlysecure.keychain.securitytoken.usb.UsbTransport.configureProtocol(UsbTransport.java:219)
	at org.sufficientlysecure.keychain.securitytoken.usb.UsbTransport.connect(UsbTransport.java:179)
	at org.sufficientlysecure.keychain.securitytoken.SecurityTokenHelper.connectToDevice(SecurityTokenHelper.java:191)
	at org.sufficientlysecure.keychain.ui.base.BaseSecurityTokenActivity.handleSecurityToken(BaseSecurityTokenActivity.java:444)
	at org.sufficientlysecure.keychain.ui.base.BaseSecurityTokenActivity$1.doInBackground(BaseSecurityTokenActivity.java:172)
	at org.sufficientlysecure.keychain.ui.base.BaseSecurityTokenActivity$1.doInBackground(BaseSecurityTokenActivity.java:162)
	at android.os.AsyncTask$2.call(AsyncTask.java:305)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	... 4 more
```

**Comment by dschuermann** [comment]
@nmikhailov could you look into this?

**Comment by dschuermann** [comment]
Ah this is a duplicate of https://github.com/open-keychain/open-keychain/issues/1936

**Comment by nmikhailov** [comment]
@dschuermann looks like dupe of #1936 
You are right, I should get back to OKC and resolve remaining security token problems.

**Comment by dschuermann** [comment]
@nmikhailov that would be awesome :)
