### ISSUE TITLE
NPE in ViewKeyAdvSubkeysFragment related to ECC

### ISSUE THREAD

**Issue by dschuermann** [open-keychain/open-keychain#2045]
From Google Play dev console. I suspect this has to do with ECC subkeys.

```
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean org.bouncycastle.asn1.ASN1ObjectIdentifier.equals(java.lang.Object)' on a null object reference
	at org.sufficientlysecure.keychain.ui.ViewKeyAdvSubkeysFragment$5.handleMessage(ViewKeyAdvSubkeysFragment.java:374)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:158)
	at android.app.ActivityThread.main(ActivityThread.java:7229)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```

**Comment by dschuermann** [comment]
Could be related to https://github.com/open-keychain/open-keychain/issues/1933
