### ISSUE TITLE
Fidesmo: not enough width to fit value

### ISSUE THREAD

**Issue by Valodim** [open-keychain/open-keychain#2101]
User messages seem to indicate that this happens while trying to move keys to fidesmo card

```
Caused by: java.lang.IllegalArgumentException: not enough width to fit value: 192/128
	at org.sufficientlysecure.keychain.securitytoken.SecurityTokenUtils.writeBits(SecurityTokenUtils.java:230)
	at org.sufficientlysecure.keychain.securitytoken.SecurityTokenUtils.createRSAPrivKeyTemplate(SecurityTokenUtils.java:89)
	at org.sufficientlysecure.keychain.securitytoken.SecurityTokenHelper.putKey(SecurityTokenHelper.java:513)
	at org.sufficientlysecure.keychain.securitytoken.SecurityTokenHelper.changeKey(SecurityTokenHelper.java:163)
	at org.sufficientlysecure.keychain.ui.SecurityTokenOperationActivity.doSecurityTokenInBackground(SecurityTokenOperationActivity.java:266)
	at org.sufficientlysecure.keychain.ui.base.BaseSecurityTokenActivity.handleSecurityToken(BaseSecurityTokenActivity.java:446)
	at org.sufficientlysecure.keychain.ui.base.BaseSecurityTokenActivity$1.doInBackground(BaseSecurityTokenActivity.java:172)
	at org.sufficientlysecure.keychain.ui.base.BaseSecurityTokenActivity$1.doInBackground(BaseSecurityTokenActivity.java:162)
	at android.os.AsyncTask$2.call(AsyncTask.java:295)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	... 4 more
```

**Comment by dschuermann** [comment]
Arg, so https://github.com/open-keychain/open-keychain/issues/2036 is still a problem.

**Comment by dschuermann** [comment]
Maybe this only happens if someone somehow tries to move 4096 bit keys, but we definitely should test this.

**Comment by af-anssi** [comment]
Do we know which version of OpenKeychain has produced this error ?

**Comment by dschuermann** [comment]
It's the last version. I suspect it crashes if someone is trying to move an **existing** 4096 bit RSA key to a Fidesmo card, but I haven't verified.

**Comment by af-anssi** [comment]
I backtracked in the code from the given stacktrace, and I agree it is caused by someone trying to import a RSA  key larger than the card is configured for. Actually, I don't know if Fidesmo cards support RSA larger than 1024 bits, are they ?

**Comment by dschuermann** [comment]
They support up to 2048 bit. Can we use the code that detects that it is a Fidesmo card and then simply restrict the operation?

**Comment by af-anssi** [comment]
We should introduce the check in PgpKeyOperation.java near line 1660, but I find no simple mean to retrieve a reference to the security token at this point...
