### ISSUE TITLE
multiDex needed for building?

### ISSUE THREAD

**Issue by nh2** [open-keychain/open-keychain#2124]
I just tried building commit 258ba1fa1fbbfd3c38110dab1076ae2f5c471aee to test the patch in https://github.com/open-keychain/open-keychain/issues/2049.

`./gradlew installGoogleDebug` got me:

```
:OpenKeychain:mergeGoogleDebugAssets
:OpenKeychain:transformClassesWithDexForGoogleDebug
Dex: The number of method references in a .dex file cannot exceed 64K.
Learn how to resolve this issue at https://developer.android.com/tools/building/multidex.html
    UNEXPECTED TOP-LEVEL EXCEPTION:
    com.android.dex.DexIndexOverflowException: method ID not in [0, 0xffff]: 65536
        at com.android.dx.merge.DexMerger$6.updateIndex(DexMerger.java:495)
        at com.android.dx.merge.DexMerger$IdMerger.mergeSorted(DexMerger.java:261)
        at com.android.dx.merge.DexMerger.mergeMethodIds(DexMerger.java:504)
        at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:161)
        at com.android.dx.merge.DexMerger.merge(DexMerger.java:188)
        at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:504)
        at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
        at com.android.dx.command.dexer.Main.run(Main.java:277)
        at com.android.dx.command.dexer.Main.main(Main.java:245)
        at com.android.dx.command.Main.main(Main.java:106)
```

I followed https://stackoverflow.com/a/36638920/263061 to make the build succeed, using this change:

```diff
diff --git a/OpenKeychain/build.gradle b/OpenKeychain/build.gradle
index 93c8f5c17..af03ea66f 100644
--- a/OpenKeychain/build.gradle
+++ b/OpenKeychain/build.gradle
@@ -172,6 +172,7 @@ android {
         // with android studio single test execution. use it to generate coverage
         // data, but keep the other one otherwis
         // testInstrumentationRunner "org.sufficientlysecure.keychain.JacocoWorkaroundJUnitRunner"
+        multiDexEnabled true
     }
 
     compileOptions {
```

This builds, but when running it I get:

```
E/AndroidRuntime(27318): java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{org.sufficientlysecure.keychain.debug/org.sufficientlysecure.keychain.ui.MainActivity}: java.lang.ClassNotFoundException: Didn't find class "org.sufficientlysecure.keychain.ui.MainActivity" on path: DexPathList[[zip file "/data/app/org.sufficientlysecure.keychain.debug-1.apk"],nativeLibraryDirectories=[/data/app-lib/org.sufficientlysecure.keychain.debug-1, /vendor/lib, /system/lib]]
E/AndroidRuntime(27318): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2135)
E/AndroidRuntime(27318): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2269)
E/AndroidRuntime(27318): 	at android.app.ActivityThread.access$800(ActivityThread.java:139)
E/AndroidRuntime(27318): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1210)
E/AndroidRuntime(27318): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(27318): 	at android.os.Looper.loop(Looper.java:136)
E/AndroidRuntime(27318): 	at android.app.ActivityThread.main(ActivityThread.java:5102)
E/AndroidRuntime(27318): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(27318): 	at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime(27318): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
E/AndroidRuntime(27318): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
E/AndroidRuntime(27318): 	at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime(27318): Caused by: java.lang.ClassNotFoundException: Didn't find class "org.sufficientlysecure.keychain.ui.MainActivity" on path: DexPathList[[zip file "/data/app/org.sufficientlysecure.keychain.debug-1.apk"],nativeLibraryDirectories=[/data/app-lib/org.sufficientlysecure.keychain.debug-1, /vendor/lib, /system/lib]]
E/AndroidRuntime(27318): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
E/AndroidRuntime(27318): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
E/AndroidRuntime(27318): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
E/AndroidRuntime(27318): 	at android.app.Instrumentation.newActivity(Instrumentation.java:1084)
E/AndroidRuntime(27318): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2126)
E/AndroidRuntime(27318): 	... 11 more
```

**Comment by nh2** [comment]
Found a temporary workaround, instead of enablin `multiDex` I'm using this change:

```diff
diff --git a/OpenKeychain/build.gradle b/OpenKeychain/build.gradle
index 93c8f5c17..362cf690e 100644
--- a/OpenKeychain/build.gradle
+++ b/OpenKeychain/build.gradle
@@ -206,7 +206,8 @@ android {
 
         debug {
             // disable ProGuard for faster compile times for debug builds
-            minifyEnabled false
+            minifyEnabled true
+            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules-release.pro'
 
             applicationIdSuffix ".debug"
 ```

**Comment by Valodim** [comment]
activating minify makes the build *very* slow, which is why we don't have it enabled for debug builds. on my machine it goes from a dozen or so seconds to a minute and a half, which has a noticable impact on development productivity.

use the `installFdroidDebug` target. the google one includes more dependencies to allow donations via play store, but is otherwise identical. we develop on the fdroid version, and try to stay below the method limit so the minify isn't necessary.

**Comment by nh2** [comment]
@Valodim OK. Could you add that info to the building section of the README, so that people know?

**Comment by Valodim** [comment]
well um, it says to use the fdroid build. I'm not sure where you got the google part from ;)

**Comment by nh2** [comment]
Ah, I see. I was somehow assuming that the building example uses the fdroid because that's what the developers prefer, and that if I'm not using fdroid I should use the Google build.

But I see that assumption doesn't make sense; anybody can use the fdroid build, even when not using fdroid.

**Comment by Valodim** [comment]
removed google flavor for debug builds and added a line in the readme. that should make it more clear :)

**Comment by nh2** [comment]
Thanks!

**Comment by nh2** [comment]
@Valodim Hmm, tested that now, it seems that I can get the error even with fdroid:

```
:OpenKeychain:transformClassesWithDexForFdroidDebug
Dex: The number of method references in a .dex file cannot exceed 64K.
```

This is on the same commit as in the issue description.

**Comment by nh2** [comment]
> Did you try a `./gradlew clean` inbetween?

That fixes it, thanks!
