### ISSUE TITLE
IllegalArgumentException in TemporaryFileProvider.cleanUp 

### ISSUE THREAD

**Issue by dschuermann** [open-keychain/open-keychain#2141]
From Google Play dev console:

This is happening really often (most encountered crash) on Android 6.

```
java.lang.RuntimeException: 
  at android.app.ActivityThread.handleBindApplication (ActivityThread.java:6319)
  at android.app.ActivityThread.access$1800 (ActivityThread.java:221)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1860)
  at android.os.Handler.dispatchMessage (Handler.java:102)
  at android.os.Looper.loop (Looper.java:158)
  at android.app.ActivityThread.main (ActivityThread.java:7224)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1230)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1120)

Caused by: java.lang.IllegalArgumentException: 
  at android.content.ContentResolver.delete (ContentResolver.java:1376)
  at org.sufficientlysecure.keychain.provider.TemporaryFileProvider.cleanUp (TemporaryFileProvider.java:115)
  at org.sufficientlysecure.keychain.KeychainApplication.onCreate (KeychainApplication.java:121)
  at android.app.Instrumentation.callApplicationOnCreate (Instrumentation.java:1036)
  at android.app.ActivityThread.handleBindApplication (ActivityThread.java:6316)
```

**Comment by Valodim** [comment]
This only happened four times, and only on Samsung devices. Am I not looking at the right crash report?

The problem seems to be that our content provider URI isn't recognized. But I can't think of a reason why this would happen, the provider is even exported! I suspect this is a Samsung fuckup :(

We could fix the symptom I guess, but that would just cover the underlying cause. This also happened only in 4.2 versions, and was last reported in April. I think we should ignore this for now and take another look if it comes up again.

**Comment by dschuermann** [comment]
Now I am confused, I see:
```
Meldungen diese Woche 
900
Meldungen insgesamt 
9.493
Betroffene Nutzer 
321
```
But you are right, it looks like it is only Samsung devices :(

**Comment by Valodim** [comment]
Ooh. Yeah there is a new section for the automatically shared crash reports. I only looked at those people manually reported. Wow that does happen often.

here's a nicer stacktrace:
```
java.lang.RuntimeException: Unable to create application org.sufficientlysecure.keychain.KeychainApplication: java.lang.IllegalArgumentException: Unknown URL content://org.sufficientlysecure.keychain.tempstorage
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6324)
	at android.app.ActivityThread.access$1800(ActivityThread.java:222)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1861)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:158)
	at android.app.ActivityThread.main(ActivityThread.java:7229)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
Caused by: java.lang.IllegalArgumentException: Unknown URL content://org.sufficientlysecure.keychain.tempstorage
	at android.content.ContentResolver.delete(ContentResolver.java:1376)
	at org.sufficientlysecure.keychain.provider.TemporaryFileProvider.cleanUp(TemporaryFileProvider.java:115)
	at org.sufficientlysecure.keychain.KeychainApplication.onCreate(KeychainApplication.java:121)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1036)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6321)
	... 8 more
```

I guess we could catch that exception and ignore the problem. maybe Application.onCreate is called in some weird scenario by Samsung but it works in the usual android one?

**Comment by dschuermann** [comment]
Oh Samsung :(
Maybe the provider is not fully initialized when Application is initiated: https://stackoverflow.com/questions/41474623/sporadic-illegalargumentexception-unknown-url-content

We could do as proposed in the stackoverflow answer and move it to a background job.

**Comment by keith24** [comment]
Samsung ON5 user here.  The app is crashing whenever I tap on a key.  If this error is so common, that might be it.  I just cloned the repo and will tried to test it... but ran into an error: 

> Error:Project :libkeychain declares a dependency from configuration 'compile' to configuration 'default' which is not declared in the descriptor for project :openpgp-api-lib.

I don't know much about java/android... I have no idea what this means.  If it's easy to fix, and I get it running, I'd be happy to test out possible solutions on my Samsung.

**Comment by dschuermann** [comment]
Please read https://github.com/open-keychain/open-keychain#build-with-gradle . You forgot the submodules.

**Comment by keith24** [comment]
OK, I give up.  I can't get it to build.  Android is not really my thing.  

I'm still offering my Samsung for testing if you want to send me APKs.
