### ISSUE TITLE
Using Yubikey Neo (brand new) Can sign but not decrypt (apdu error)

### ISSUE THREAD

**Issue by Morthawt** [open-keychain/open-keychain#2179]
I go to decrypt a test message and it fails with "Failed to chain apdu"

## Expected Behavior
The message should be decrypted.

## Current Behavior
Error: Failed to chain apdu

Take away the Security Token now and touch TRY AGAIN.

## Possible Solution
I do not know

## Steps to Reproduce (for bugs)
1. Click my key
2. Encrypt a message (not signed) to myself
3. Go to main screen
4. Encrypt/Decrypt
5. Read from clipboard
6. Hold Yubikey Neo to the back of the phone when requested.

## Context
I am unable to use my key for decrypting messages. All I seem to be able to do is sign.

## Your Environment

* Android Version: 6.0.1
* OpenKeychain Version: 4.7
* From Google Play or F-Droid?: F-Droid

**Comment by Valodim** [comment]
Huh. This happens [https://github.com/open-keychain/open-keychain/blob/master/OpenKeychain/src/main/java/org/sufficientlysecure/keychain/securitytoken/SecurityTokenHelper.java#L798](here), when a command returns an error before it is fully transferred.

ping @nmikhailov, also tentative ping @jas4711 do you know if maybe something changed on new yubikeys lately?

**Comment by Morthawt** [comment]
I am not aware of any changes. What is strange is that the Yubico
authenticator app which obtains TOTP codes via NFC works, signing
information through your app using NFC works. Decryption is the thing which
is not working. I am unaware of what the problem is. I even tried
generating the key internally instead of making a key myself as I did
before and it just errors. You have the best GPG app for android, Yubikeys
are (hands down) the best hardware for personal security and privacy. It
would be nice if perhaps they could help you resolve this or supply you one
for testing? But all I know is, this problem is my only stumbling block so
far with your amazing app.




----------------------------------------
For secure PGP/GnuPG users, if it is *seriously *needed/personal etc
(I rarely use crypto due to more work involved, no ability to search past
emails etc)
The download link for my public key
<https://keyserver2.pgp.com/vkd/DownloadKey.event?keyid=0xDF945F5C614D98E6>
Key Fingerprint: 4C23 C140 E8BE E33B 7858  D986 DF94 5F5C 614D 98E6
----------------------------------------

**Comment by Valodim** [comment]
We have a bunch of yubikeys for testing, and they work fine. Also, as far as we know, nothing changed in the yubico openpgp applet since the authentication bug was fixed a long time ago.

I assume you're using NFC for this. Could you try if the same operation works via USB with OpenKeychain? And, does it work with gnupg via usb?

**Comment by Morthawt** [comment]
gnupg works fine via USB. As for OpenKeychain I have no clue how I could
test that over USB unless you have a windows client?




----------------------------------------
For secure PGP/GnuPG users, if it is *seriously *needed/personal etc
(I rarely use crypto due to more work involved, no ability to search past
emails etc)
The download link for my public key
<https://keyserver2.pgp.com/vkd/DownloadKey.event?keyid=0xDF945F5C614D98E6>
Key Fingerprint: 4C23 C140 E8BE E33B 7858  D986 DF94 5F5C 614D 98E6
----------------------------------------

**Comment by Valodim** [comment]
Yubikeys can be connected via USB-OTG adapter or USB-C to USB-A. But if you don't have one of these, nvm. This issue might be related to #2049, which also suggests something wrong in the code that fragments APDUs that are too large.

**Comment by Morthawt** [comment]
My phone is not OTG capable. Possibly, although I am not a high level
programmer, I only make programs and tools with AutoIt scripting language
on Windows. All I can think of to tell you is signing works fine but
decryption fails each and every time. I would ideally love to have this
capability when mobile, rather than have private keys on insecure
(potentially) devices like computers and phones etc. My primary key is 4096
bit and won't fit on a Yubikey Neo, so I was forced to make a 2048 bit
especially for mobile capability. Still, I was very much hoping to have
this capability and look forward to a resolution that will complete my Neo
usage.




----------------------------------------
For secure PGP/GnuPG users, if it is *seriously *needed/personal etc
(I rarely use crypto due to more work involved, no ability to search past
emails etc)
The download link for my public key
<https://keyserver2.pgp.com/vkd/DownloadKey.event?keyid=0xDF945F5C614D98E6>
Key Fingerprint: 4C23 C140 E8BE E33B 7858  D986 DF94 5F5C 614D 98E6
----------------------------------------

**Comment by Valodim** [comment]
For now I'll try to add some more debugging output to that code, but I'm afraid there's not a lot I can do right now to fix the problem.

Can you check what firmware version you have on your Yubikey? (you can find out with the ykpersonalize program)

**Comment by Morthawt** [comment]
3.4.9 on my new Neo. First I have had. I am quite impressed, other than the
PGP key size limitation.




----------------------------------------
For secure PGP/GnuPG users, if it is *seriously *needed/personal etc
(I rarely use crypto due to more work involved, no ability to search past
emails etc)
The download link for my public key
<https://keyserver2.pgp.com/vkd/DownloadKey.event?keyid=0xDF945F5C614D98E6>
Key Fingerprint: 4C23 C140 E8BE E33B 7858  D986 DF94 5F5C 614D 98E6
----------------------------------------

**Comment by Valodim** [comment]
Oh, I just thought of something. Can you tell me the key id you're using if it's on keyservers, or send the public key via mail?

**Comment by Morthawt** [comment]
It is my signature under my emails here. If you do not see it let me know
and I will manually dig it up for you.




----------------------------------------
For secure PGP/GnuPG users, if it is *seriously *needed/personal etc
(I rarely use crypto due to more work involved, no ability to search past
emails etc)
The download link for my public key
<https://keyserver2.pgp.com/vkd/DownloadKey.event?keyid=0xDF945F5C614D98E6>
Key Fingerprint: 4C23 C140 E8BE E33B 7858  D986 DF94 5F5C 614D 98E6
----------------------------------------

**Comment by Valodim** [comment]
got it, thanks

**Comment by Morthawt** [comment]
Ah actually no it is separate 1 sec, it's the lower sec 2048 one:

-----BEGIN PGP PUBLIC KEY BLOCK-----

mQENBFnTnxQBCACxosY7WTBbClOR7BF+LEk6WfHq7pcvH47wU0vzKOaV1aj7J34a
nBLAm8apokpg7t/c9sQmPYtgZPnumP4SpH/VgL0RxtQXTk2Q9S9GqXjZ7sQ37N+i
TM0ACspMKK24KeMxRA6JJPU7HS+GmurnpXpBryxGnlLton3tvut7LlJOjW76mjLc
lX+Gv6dFAbpz1gpr27mQgzgNc+fKyAErObNkKGQd+lauc05ddZnCYVc4KGpazrUn
45+jn628Lwc68z/jCE5tEnPn8kw1JIZhONKU0C9Gxs2SthAh7vhR8rDCPjtj+Uxk
u/7rutI9iwxvtOo/dK7khmwR3gKXrUnv3MWlABEBAAG0ck5vdCBEaXNjbG9zZWQg
KFRoaXMga2V5IHdhcyBnZW5lcmF0ZWQgaW4gWXViaWNvIGhhcmR3YXJlLiBObyBr
ZXkgYmFja3VwcyBhcmUgcG9zc2libGUuKSA8bm90LmRpc2Nsb3NlZEBkb21haW4u
dGxkPokBTgQTAQgAOBYhBGUH8voLYgDaZg+Fwx4FAcmQIlvPBQJZ058UAhsDBQsJ
CAcCBhUICQoLAgQWAgMBAh4BAheAAAoJEB4FAcmQIlvP3wsH/1lpNUoKI/EYoAtH
eAywEzDEJtThTwzl7iH6XTZX+ajxftSyGAYTaL23qlRaraXVRwG2IYBsnf/Stass
uKVrqh/toDRqh9WYmqkGLIklO/Yi6CXb6x+bRGla0B8xmTxrtgqyw3DQgYdvd4/D
eyqqMmaQq8ua2aSUmrcC0temk/kz75f0KySnyPBDE1K5oPVhB2uj3qYXCWh9bRES
sXJT+Z9xerfHGoHM61ZofJFtPktUzpn7jCeJVYs/E2vvSpr8wr5iW8Of12Vhc1JM
nBM6jJhSzU9aaWUd9nVAgDz92ET372EnSqhgcjhhP0SeqQh5KQi9X0bmpSrUtz3S
WkIce6i5AQ0EWdOfFAEIAKvB0shctAleK/N2jzQO+LAkxLc5J7HzxeiuAm7P2wkW
fQJ+fty7sh41QNnxD0UW1bYd8IJgjmHIjs5rD1XMxAlkj+XPAPt9qpeC8XnyN1WT
mZLTPv4COtoZ8pw0vSUzfrl4KsE+ACP7NVE2z58yK8aeEKpEekCQ39PdPU8ZvANz
qZufZytGebUUWyqjziPnlV4PEubUXU0GKtVMkjbwf42LQwXUrSCFNYP11HmP2XZK
5IsYp1WGqZb500U6PgdV5nMONB3eomZBhwlQJlXrfHLc3vPsm9/KUiG+Lq3dhCLo
N0t7P/ogurI6q+V6pCSN71NM8zIYaectUa26Kd7XbJ0AEQEAAYkBNgQYAQgAIBYh
BGUH8voLYgDaZg+Fwx4FAcmQIlvPBQJZ058UAhsgAAoJEB4FAcmQIlvP3O8H/jk5
ouJQtiyM6jpEM6MAFZOeK+F2QpIIfAYrjDH+J2WKEFSR32e34ZGPpLtvBfUYSQ98
j7UaiFg1Q4xb/vZmXcs4vou9GRgHAWWWCvWv73YI4I8G2rvmQpXjkjDFzrUFjQ+f
nshlRdH2u+dp2cqLBRGoB0FSDwRnNMcgzDwRY7ALBEBm7dQYKe7/vTzeWMieEF7Y
CekAh8R1yXZLKaKjvTiQgZ+yAad6hl0LfbDMBq+DakinbL6FWRxGiQVKR91chgYg
yDR7Xf38Ef3C/cJXpyZm3ZsEznY/cgTaQkpE7eHls5BubWMPEhotuCaOpVU2ooqb
YZ1riA/VmxeLOUtRRny5AQ0EWdOfFAEIAJFmkjmNuTh/zJYR1RhFpdjffL/iejCC
8lKl/qIt7bPzWiRy7Ze1mQLaPROCYDHVoJefmdHEKSRVBmVK/cGymJVFOVD7IVrq
jXxfXgpKOMbo+p7BwrhCroR37mR684C/yXcAdHS9c1seQJEdlNrkvVqvrm27NBw0
GWLhfpmoOXgma0uHWCUYOvnQk7ffjzVo8jNquPaMa6Q7LlmBsJluAKHBbmW157qa
HFiM4Z9xCJTbXgplTkI48KalBv/eqXC7w+9/fI6L9rXAuh1SayWn8t6min+QTYos
G+2tVzGBPSrvVHalvhIV5TRjjQEqm078JG5jrIbdAZw4dpGciY1pPdkAEQEAAYkB
NgQYAQgAIBYhBGUH8voLYgDaZg+Fwx4FAcmQIlvPBQJZ058UAhsMAAoJEB4FAcmQ
IlvPnxUH/1a75hKtlE6PggFOs1kc6j0+930T76pjamjvp2ep0Ogu3NizgSdgKNJ/
KjBIvXUWwhbU5aHMhXPGCocSEaXPzM4yShu41Z+XErKVXeWYCtuHkgahC7DKxLKd
X86YwwujsbNaYS3lOnJ/JDwBGz9tzvO2hJGTvzjrqEzScUAMXOJJsLHiohRWIP9h
+36IhkHSFHJa8jHn4F9XmUPdat9s5TprRddCAfT98O9DHkVlR1CvjzerCs5TII0T
W90hubQVpq46B57mOpzvJMz/nqgbDepUMWwvY/CZNGNsVWT8ItdKdGObjLApa3Ke
mKku7NNmd2bLZzweZ5laRdjlcMBKgho=
=zMgF
-----END PGP PUBLIC KEY BLOCK-----






----------------------------------------
For secure PGP/GnuPG users, if it is *seriously *needed/personal etc
(I rarely use crypto due to more work involved, no ability to search past
emails etc)
The download link for my public key
<https://keyserver2.pgp.com/vkd/DownloadKey.event?keyid=0xDF945F5C614D98E6>
Key Fingerprint: 4C23 C140 E8BE E33B 7858  D986 DF94 5F5C 614D 98E6
----------------------------------------

**Comment by Valodim** [comment]
Hm ok, the idea I had wasn't it. Back to square one.

**Comment by Morthawt** [comment]
Another error just happened, which I forgot has happened a few times:

Error: null

Take away the Security Token now and touch TRY AGAIN.




----------------------------------------
For secure PGP/GnuPG users, if it is *seriously *needed/personal etc
(I rarely use crypto due to more work involved, no ability to search past
emails etc)
The download link for my public key
<https://keyserver2.pgp.com/vkd/DownloadKey.event?keyid=0xDF945F5C614D98E6>
Key Fingerprint: 4C23 C140 E8BE E33B 7858  D986 DF94 5F5C 614D 98E6
----------------------------------------

**Comment by Morthawt** [comment]
I wiped out the hardware-generated key with a whole new software generated
key, to see if some how it would make a difference. The same issues are
persisting the "null" and "apdu" errors. Sorry I could not be much help to
you in resolving/diagnosing this. Very frustrating.




----------------------------------------
For secure PGP/GnuPG users, if it is *seriously *needed/personal etc
(I rarely use crypto due to more work involved, no ability to search past
emails etc)
The download link for my public key
<https://keyserver2.pgp.com/vkd/DownloadKey.event?keyid=0xDF945F5C614D98E6>
Key Fingerprint: 4C23 C140 E8BE E33B 7858  D986 DF94 5F5C 614D 98E6
----------------------------------------

**Comment by Morthawt** [comment]
I just tried to certify/verify one of my other keys. I have the public key
on my phone. I attempted to sign it with the test one on my Yubikey Neo.
Same problem as attempting to decrypt. So so far I am unable to decrypt and
unable to certify other keys using my Neo.




----------------------------------------
For secure PGP/GnuPG users, if it is *seriously *needed/personal etc
(I rarely use crypto due to more work involved, no ability to search past
emails etc)
The download link for my public key
<https://keyserver2.pgp.com/vkd/DownloadKey.event?keyid=0xDF945F5C614D98E6>
Key Fingerprint: 4C23 C140 E8BE E33B 7858  D986 DF94 5F5C 614D 98E6
----------------------------------------

**Comment by Valodim** [comment]
We'll be receiving some new yubikeys soon. If the problem occurs with them we should be able to fix it. If it doesn't, there is a possibility that you simply have a bad yubikey :hurtrealbad:

Anyways, we'll look into that and get back to you.

**Comment by Morthawt** [comment]
Thanks. My feeling is it's probably not a problem with my Yubikey as other
NFC functions appear to be fine. One thing to note is I have performed a
reset of the PGP applet or what ever after experimenting with failing pin
codes and things and verifying for myself what happens. I followed these
simple instructions:
https://developers.yubico.com/ykneo-openpgp/ResetApplet.html I also made a
bat file so I could just execute it if I mess up something on either of my
YK4 or YKNeo keys. I have pin and admin set but I have not set up any PUK.




----------------------------------------
For secure PGP/GnuPG users, if it is *seriously *needed/personal etc
(I rarely use crypto due to more work involved, no ability to search past
emails etc)
The download link for my public key
<https://keyserver2.pgp.com/vkd/DownloadKey.event?keyid=0xDF945F5C614D98E6>
Key Fingerprint: 4C23 C140 E8BE E33B 7858  D986 DF94 5F5C 614D 98E6
----------------------------------------

**Comment by dschuermann** [comment]
@Morthawt I was able to reproduce the "null" error. It happens sometimes when the Yubikey is not hold against the correct position and taken away too fast.

We got new YubiKey NEOs but I was not able to reproduce the error.

So, to debug the real problem a little bit further:
Which type of phone do you use?
How has the message/file been encrypted? Using OpenKeychain or gpg?
Are you sure this also happens on certify? Certify should be a similar short APDU as signing.

BTW: We now track some details (including problematic phones) here: https://github.com/open-keychain/open-keychain/wiki/Security-Tokens

**Comment by Morthawt** [comment]
Samsung Galaxy S5 Mini. The file is not decrypted after attempt. I was only using your app to try the encryption/decryption/signing. Certify and decrypt do not work.

**Comment by dschuermann** [comment]
How was the file encrypted? With OpenKeychain?

**Comment by Morthawt** [comment]
As I said, all operations were done inside your app. I tried using keys
made by the Yubikey neo it's self and also ones I imported that I made
myself outside and no matter what, decryption and certifying does not work.
I can reliably sign any time I want and that is it.




----------------------------------------
For secure PGP/GnuPG users, if it is *seriously *needed/personal etc
(I rarely use crypto due to more work involved, no ability to search past
emails etc)
The download link for my public key
<https://keyserver2.pgp.com/vkd/DownloadKey.event?keyid=0xDF945F5C614D98E6>
Key Fingerprint: 4C23 C140 E8BE E33B 7858  D986 DF94 5F5C 614D 98E6
----------------------------------------

**Comment by Morthawt** [comment]
I can add, I have tested the other features of the Yubikey Neo, PIV,
OpenPGP in general, Yubico OTP, Challenge response, TOTP storage all work
fine. I have used the NFC to sign with your app, U2F via the chrome app and
TOTP codes via Yubico authenticator, all of which worked fine. So I have a
feeling it is most likely a bug or glitch some how, else signing would not
be reliable.




----------------------------------------
For secure PGP/GnuPG users, if it is *seriously *needed/personal etc
(I rarely use crypto due to more work involved, no ability to search past
emails etc)
The download link for my public key
<https://keyserver2.pgp.com/vkd/DownloadKey.event?keyid=0xDF945F5C614D98E6>
Key Fingerprint: 4C23 C140 E8BE E33B 7858  D986 DF94 5F5C 614D 98E6
----------------------------------------

**Comment by dschuermann** [comment]
Thanks for the info. We need to dig deeper ;)

**Comment by Morthawt** [comment]
No problem. I eagerly await the day I can truly realise the potential of
this Neo by using your app. Not that I actually do much encrypted email. I
probably have an encrypted email conversation once every 4 years lol but
still, having the capability while mobile is very interesting. Pity I
cannot put my real 4096bit key on there though.




----------------------------------------
For secure PGP/GnuPG users, if it is *seriously *needed/personal etc
(I rarely use crypto due to more work involved, no ability to search past
emails etc)
The download link for my public key
<https://keyserver2.pgp.com/vkd/DownloadKey.event?keyid=0xDF945F5C614D98E6>
Key Fingerprint: 4C23 C140 E8BE E33B 7858  D986 DF94 5F5C 614D 98E6
----------------------------------------

**Comment by evgeny-mezin-epam** [comment]
> Pity I cannot put my real 4096bit key on there though.

Actually, you can, but only using the Yubikey 4 (without NFC capability). 
Nevertheless you can make use of OTG cable on your mobile to utilize the Yubikey4's 4096bit potential

**Comment by Morthawt** [comment]
I was referring to the Neo, I have my 4096 key on my Yubikey 4's. My phone
is not OTG compatible. I have tried it.




----------------------------------------
For secure PGP/GnuPG users, if it is *seriously *needed/personal etc
(I rarely use crypto due to more work involved, no ability to search past
emails etc)
The download link for my public key
<https://keyserver2.pgp.com/vkd/DownloadKey.event?keyid=0xDF945F5C614D98E6>
Key Fingerprint: 4C23 C140 E8BE E33B 7858  D986 DF94 5F5C 614D 98E6
----------------------------------------

**Comment by dschuermann** [comment]
@Morthawt though I am not fully sure what causes your problem, can you re-test with the newest OpenKeychain 4.8? We did a lot of refactoring in the smartcard layer.

**Comment by Morthawt** [comment]
I can now encrypt, decrypt, sign and verify text. I am unable to select my
private key to certify a public key though for some reason. It's greyed out
and will not let me select my key.




----------------------------------------
For secure PGP/GnuPG users, if it is *seriously *needed/personal etc
(I rarely use crypto due to more work involved, no ability to search past
emails etc)
The download link for my public key
<https://keyserver2.pgp.com/vkd/DownloadKey.event?keyid=0xDF945F5C614D98E6>
Key Fingerprint: 4C23 C140 E8BE E33B 7858  D986 DF94 5F5C 614D 98E6
----------------------------------------

**Comment by dschuermann** [comment]
@Morthawt from your previous comment I deduce that your primary key is not on your Yubikey Neo and not on your phone? If yes, certifying will not work, this can only be done by your primary key.

**Comment by Morthawt** [comment]
My private key is on the Yubikey Neo. I say private, the key I mess around
with on my neo is. My absolutely main one is 4096 bit and can only fit on
my Yubikey 4's. But when I download the public key for my main primary and
try to sign it with my Yubikey's one that contains a private key, it is
greyed out and will not certify, even though the private key is on the
Yubikey Neo,.




----------------------------------------
For secure PGP/GnuPG users, if it is *seriously *needed/personal etc
(I rarely use crypto due to more work involved, no ability to search past
emails etc)
The download link for my public key
<https://keyserver2.pgp.com/vkd/DownloadKey.event?keyid=0xDF945F5C614D98E6>
Key Fingerprint: 4C23 C140 E8BE E33B 7858  D986 DF94 5F5C 614D 98E6
----------------------------------------

**Comment by dschuermann** [comment]
Sry, but you need to be more specific about your configuration. OpenPGP keys consist of one primary key and can have many subkeys attached. Subkeys can have flags for encrypt/sign/authenticate. But only the primary key can certify. So what "private key" are you using?

**Comment by Morthawt** [comment]
I assume it should be working now. The fact the other features are working
strongly suggests it. I have since, done more tests and things and I bet
the key on there has no certify capability currently, thinking about it.
Any way, good job on fixing the capabilities.




----------------------------------------
For secure PGP/GnuPG users, if it is *seriously *needed/personal etc
(I rarely use crypto due to more work involved, no ability to search past
emails etc)
The download link for my public key
<https://keyserver2.pgp.com/vkd/DownloadKey.event?keyid=0xDF945F5C614D98E6>
Key Fingerprint: 4C23 C140 E8BE E33B 7858  D986 DF94 5F5C 614D 98E6
----------------------------------------

**Comment by dschuermann** [comment]
Awesome, thanks for debugging and testing!

**Comment by tobiasreischmann** [comment]
I have a Samsung S5 mini and 4.8.1 installed, but I am struggling with the same problem.
When I try to decrypt a message encrypted with my public key using the Yubikey Neo, I get "Failed to chain apdu".
In difference to @Morthawt, my parent key is 2048. I have three keys on my Yubikey Neo:

- My parent key with [SC] capabilities.
- A subkey with [E] capabilities.
- A subkey with [A] capabilities.

It is no problem to sign messages. However, If I try to decrypt messages either directly in Openkeychain or for instance in Android-Password-Store I get the described error. There is also no problem with the encryption or with the key. If I try to decrypt the same message on my linux using the Yubikey, it works as expected.

@Morthawt have you done anything different, than updating to 4.8.1 in order to make encryption work?

**Comment by dschuermann** [comment]
@tobiasreischmann Is
1. Is there more information included in the error message? The full message should look like: "Failed to chain apdu (x/x, lastSW: xx)"
2. Can you try generating a new key using OpenKeychain on your Yubikey? Does this work?
3. Can you try with a different device? Looks like both of you use a Samsung S5 mini

**Comment by dschuermann** [comment]
Related Samsung bugs: https://github.com/Yubico/yubioath-android/issues/9 https://github.com/Yubico/yubioath-android/issues/29

**Comment by Valodim** [comment]
Given how specific the problem is (signing works, encryption doesn't) and how specific the problematic devices are (Samsung S5 Mini), it's likely that this is a platform bug and there is nothing we can do about it.

@tobiasreischmann Is your S5 android version up to date? If we can confirm that this doesn't work with an up to date S5 mini, it's probably better if we just disable nfc with an error message for this device, rather than throwing technical errors from a broken nfc stack at the user.

**Comment by tobiasreischmann** [comment]
Here is some more information:
Device: Samsung Galaxy S 5 mini SM-6800F
Android-Version 6.0.1
openkeychain: 4.8.1
Store: Tried both Play Store and F-Droid
NFC-Method: Tried both SE-SIM-Card (originally SE-SIM-Karte) and Android-OS (originally Android-Betriebssystem)

The exact error message is:
Failed to chain apdu (last SW: 26368)

Additionally, OpenKeychain has problems to read the key, when I try to use it for decryption. This means, before I get the above error message, I usually get the message that the token was removed to early and this for several tries. I directly placed the key at one specific position and did not move it from there on. Using the key for signing usually works in the first run.

Unfortunately, I have currently not the time to investigate with several different testing scenarios. (Maybe in 2 weeks)
Which difference do you could it make to use a encryption key generated by OpenKeychain, @dschuermann ?
Since the stick is working fine, with my linux OS, I don't think there is a problem with the key. The Android-OS or the device could, however, be indeed a problem.

**Comment by dschuermann** [comment]
Regarding the key generation: We were simply wondering if a long transmission over NFC, such as key generation, also leads to this problem.

But we are now sure that it all boils down to a buggy NFC stack in Samsung's Galaxy S5 mini. This is obvious from the other related bug reports.

**Comment by Valodim** [comment]
The error message is SW_WRONG_LENGTH, which is basically some any kind of array out of bounds, e.g. when we are sending a too large buffer. But this *is* a valid response from the card, even if it's an error, which makes it less likely again that this is a platform problem. Ugh.

**Comment by Morthawt** [comment]
I have tested this again and I have been able to certify a public key using my Yubikey Neo's key, but I am unable to decrypt messages. It says:

> Error: Failed to chain apdu
> (0/1, last SW: 26368)
> 
> Take away the security
> Token now and tough TRY
> Again.

**I have tried repeatedly, even taking the case off my phone and still every time I get this. Signing entered text works, encrypting works, certifying a public key works. Decrypting does not work.**

**Comment by taeric** [comment]
Curious if there was ever anything found on this.  I am testing setting up a Yubikey so that I can use password store as my password manager. Most things seem to work, in that I was able to import my key (had to use the url of the token, keyservers seemed to never pick up my key), and I was then able to encrypt a file and send it to my self to decrypt.  That worked, so long as I decrypt on my laptop.  Trying to decrypt anything, including the file I just mentioned, on the phone gives me the reported error.

I have a Moto X4.

**Comment by tobiasreischmann** [comment]
Funny thing is. I got it to work some months ago by removing the preinstalled Android of my Samsumg S5 mini and changing it to linage OS. I have, however, no idea, why everything works now.

**Comment by DrM1KEY** [comment]
Running OpenKeychain version 5.3-beta3 (53002)
on Samsung S5 mini
Model: SM-G800F
Android version 6.0.1
not rooted or modified
Keys generated on Yubikey 5 NFC through OpenKeychain.
Decrypt worked without a problem.

**Comment by taeric** [comment]
I don't know if I'm on a beta or not, wil try and get my phone and check it.  If I ever try the NFC, though, I'm unable to get any of my passwords decrypted.  If, instead, I use a USB C adapter, that seems to reliably work.  

If there is something you'd like me to try, please let me know.

**Comment by DrM1KEY** [comment]
I managed to recreate the Failed to chain apdu message on my S5 mini
After receiving the message I turned off and on NFC, did not clear saved password, touched Yubikey and decrypt was successful.

**Comment by taeric** [comment]
I tried a similar workflow on my end, and didn't seem to have any difference.  I put password in and tap, see the error.  Disable NFC, Reenable NFC.  Try again, no change.

I also made sure to reenable and not reenable Android Beam.  Still no difference. :(

I have *not* tried looking at logs.  I pulled up the code to look once, but there is a surprising amount of code that goes into this and I did not make much headway there.

**Comment by esbullington** [comment]
@taeric Are you on Android P? I also have a motorola x4 and this issue began immediately after I upgraded to Android P. 

I suspect it may be related to the bugfix to [this issue](https://issuetracker.google.com/issues/37005118), which was deployed on Android P. It would involve one of these patches:

https://android-review.googlesource.com/q/status:merged+branch:master+topic:max_transceive_length

**Comment by taeric** [comment]
I am on Android 9, yes.  I've seriously considered changing to the Pixel 3a, in large to get this fixed.  If there are any changes you'd like me to try on my current device, let me know.

**Comment by asirinelli** [comment]
I confirm the bug with a moto x4 and Android 9 together with a Yubikey 5 through NFC. What is working: signing and authenticating. What is not working: deciphering. I am getting the famous error message:
`Failed to chain apdu (0/2, last SW: 26368)`
I have captured a logcat, it is a bit long (libnfc_nci is very verbose). If it can help someone: https://gist.github.com/asirinelli/8169b3b199fa01bf0b3b192491de472c

**Comment by asirinelli** [comment]
Here is the exception raised:

```
10-22 23:20:08.256 20753 20753 D BaseSecurityTokenActivity: Exception in handleSecurityTokenError
10-22 23:20:08.256 20753 20753 D BaseSecurityTokenActivity: java.io.IOException: Failed to chain apdu (0/2, last SW: 26368)
10-22 23:20:08.256 20753 20753 D BaseSecurityTokenActivity: 	at org.sufficientlysecure.keychain.securitytoken.SecurityTokenConnection.transceiveWithChaining(SecurityTokenConnection.java:216)
10-22 23:20:08.256 20753 20753 D BaseSecurityTokenActivity: 	at org.sufficientlysecure.keychain.securitytoken.SecurityTokenConnection.communicate(SecurityTokenConnection.java:190)
10-22 23:20:08.256 20753 20753 D BaseSecurityTokenActivity: 	at org.sufficientlysecure.keychain.securitytoken.operations.PsoDecryptTokenOp.decryptSessionKeyRsa(PsoDecryptTokenOp.java:92)
10-22 23:20:08.256 20753 20753 D BaseSecurityTokenActivity: 	at org.sufficientlysecure.keychain.securitytoken.operations.PsoDecryptTokenOp.verifyAndDecryptSessionKey(PsoDecryptTokenOp.java:77)
10-22 23:20:08.256 20753 20753 D BaseSecurityTokenActivity: 	at org.sufficientlysecure.keychain.ui.SecurityTokenOperationActivity.doSecurityTokenInBackground(SecurityTokenOperationActivity.java:214)
10-22 23:20:08.256 20753 20753 D BaseSecurityTokenActivity: 	at org.sufficientlysecure.keychain.ui.base.BaseSecurityTokenActivity.handleSecurityToken(BaseSecurityTokenActivity.java:439)
10-22 23:20:08.256 20753 20753 D BaseSecurityTokenActivity: 	at org.sufficientlysecure.keychain.ui.base.BaseSecurityTokenActivity$1.doInBackground(BaseSecurityTokenActivity.java:149)
10-22 23:20:08.256 20753 20753 D BaseSecurityTokenActivity: 	at org.sufficientlysecure.keychain.ui.base.BaseSecurityTokenActivity$1.doInBackground(BaseSecurityTokenActivity.java:137)
10-22 23:20:08.256 20753 20753 D BaseSecurityTokenActivity: 	at android.os.AsyncTask$2.call(AsyncTask.java:333)
10-22 23:20:08.256 20753 20753 D BaseSecurityTokenActivity: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
10-22 23:20:08.256 20753 20753 D BaseSecurityTokenActivity: 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
10-22 23:20:08.256 20753 20753 D BaseSecurityTokenActivity: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
10-22 23:20:08.256 20753 20753 D BaseSecurityTokenActivity: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
10-22 23:20:08.256 20753 20753 D BaseSecurityTokenActivity: 	at java.lang.Thread.run(Thread.java:764)
```
