### ISSUE TITLE
GnuK EdDSA Crash

### ISSUE THREAD

**Issue by XDjackieXD** [open-keychain/open-keychain#2234]
When plugging in my GnuK with an EdDSA (Ed25519) subkey, openkeychain crashes with "Unsupported Algorithm ID: 22" in KeyFormat.java line 70.

## Expected Behavior
GnuK can be used with alread imported public key

## Current Behavior
Crash of open-keychain when GnuK gets plugged in.
Logcat shows an IllegalArgumentException: "Unsupported Algorithm ID: 22"

## Possible Solution
Add EdDSA to the Algorithm Tag list of spongycastle/bouncycastle and add handling of EdDSA keys in KeyFormat.java

## Steps to Reproduce (for bugs)
Plug in GnuK that contains an Ed25519 subkey

## Your Environment
* Android Version: 7.1.2 (latest LineageOS)
* OpenKeychain Version: 4.8
* From Google Play or F-Droid?: F-Droid

**Comment by sbach** [comment]
I can confirm the behavior with Gnuk 1.2.5, running on a Maple Mini.

Here is the logcat dump:
```
[...]
D Keychain: Usb transport connected, took 103ms, ATR=3bda11ff81b1fe551f0300318473800180059000e1
D Keychain: USB XferBlock call took 1ms
D Keychain: USB XferBlock call took 1ms
E AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
E AndroidRuntime: Process: org.sufficientlysecure.keychain, PID: 17354
E AndroidRuntime: java.lang.RuntimeException: An error occurred while executing doInBackground()
E AndroidRuntime:        at android.os.AsyncTask$3.done(AsyncTask.java:325)
E AndroidRuntime:        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
E AndroidRuntime:        at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
E AndroidRuntime:        at java.util.concurrent.FutureTask.run(FutureTask.java:242)
E AndroidRuntime:        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
E AndroidRuntime:        at java.lang.Thread.run(Thread.java:761)
E AndroidRuntime: Caused by: java.lang.IllegalArgumentException: Unsupported Algorithm id 22
E AndroidRuntime:        at org.sufficientlysecure.keychain.securitytoken.KeyFormat.fromBytes(KeyFormat.java:70)
E AndroidRuntime:        at org.sufficientlysecure.keychain.securitytoken.OpenPgpCapabilities.parseDdo(OpenPgpCapabilities.java:96)
E AndroidRuntime:        at org.sufficientlysecure.keychain.securitytoken.OpenPgpCapabilities.updateWithData(OpenPgpCapabilities.java:65)
E AndroidRuntime:        at org.sufficientlysecure.keychain.securitytoken.OpenPgpCapabilities.<init>(OpenPgpCapabilities.java:47)
E AndroidRuntime:        at org.sufficientlysecure.keychain.securitytoken.SecurityTokenConnection.refreshConnectionCapabilities(SecurityTokenConnection.java:250)
E AndroidRuntime:        at org.sufficientlysecure.keychain.securitytoken.SecurityTokenConnection.connectToDevice(SecurityTokenConnection.java:206)
E AndroidRuntime:        at org.sufficientlysecure.keychain.securitytoken.SecurityTokenConnection.connectIfNecessary(SecurityTokenConnection.java:183)
E AndroidRuntime:        at org.sufficientlysecure.keychain.ui.base.BaseSecurityTokenActivity$1.doInBackground(BaseSecurityTokenActivity.java:156)
E AndroidRuntime:        at org.sufficientlysecure.keychain.ui.base.BaseSecurityTokenActivity$1.doInBackground(BaseSecurityTokenActivity.java:146)
E AndroidRuntime:        at android.os.AsyncTask$2.call(AsyncTask.java:305)
E AndroidRuntime:        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
E AndroidRuntime:        ... 4 more
[...]
````

**Comment by Valodim** [comment]
Thanks for the report, indeed a couple of wires that would be necessary for eddsa on security tokens to work are missing so far. We will look into it, but it's not high priority for now.

**Comment by Valodim** [comment]
I have this fixed ([gnuk-djb](https://github.com/open-keychain/open-keychain/tree/gnuk-djb) branch), but will wait for cv25519 support to land (#2269) so I can just add support for both algorithms at the same time.
