### ISSUE TITLE
Keyserver search broken on some Android versions

### ISSUE THREAD

**Issue by dschuermann** [open-keychain/open-keychain#2276]
Looks like Conscrypt is trying to use our Bouncy Castle fork, which is stripped from some classes by ProGuard.

The following error happens on a release build (not debug) on Nexus 5 with Android 6.0.1:

```
Keyserver search: https://keyserver.ubuntu.com/pks/lookup?op=index&options=mr&search=dominik%20sch%C3%BCrn using Proxy: DIRECT@
Pinning certificate for https://keyserver.ubuntu.com/pks/lookup?op=index&options=mr&search=dominik%20sch%C3%BCrn
Pinning certificate for https://api.keybase.io/_/api/1.0/user/autocomplete.json?q=dominik+sch%C3%BCrn
IOException at HkpKeyserver
javax.net.ssl.SSLHandshakeException: java.security.NoSuchAlgorithmException: CertPathValidator PKIX implementation not found: java.lang.ClassNotFoundException: org.bouncycastle.jce.provider.PKIXCertPathValidatorSpi
at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:328)
at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.java:299)
at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.java:268)
at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:160)
at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:256)
at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:134)
at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:113)
at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:125)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
at okhttp3.RealCall.execute(RealCall.java:77)
at org.sufficientlysecure.keychain.keyimport.HkpKeyserverClient.query(HkpKeyserverClient.java:366)
at org.sufficientlysecure.keychain.keyimport.HkpKeyserverClient.search(HkpKeyserverClient.java:154)
at org.sufficientlysecure.keychain.keyimport.HkpKeyserverClient.search(HkpKeyserverClient.java:53)
at org.sufficientlysecure.keychain.keyimport.CloudSearch$1.run(CloudSearch.java:65)
at java.lang.Thread.run(Thread.java:818)
Caused by: java.security.cert.CertificateException: java.security.NoSuchAlgorithmException: CertPathValidator PKIX implementation not found: java.lang.ClassNotFoundException: org.bouncycastle.jce.provider.PKIXCertPathValidatorSpi
at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:262)
at com.android.org.conscrypt.TrustManagerImpl.checkServerTrusted(TrustManagerImpl.java:225)
at com.android.org.conscrypt.Platform.checkServerTrusted(Platform.java:115)
at com.android.org.conscrypt.OpenSSLSocketImpl.verifyCertificateChain(OpenSSLSocketImpl.java:556)
at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:324)
... 24 more
Caused by: java.security.NoSuchAlgorithmException: CertPathValidator PKIX implementation not found: java.lang.ClassNotFoundException: org.bouncycastle.jce.provider.PKIXCertPathValidatorSpi
at java.security.Provider$Service.newInstance(Provider.java:1075)
at org.apache.harmony.security.fortress.Engine.getInstance(Engine.java:141)
at java.security.cert.CertPathValidator.getInstance(CertPathValidator.java:106)
at com.android.org.conscrypt.TrustManagerImpl.<init>(TrustManagerImpl.java:131)
at com.android.org.conscrypt.TrustManagerImpl.<init>(TrustManagerImpl.java:115)
at com.android.org.conscrypt.TrustManagerImpl.<init>(TrustManagerImpl.java:108)
at com.android.org.conscrypt.TrustManagerFactoryImpl.engineGetTrustManagers(TrustManagerFactoryImpl.java:80)
at javax.net.ssl.TrustManagerFactory.getTrustManagers(TrustManagerFactory.java:219)
at org.sufficientlysecure.keychain.network.TlsCertificatePinning.createTrustManager(TlsCertificatePinning.java:132)
at org.sufficientlysecure.keychain.network.TlsCertificatePinning.pinCertificate(TlsCertificatePinning.java:104)
at org.sufficientlysecure.keychain.network.OkHttpClientFactory.getClientPinnedIfAvailable(OkHttpClientFactory.java:72)
at org.sufficientlysecure.keychain.keyimport.HkpKeyserverClient.query(HkpKeyserverClient.java:358)
... 4 more
keybase result parsing error
com.textuality.keybase.lib.KeybaseException: Network error attempting Keybase query
at com.textuality.keybase.lib.KeybaseQuery.getFromKeybase(KeybaseQuery.java:82)
at com.textuality.keybase.lib.KeybaseQuery.search(KeybaseQuery.java:51)
at org.sufficientlysecure.keychain.keyimport.KeybaseKeyserverClient.search(KeybaseKeyserverClient.java:57)
at org.sufficientlysecure.keychain.keyimport.KeybaseKeyserverClient.search(KeybaseKeyserverClient.java:33)
at org.sufficientlysecure.keychain.keyimport.CloudSearch$1.run(CloudSearch.java:65)
at java.lang.Thread.run(Thread.java:818)
Caused by: javax.net.ssl.SSLHandshakeException: java.security.NoSuchAlgorithmException: CertPathValidator PKIX implementation not found: java.lang.ClassNotFoundException: org.bouncycastle.jce.provider.PKIXCertPathValidatorSpi
at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:328)
at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.java:299)
at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.java:268)
at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:160)
at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:256)
at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:134)
at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:113)
at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:125)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
at okhttp3.RealCall.execute(RealCall.java:77)
at org.sufficientlysecure.keychain.network.OkHttpKeybaseClient.getUrlResponse(OkHttpKeybaseClient.java:46)
at com.textuality.keybase.lib.KeybaseQuery.getFromKeybase(KeybaseQuery.java:64)
... 5 more
Caused by: java.security.cert.CertificateException: java.security.NoSuchAlgorithmException: CertPathValidator PKIX implementation not found: java.lang.ClassNotFoundException: org.bouncycastle.jce.provider.PKIXCertPathValidatorSpi
at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:262)
at com.android.org.conscrypt.TrustManagerImpl.checkServerTrusted(TrustManagerImpl.java:225)
at com.android.org.conscrypt.Platform.checkServerTrusted(Platform.java:115)
at com.android.org.conscrypt.OpenSSLSocketImpl.verifyCertificateChain(OpenSSLSocketImpl.java:556)
at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:324)
... 26 more
Caused by: java.security.NoSuchAlgorithmException: CertPathValidator PKIX implementation not found: java.lang.ClassNotFoundException: org.bouncycastle.jce.provider.PKIXCertPathValidatorSpi
at java.security.Provider$Service.newInstance(Provider.java:1075)
at org.apache.harmony.security.fortress.Engine.getInstance(Engine.java:141)
at java.security.cert.CertPathValidator.getInstance(CertPathValidator.java:106)
at com.android.org.conscrypt.TrustManagerImpl.<init>(TrustManagerImpl.java:131)
at com.android.org.conscrypt.TrustManagerImpl.<init>(TrustManagerImpl.java:115)
at com.android.org.conscrypt.TrustManagerImpl.<init>(TrustManagerImpl.java:108)
at com.android.org.conscrypt.TrustManagerFactoryImpl.engineGetTrustManagers(TrustManagerFactoryImpl.java:80)
at javax.net.ssl.TrustManagerFactory.getTrustManagers(TrustManagerFactory.java:219)
at org.sufficientlysecure.keychain.network.TlsCertificatePinning.createTrustManager(TlsCertificatePinning.java:132)
at org.sufficientlysecure.keychain.network.TlsCertificatePinning.pinCertificate(TlsCertificatePinning.java:104)
at org.sufficientlysecure.keychain.network.OkHttpClientFactory.getClientPinnedIfAvailable(OkHttpClientFactory.java:72)
at org.sufficientlysecure.keychain.network.OkHttpKeybaseClient.getUrlResponse(OkHttpKeybaseClient.java:39)
... 6 more
```

**Comment by dschuermann** [comment]
Fixed in https://github.com/open-keychain/open-keychain/commit/2f50ce7f025e44cbc62bfd3f08dae06736af4420

Rolled out as 4.9.1

**Comment by cketti** [comment]
How did Conscrypt end up in your classpath?
