### ISSUE TITLE
application crashes, after entering the PIN code when opening a backup copy of the keys

### ISSUE THREAD

**Issue by barclaydemolly** [open-keychain/open-keychain#2315]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Android Version: 
* Device Model: 
* OpenKeychain Version: 
* From Google Play or F-Droid?:

**Comment by 5h4d0ww0lf** [comment]
@barclaydemolly Probably malformed keys. Probably created a backup on some OpenPGP implementation instead exporting them. Awaiting further informations.

**Comment by barclaydemolly** [comment]
1. Creating a backup of the keys in 5.0.2.
2. opening files * sec.pgp and * pub.pgp through a backup / restore option selecting the output file.
3. the program asks for the input of the transfer code, after entering it, again requests it again a second time. After entering, the program crashes.

**Comment by Craeckie** [comment]
Restore doesn't work for me on 5.1.1, backup was also created on 5.1.1. Restore worked for me on 5.0.2 with the same backup after that I could upgrade to 5.1.1.

There is also a second issue: No error message if you enter the wrong key, it just reopens "Enter transfer code".

**Comment by bwildenhain** [comment]
I also get a crash when trying to restore a backup  with OpenKeychain 5.7.5 from F-Droid made on LineageOS 19 with the same version of OpenKeychain. The following seems to be the relevant logcat output:

`FATAL EXCEPTION: ModernAsyncTask #1
Process: org.sufficientlysecure.keychain, PID: 6767
java.lang.RuntimeException: An error occurred while executing doInBackground()                                                                                   05-08 23:51:50.717  6767 12827 E AndroidRuntime:        at androidx.loader.content.ModernAsyncTask$3.done(ModernAsyncTask.java:6)
       at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
       at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
       at java.util.concurrent.FutureTask.run(FutureTask.java:271)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:920)
Caused by: java.lang.IllegalArgumentException: Invalid UTF-8 input
       at org.bouncycastle.util.Strings.fromUTF8ByteArray(Unknown Source:20)
       at org.bouncycastle.bcpg.UserIDPacket.getID(UserIDPacket.java:1)
       at org.bouncycastle.openpgp.PGPPublicKey.getUserIDs(PGPPublicKey.java:4)
       at org.sufficientlysecure.keychain.pgp.UncachedPublicKey.getPrimaryUserIdWithFallback(UncachedPublicKey.java:2)
       at org.sufficientlysecure.keychain.keyimport.ImportKeysListEntry.<init>(ImportKeysListEntry.java:9)
       at org.sufficientlysecure.keychain.keyimport.processing.ImportKeysListLoader.generateListOfKeyrings(ImportKeysListLoader.java:6)
       at org.sufficientlysecure.keychain.keyimport.processing.ImportKeysListLoader.loadInBackground(ImportKeysListLoader.java:9)
       at org.sufficientlysecure.keychain.keyimport.processing.ImportKeysListLoader.loadInBackground(ImportKeysListLoader.java:1)
       at androidx.loader.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:1)
       at androidx.loader.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:2)
       at androidx.loader.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:1)
       at androidx.loader.content.ModernAsyncTask$2.call(ModernAsyncTask.java:3)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       ... 3 more
`
