### ISSUE TITLE
java.lang.IllegalStateException: Apps may not schedule more than 100 distinct jobs

### ISSUE THREAD

**Issue by Timvde** [open-keychain/open-keychain#2443]
OpenKeychain crashes on start up. This suddenly started to happen. I did not update the app, and I think I have used it in the past successfully on my current ROM (since I last updated it over a month ago...).

## Environment

* Android Version: Android 8.1 (unofficial LineageOS 15.1: https://forum.xda-developers.com/oneplus-x/development/rom-lineageos-15-1-oneplus-x-t3747380)
* Device Model: OnePlus X
* OpenKeychain Version: 5.2
* From Google Play or F-Droid?: F-Droid
* Other details that might be relevant: using xposed, microG
 
## Full log
From app start until app force close, I'm not sure if all is relevant, but I'm not familiar enough with Android to filter.

```
02-21 19:51:41.600  1947 11599 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=org.sufficientlysecure.keychain/.ui.MainActivity bnds=[438,1372][642,1751]} from uid 10025
02-21 19:51:41.729  1947  5018 I ActivityManager: Start proc 13541:org.sufficientlysecure.keychain/u0a95 for activity org.sufficientlysecure.keychain/.ui.MainActivity
02-21 19:51:41.730 13541 13541 W main    : type=1400 audit(0.0:15499): avc: denied { read } for name="u:object_r:wcnss_prop:s0" dev="tmpfs" ino=2078 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:wcnss_prop:s0 tclass=file permissive=0
02-21 19:51:41.730 13541 13541 W main    : type=1400 audit(0.0:15500): avc: denied { read } for name="u:object_r:wififtmd_prop:s0" dev="tmpfs" ino=2079 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:wififtmd_prop:s0 tclass=file permissive=0
02-21 19:51:41.730 13541 13541 W main    : type=1400 audit(0.0:15501): avc: denied { read } for name="u:object_r:spcomlib_prop:s0" dev="tmpfs" ino=2080 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:spcomlib_prop:s0 tclass=file permissive=0
02-21 19:51:41.730 13541 13541 W main    : type=1400 audit(0.0:15502): avc: denied { read } for name="u:object_r:vendor_rild_libpath_prop:s0" dev="tmpfs" ino=2081 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:vendor_rild_libpath_prop:s0 tclass=file permissive=0
02-21 19:51:41.730 13541 13541 W main    : type=1400 audit(0.0:15503): avc: denied { read } for name="u:object_r:qdma_prop:s0" dev="tmpfs" ino=2082 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:qdma_prop:s0 tclass=file permissive=0
02-21 19:51:41.730 13541 13541 W main    : type=1400 audit(0.0:15504): avc: denied { read } for name="u:object_r:per_mgr_state_prop:s0" dev="tmpfs" ino=2083 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:per_mgr_state_prop:s0 tclass=file permissive=0
02-21 19:51:41.730 13541 13541 W main    : type=1400 audit(0.0:15505): avc: denied { read } for name="u:object_r:bg_daemon_prop:s0" dev="tmpfs" ino=2084 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:bg_daemon_prop:s0 tclass=file permissive=0
02-21 19:51:41.830  1947  5010 W ActivityManager: Slow operation: 74ms so far, now at attachApplicationLocked: after mServices.attachApplicationLocked
02-21 19:51:41.838 13541 13541 W zygote  : ClassLoaderContext size mismatch. expected=1, actual=2 (PCL[] | PCL[];PCL[/data/dalvik-cache/xposed_XResourcesSuperClass.dex*2802528989:/data/dalvik-cache/xposed_XTypedArraySuperClass.dex*708326108])
02-21 19:51:41.962 13541 13541 D PackageManagerHelper: androidx.work.impl.background.systemjob.SystemJobService enabled
02-21 19:51:41.963 13541 13541 D Schedulers: Created SystemJobScheduler and enabled SystemJobService
02-21 19:51:41.965 13541 13541 D PackageManagerHelper: androidx.work.impl.background.systemalarm.SystemAlarmService disabled
02-21 19:51:42.183 13541 13563 D SystemJobScheduler: Scheduling work ID 6b8a298a-4a44-420a-818b-2ba85a17d398 Job ID 389
02-21 19:51:42.184  1947 15377 W JobSchedulerService: Too many jobs for uid 10095
02-21 19:51:42.186 13541 13563 E AndroidRuntime: FATAL EXCEPTION: pool-3-thread-1
02-21 19:51:42.186 13541 13563 E AndroidRuntime: Process: org.sufficientlysecure.keychain, PID: 13541
02-21 19:51:42.186 13541 13563 E AndroidRuntime: java.lang.IllegalStateException: Apps may not schedule more than 100 distinct jobs
02-21 19:51:42.186 13541 13563 E AndroidRuntime:        at android.os.Parcel.readException(Parcel.java:2021)
02-21 19:51:42.186 13541 13563 E AndroidRuntime:        at android.os.Parcel.readException(Parcel.java:1959)
02-21 19:51:42.186 13541 13563 E AndroidRuntime:        at android.app.job.IJobScheduler$Stub$Proxy.schedule(IJobScheduler.java:180)
02-21 19:51:42.186 13541 13563 E AndroidRuntime:        at android.app.JobSchedulerImpl.schedule(JobSchedulerImpl.java:44)
02-21 19:51:42.186 13541 13563 E AndroidRuntime:        at androidx.work.impl.background.systemjob.SystemJobScheduler.scheduleInternal(SystemJobScheduler.java:85)
02-21 19:51:42.186 13541 13563 E AndroidRuntime:        at androidx.work.impl.background.systemjob.SystemJobScheduler.schedule(SystemJobScheduler.java:64)
02-21 19:51:42.186 13541 13563 E AndroidRuntime:        at androidx.work.impl.Schedulers.scheduleInternal(Schedulers.java:98)
02-21 19:51:42.186 13541 13563 E AndroidRuntime:        at androidx.work.impl.Schedulers.schedule(Schedulers.java:69)
02-21 19:51:42.186 13541 13563 E AndroidRuntime:        at androidx.work.impl.utils.EnqueueRunnable.scheduleWorkInBackground(EnqueueRunnable.java:109)
02-21 19:51:42.186 13541 13563 E AndroidRuntime:        at androidx.work.impl.utils.EnqueueRunnable.run(EnqueueRunnable.java:81)
02-21 19:51:42.186 13541 13563 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
02-21 19:51:42.186 13541 13563 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
02-21 19:51:42.186 13541 13563 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:764)
02-21 19:51:42.190  1947 11583 W ActivityManager:   Force finishing activity org.sufficientlysecure.keychain/.ui.MainActivity
```

**Comment by Timvde** [comment]
If someone else reads this: I force closed OpenKeychain and cleared the app cache. That worked.

**Comment by Orhideous** [comment]
@Timvde Thanks! This helps me :)

**Comment by serianox** [comment]
@Timvde You just saved me. *<:o)

**Comment by matachi** [comment]
Force stopping the app was enough for me. I didn't need to clear its cache.

However, I had already tried restarting my phone, but that didn't help.
