### ISSUE TITLE
The application still has some bugs

### ISSUE THREAD

**Issue by AssassinRain** [open-keychain/open-keychain#2479]
Hello. I noticed some crashes in logs. The corresponding commit version of code is 73f428a, and application version is 1.4.6.

## 1.org.sufficientlysecure.keychain.ui.UsbEventReceiverActivity
The exception trace is:
*FATAL EXCEPTION: main
java.lang.RuntimeException: Unable to resume activity {org.sufficientlysecure.keychain/org.sufficientlysecure.keychain.ui.UsbEventReceiverActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.hardware.usb.UsbDevice.getDeviceName()' on a null object reference
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3790)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3830)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3038)
	at android.app.ActivityThread.-wrap11(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6944)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.hardware.usb.UsbDevice.getDeviceName()' on a null object reference
	at org.sufficientlysecure.keychain.securitytoken.UsbConnectionDispatcher.requestPermissionForUsbDevice(UsbConnectionDispatcher.java:128)
	at org.sufficientlysecure.keychain.ui.UsbEventReceiverActivity.onResume(UsbEventReceiverActivity.java:39)
	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1361)
	at android.app.Activity.performResume(Activity.java:7361)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3765)*

## 2.org.sufficientlysecure.keychain.ui.ImportKeysProxyActivity
The exception trace is:
*FATAL EXCEPTION: main
java.lang.RuntimeException: Unable to start activity ComponentInfo{org.sufficientlysecure.keychain/org.sufficientlysecure.keychain.ui.ImportKeysProxyActivity}: java.lang.NullPointerException: Attempt to read from null array
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2957)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3032)
	at android.app.ActivityThread.-wrap11(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6944)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
Caused by: java.lang.NullPointerException: Attempt to read from null array
	at org.sufficientlysecure.keychain.ui.ImportKeysProxyActivity.handleActionNdefDiscovered(ImportKeysProxyActivity.java:288)
	at org.sufficientlysecure.keychain.ui.ImportKeysProxyActivity.handleActions(ImportKeysProxyActivity.java:97)
	at org.sufficientlysecure.keychain.ui.ImportKeysProxyActivity.onCreate(ImportKeysProxyActivity.java:79)
	at android.app.Activity.performCreate(Activity.java:7183)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1220)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2910)*
## 3.org.sufficientlysecure.keychain.ui.keyview.ViewKeyActivity
The exception trace is:
*FATAL EXCEPTION: main
java.lang.RuntimeException: Unable to start activity ComponentInfo{org.sufficientlysecure.keychain/org.sufficientlysecure.keychain.ui.keyview.ViewKeyActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2957)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3032)
	at android.app.ActivityThread.-wrap11(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6944)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
	at org.sufficientlysecure.keychain.ui.keyview.ViewKeyActivity.onCreate(ViewKeyActivity.java:244)
	at android.app.Activity.performCreate(Activity.java:7183)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1220)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2910)*
## 3.org.sufficientlysecure.keychain.ui.EncryptFilesActivity
The exception trace is:
*FATAL EXCEPTION: main
java.lang.RuntimeException: Unable to start activity ComponentInfo{org.sufficientlysecure.keychain/org.sufficientlysecure.keychain.ui.EncryptFilesActivity}: java.lang.NullPointerException: name
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2957)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3032)
	at android.app.ActivityThread.-wrap11(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6944)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
Caused by: java.lang.NullPointerException: name
	at com.android.internal.util.Preconditions.checkNotNull(Preconditions.java:128)
	at android.content.ContentResolver.acquireUnstableContentProviderClient(ContentResolver.java:1888)
	at android.provider.DocumentsContract.getDocumentThumbnail(DocumentsContract.java:1042)
	at org.sufficientlysecure.keychain.util.FileHelper.getThumbnail(FileHelper.java:222)
	at org.sufficientlysecure.keychain.ui.EncryptFilesFragment$FilesAdapter$ViewModel.<init>(EncryptFilesFragment.java:794)
	at org.sufficientlysecure.keychain.ui.EncryptFilesFragment$FilesAdapter.add(EncryptFilesFragment.java:927)
	at org.sufficientlysecure.keychain.ui.EncryptFilesFragment.processPendingInputUris(EncryptFilesFragment.java:259)
	at org.sufficientlysecure.keychain.ui.EncryptFilesFragment.onCreateView(EncryptFilesFragment.java:168)
	at android.support.v4.app.Fragment.performCreateView(Fragment.java:2346)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1428)
	at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1759)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1827)
	at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:797)
	at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2596)
	at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2383)
	at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2338)
	at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2245)
	at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3248)
	at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3200)
	at android.support.v4.app.FragmentController.dispatchActivityCreated(FragmentController.java:195)
	at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:597)
	at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:177)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1340)
	at android.app.Activity.performStart(Activity.java:7200)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2920)*
### The command to trigger it is: adb shell am start -n org.sufficientlysecure.keychain/org.sufficientlysecure.keychain.ui.EncryptFilesActivity -d I

Because all these activities are exported ones, i.e., be exposed to outside, they may receive unfriendly commands and then lead to app crash. After investigation, we found that the missing of null checkers causes those crashes.
Please help to confirm whether they are true bugs. We believe that fixing these bugs will further improve the robustness of this app.

**Comment by Grossdm** [comment]
Just a head's up - I suspect you will wait a long time before anyone bothers to read an issue with such a non-descriptive title.

I recommend that you change it do a short description of whatever error you had.
(I certainly didn't read through your log dump, trying to see if you had a legitimate issue.)

**Comment by AssassinRain** [comment]
I'm very sorry about that, but now I change the title and add a short description. Thank you for your reply.

**Comment by hanada31** [comment]
Hello, I noticed several similar problems. The app will crash when specific adb command is received,

1. org.sufficientlysecure.keychain.ui.DebugActionsActivity

ADB command: adb shell am start -n org.sufficientlysecure.keychain/org.sufficientlysecure.keychain.ui.DebugActionsActivity

FATAL EXCEPTION: main
java.lang.RuntimeException: Unable to start activity ComponentInfo{org.sufficientlysecure.keychain/org.sufficientlysecure.keychain.ui.DeleteKeyDialogActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.app.Dialog.setOwnerActivity(android.app.Activity)' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2957)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3032)
	at android.app.ActivityThread.-wrap11(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6944)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.app.Dialog.setOwnerActivity(android.app.Activity)' on a null object reference
	at android.support.v4.app.DialogFragment.onActivityCreated(DialogFragment.java:415)
	at android.support.v4.app.Fragment.performActivityCreated(Fragment.java:2355)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1451)
	at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1759)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1827)
	at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:797)
	at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2596)
	at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2383)
	at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2338)
	at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2245)
	at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3248)
	at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3200)
	at android.support.v4.app.FragmentController.dispatchActivityCreated(FragmentController.java:195)
	at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:597)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1340)
	at android.app.Activity.performStart(Activity.java:7200)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2920)

2. org.sufficientlysecure.keychain.ui.keyview.ViewKeyActivity
The same.

3. org.sufficientlysecure.keychain.ui.ViewKeyAdvActivity
The same.
