### ISSUE TITLE
Crashes with NFC Security token on GrapheneOS

### ISSUE THREAD

**Issue by randomisresistance** [open-keychain/open-keychain#2806]
Since a while the app crashes when beeing used with a NFT Token and K-9 Mail 

## Expected Behavior
App does not crash and dcrypts mail

## Current Behavior
App crashes after decryption was done properly

## Possible Solution
Not sure if this is an issue in the App or GrapehenOS.

## Steps to Reproduce (for bugs)

1. Allow NFC access
2. Open Encrypted Mail in K-9
3. Enter PIN
4. Hold NFC Token against phone
CRASH

## Context
```
type: crash
osVersion: google/bluejay/bluejay:13/TQ1A.221205.011/2022122000:user/release-keys
package: org.sufficientlysecure.keychain:57500
process: org.sufficientlysecure.keychain
processUptime: 20576 + 190 ms

java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$4.done(AsyncTask.java:415)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:381)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:250)
	at java.util.concurrent.FutureTask.run(FutureTask.java:269)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.SecurityException: Permission Denial: Tag ( ID: 04 77 33 2A 70 71 80 ) is out of date
	at android.nfc.Tag.getTagService(Tag.java:381)
	at android.nfc.tech.BasicTagTechnology.isConnected(BasicTagTechnology.java:63)
	at android.nfc.tech.IsoDep.isConnected(IsoDep.java:40)
	at nordpol.android.AndroidCard.isConnected(AndroidCard.java:1)
	at org.sufficientlysecure.keychain.securitytoken.NfcTransport.isConnected(NfcTransport.java:1)
	at org.sufficientlysecure.keychain.securitytoken.SecurityTokenConnection.isConnected(SecurityTokenConnection.java:1)
	at org.sufficientlysecure.keychain.ui.SecurityTokenOperationActivity$3.doInBackground(SecurityTokenOperationActivity.java:2)
	at org.sufficientlysecure.keychain.ui.SecurityTokenOperationActivity$3.doInBackground(SecurityTokenOperationActivity.java:1)
	at android.os.AsyncTask$3.call(AsyncTask.java:394)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	... 4 more

```

## Your Environment
* Android Version: GrapheneOS latest
* Device Model: Pixel 6a
* OpenKeychain Version: 7.5.7
* F-Droid

**Comment by DevSpork** [comment]
I can reproduce this on stock Android 13.

**Comment by Flash1232** [comment]
Duplicate issue of fix in !2804

**Comment by Valodim** [comment]
fixed, will be released soon
