### ISSUE TITLE
Crash If i try to import a private key

### ISSUE THREAD

**Issue by Tealk** [open-keychain/open-keychain#2854]
```
type: crash
osVersion: google/oriole/oriole:13/TQ3A.230901.001/2023100300:user/release-keys
package: org.sufficientlysecure.keychain:58902
process: org.sufficientlysecure.keychain
processUptime: 17799 + 232 ms
installer: com.looker.droidify

java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=382065989, result=-1, data=Intent { dat=content://org.nextcloud.documents/... flg=0x1 }} to activity {org.sufficientlysecure.keychain/org.sufficientlysecure.keychain.ui.ImportKeysActivity}: android.os.NetworkOnMainThreadException
	at android.app.ActivityThread.deliverResults(ActivityThread.java:5355)
	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5394)
	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:67)
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:138)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2313)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7940)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
Caused by: android.os.NetworkOnMainThreadException
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3030)
	at android.os.Parcel.createException(Parcel.java:3004)
	at android.os.Parcel.readException(Parcel.java:2980)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:190)
	at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:153)
	at android.content.ContentProviderProxy.openTypedAssetFile(ContentProviderNative.java:780)
	at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:2048)
	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1863)
	at android.content.ContentResolver.openInputStream(ContentResolver.java:1539)
	at org.sufficientlysecure.keychain.util.FileHelper.isEncryptedFile(FileHelper.java:1)
	at org.sufficientlysecure.keychain.ui.ImportKeysFileFragment.startImportingKeys(ImportKeysFileFragment.java:1)
	at org.sufficientlysecure.keychain.ui.ImportKeysFileFragment.onActivityResult(ImportKeysFileFragment.java:5)
	at androidx.fragment.app.FragmentManager$9.onActivityResult(FragmentManager.java:10)
	at androidx.fragment.app.FragmentManager$9.onActivityResult(FragmentManager.java:1)
	at androidx.activity.result.ActivityResultRegistry.doDispatch(ActivityResultRegistry.java:5)
	at androidx.activity.result.ActivityResultRegistry.dispatchResult(ActivityResultRegistry.java:2)
	at androidx.activity.ComponentActivity.onActivityResult(ComponentActivity.java:1)
	at androidx.fragment.app.FragmentActivity.onActivityResult(FragmentActivity.java:2)
	at org.sufficientlysecure.keychain.ui.ImportKeysActivity.onActivityResult(ImportKeysActivity.java:3)
	at android.app.Activity.dispatchActivityResult(Activity.java:8712)
	at android.app.ActivityThread.deliverResults(ActivityThread.java:5348)
	... 15 more

```

**Comment by Tealk** [comment]
I think it might have to do with #1568, I tried to load the keys from the folder of the nextcloud. Locally it worked.

**Comment by dschultzca** [comment]
Same issue here, copied file from Nextcloud folder to a local folder and import was successful.
Phone: Android 10
OpenKeychain: 6.0.4
