### ISSUE TITLE
6.x.x : Crash when tryind to add an additional email address at key creation

### ISSUE THREAD

**Issue by Sami32** [open-keychain/open-keychain#2897]
When i want manually create my key (Manage my keys) and select "Add an additional email address" OpenKeychain crash.
AFAICR it worked fine before version 6.x.x.

![IMG_20240301_014613](https://github.com/open-keychain/open-keychain/assets/18471069/0dd8f65d-ed7b-4f1b-9b9d-87f57badac23)

## Your Environment
* Android Version: Google Android 7.0
* Device Model: Xiaomi Redmi Note 4
* OpenKeychain Version: 6.0.2
* From Google Play or F-Droid?: F-Droid

**Comment by rafaelazvdo** [comment]
This bug is also present in version 6.0.4.

**Comment by srleonbr** [comment]
I'm also having the same problem. Fortunately, it is possible to add emails later, both in the advanced key generation options and after they are ready. But that's annoying.

**Comment by 825i** [comment]
Also having this issue on Xperia 1V

**Comment by 7heMech** [comment]
Samsung note 10+

**Comment by valerio-bozzolan** [comment]
Crash confirmed on version 6.0.4 (F-Droid) from Android 15, Fairphone 5.

Stack trace obtained from `adb logcat`:

```
06-05 18:14:14.995 20049 20049 D AndroidRuntime: Shutting down VM
06-05 18:14:14.996 20049 20049 E AndroidRuntime: FATAL EXCEPTION: main
06-05 18:14:14.996 20049 20049 E AndroidRuntime: Process: org.sufficientlysecure.keychain, PID: 20049
06-05 18:14:14.996 20049 20049 E AndroidRuntime: java.lang.ClassCastException: androidx.appcompat.widget.AppCompatTextView cannot be cast to androidx.appcompat.widget.AppCompatEditText
06-05 18:14:14.996 20049 20049 E AndroidRuntime:        at org.sufficientlysecure.keychain.ui.dialog.AddEmailDialogFragment.onCreateDialog(SourceFile:52)
06-05 18:14:14.996 20049 20049 E AndroidRuntime:        at androidx.fragment.app.DialogFragment.prepareDialog(SourceFile:14)
06-05 18:14:14.996 20049 20049 E AndroidRuntime:        at androidx.fragment.app.DialogFragment.onGetLayoutInflater(SourceFile:17)
06-05 18:14:14.996 20049 20049 E AndroidRuntime:        at androidx.fragment.app.Fragment.performGetLayoutInflater(SourceFile:1)
06-05 18:14:14.996 20049 20049 E AndroidRuntime:        at androidx.fragment.app.FragmentStateManager.createView(SourceFile:43)
06-05 18:14:14.996 20049 20049 E AndroidRuntime:        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(SourceFile:117)
06-05 18:14:14.996 20049 20049 E AndroidRuntime:        at androidx.fragment.app.FragmentManager.executeOpsTogether(SourceFile:278)
06-05 18:14:14.996 20049 20049 E AndroidRuntime:        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(SourceFile:85)
06-05 18:14:14.996 20049 20049 E AndroidRuntime:        at androidx.fragment.app.FragmentManager.execPendingActions(SourceFile:22)
06-05 18:14:14.996 20049 20049 E AndroidRuntime:        at androidx.fragment.app.FragmentManager$5.run(SourceFile:4)
06-05 18:14:14.996 20049 20049 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:991)
06-05 18:14:14.996 20049 20049 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:102)
06-05 18:14:14.996 20049 20049 E AndroidRuntime:        at android.os.Looper.loopOnce(Looper.java:232)
06-05 18:14:14.996 20049 20049 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:317)
06-05 18:14:14.996 20049 20049 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:8934)
06-05 18:14:14.996 20049 20049 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
06-05 18:14:14.996 20049 20049 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:591)
06-05 18:14:14.996 20049 20049 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:911)
```

In short:

```
java.lang.ClassCastException: androidx.appcompat.widget.AppCompatTextView cannot be cast to androidx.appcompat.widget.AppCompatEditText
```

## Exploration

So, we have this `AppCompatEditText`:

https://github.com/open-keychain/open-keychain/blob/8d0bd1f8537fb3a795fda8161f730a313ef7b01c/OpenKeychain/src/main/res/layout/add_email_dialog.xml#L17

And it's casted to a `AppCompatEditText`:

https://github.com/open-keychain/open-keychain/blob/8d0bd1f8537fb3a795fda8161f730a313ef7b01c/OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/dialog/AddEmailDialogFragment.java#L83

https://github.com/open-keychain/open-keychain/blob/8d0bd1f8537fb3a795fda8161f730a313ef7b01c/OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/dialog/AddEmailDialogFragment.java#L55

So what's wrong? uhmmm

Additional interesting thing: the mentioned class seems not used directly:

```
$ grep -R 'AppCompatTextView' .
no results
```

I wonder if something else (a dependency?) is using the same ID, conflicting it (?)
