### ISSUE TITLE
NullPointerException in PassphraseCacheService

### ISSUE THREAD

**Issue by dschuermann** [open-keychain/open-keychain#985]
From G Play
Android 4.3
Xperia T (LT30p)

```
java.lang.RuntimeException: Unable to start service org.sufficientlysecure.keychain.service.PassphraseCacheService@4209e988 with Intent { act=org.sufficientlysecure.keychain.action.PASSPHRASE_CACHE_GET cmp=org.sufficientlysecure.keychain/.service.PassphraseCacheService (has extras) }: java.lang.NullPointerException
at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2785)
at android.app.ActivityThread.access$1900(ActivityThread.java:150)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1395)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:213)
at android.app.ActivityThread.main(ActivityThread.java:5225)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:525)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:741)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:557)
at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.NullPointerException
at org.sufficientlysecure.keychain.provider.CachedPublicKeyRing.getSecretKeyType(CachedPublicKeyRing.java:203)
at org.sufficientlysecure.keychain.service.PassphraseCacheService.getCachedPassphraseImpl(PassphraseCacheService.java:230)
at org.sufficientlysecure.keychain.service.PassphraseCacheService.onStartCommand(PassphraseCacheService.java:377)
at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2768)
... 10 more
```

**Comment by Valodim** [comment]
The generic data method didn't throw an exception but returned null if no data was found. Might be fixed in 920fbdfb427877d89d9a6bcf62b6dc9fba846c2e but not 100% sure
