### ISSUE TITLE
NoSuchElementException in UncachedPublicKey.getPrimaryUserIdWithFallback

### ISSUE THREAD

**Issue by dschuermann** [open-keychain/open-keychain#994]
Android 4.4
OK v3.1.1

"tried to import from a USB drive."

```
java.lang.RuntimeException: An error occured while executing doInBackground()
at android.support.v4.content.ModernAsyncTask$3.done(ModernAsyncTask.java:137)
at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
at java.util.concurrent.FutureTask.run(FutureTask.java:242)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
at java.lang.Thread.run(Thread.java:841)
Caused by: java.util.NoSuchElementException
at java.util.ArrayList$ArrayListIterator.next(ArrayList.java:576)
at org.sufficientlysecure.keychain.pgp.UncachedPublicKey.getPrimaryUserIdWithFallback(UncachedPublicKey.java:194)
at org.sufficientlysecure.keychain.keyimport.ImportKeysListEntry.<init>(ImportKeysListEntry.java:284)
at org.sufficientlysecure.keychain.ui.adapter.ImportKeysListLoader.generateListOfKeyrings(ImportKeysListLoader.java:133)
at org.sufficientlysecure.keychain.ui.adapter.ImportKeysListLoader.loadInBackground(ImportKeysListLoader.java:82)
at org.sufficientlysecure.keychain.ui.adapter.ImportKeysListLoader.loadInBackground(ImportKeysListLoader.java:39)
at android.support.v4.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:242)
at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:51)
at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:40)
at android.support.v4.content.ModernAsyncTask$2.call(ModernAsyncTask.java:123)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
... 3 more
```

**Comment by Valodim** [comment]
During import, there may be keys which have no user id at all. The import had a "if no primary uid is known, just pick the first" mechanic which didn't check if a first even existed. I made this a little more robust, but needs testing.

**Comment by dschuermann** [comment]
I will close this now. If it happens again and we get Google Play reports we can open a new issue.
