### ISSUE TITLE
ArrayIndexOutOfBoundsException in PreferencesKeyServerActivity

### ISSUE THREAD

**Issue by dschuermann** [open-keychain/open-keychain#998]
From G Play.
3.1.1
Optimus L5 (m4)
"hacker om mijn heen"

```
java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
at java.util.Vector.arrayIndexOutOfBoundsException(Vector.java:907)
at java.util.Vector.elementAt(Vector.java:328)
at java.util.Vector.get(Vector.java:442)
at org.sufficientlysecure.keychain.ui.PreferencesKeyServerActivity$3.onClick(PreferencesKeyServerActivity.java:90)
at android.view.View.performClick(View.java:3524)
at android.view.View$PerformClick.run(View.java:14194)
at android.os.Handler.handleCallback(Handler.java:605)
at android.os.Handler.dispatchMessage(Handler.java:92)
at android.os.Looper.loop(Looper.java:137)
at android.app.ActivityThread.main(ActivityThread.java:4476)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:816)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:583)
at dalvik.system.NativeStart.main(Native Method)
```

**Comment by Valodim** [comment]
no longer relevant, the preference dialog in question was rewritten by adithya
